/-
Copyright (c) 2026 Lean FRO LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Author: Emilio J. Gallego Arias
-/

-- Generated by scripts/bindings/generate-lean-bindings.mjs. Do not edit.

module

public import Vir.Js.Types

public section

namespace Lean.Vir

namespace Js.Array

/--
Generated binding for reviewed VIR protocol `javascript.array.empty`.

Constructs an empty native JavaScript Array.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1`: receiver none; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "js.array.empty"]
opaque empty
    {α : Type} :
    RuntimeM (Lean.Vir.Js.Array α)

/--
Generated binding for reviewed VIR protocol `javascript.array.push`.

Selects the one-item arity of Array<T>.push(...items: T[]): number. The receiver and item share T; no erasure or conversion occurs.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1`: receiver none; array js-resource/borrowed/call; value js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "js.array.push"]
opaque push
    {α : Type}
    (array : @& Lean.Vir.Js.Array α)
    (value : @& Lean.Vir.Js α) :
    RuntimeM (Lean.Vir.Js Float)

/--
Generated binding for reviewed VIR protocol `javascript.array.length`.

Returns the exact native JavaScript Number stored in Array.length.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1`: receiver none; array js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "js.array.length"]
opaque length
    {α : Type}
    (array : @& Lean.Vir.Js.Array α) :
    RuntimeM (Lean.Vir.Js Float)

/--
Generated binding for reviewed VIR protocol `javascript.array.item`.

Preserves Array<T>'s [n: number]: T relationship. This is the TypeScript unchecked-index lane: native holes and missing entries remain undefined, without a bounds check or null conversion. It does not implement noUncheckedIndexedAccess.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1`: receiver none; array js-resource/borrowed/call; index js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "js.array.item"]
opaque get
    {α : Type}
    (array : @& Lean.Vir.Js.Array α)
    (index : @& Lean.Vir.Js Float) :
    RuntimeM (Lean.Vir.Js α)

end Js.Array

namespace Js.Function

/--
Generated binding for reviewed VIR protocol `javascript.function.of-lean-unary`.

Explicitly converts a transferred Lean unary callback into an ordinary JavaScript function with the same call shape.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1`: receiver none; callback callback/owned/until-release; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js_explicit_conversion "js.value.function.unary"]
opaque ofLean
    {α : Type}
    {β : Type}
    (callback : Lean.Vir.Js α → RuntimeM (Lean.Vir.Js β)) :
    RuntimeM (Lean.Vir.Js.Function1 (Lean.Vir.Js α) (Lean.Vir.Js β))

/--
Generated binding for reviewed VIR protocol `javascript.function.of-lean-unary-void`.

Explicitly converts a transferred Lean unary callback with a discarded result into an ordinary JavaScript function.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1`: receiver none; callback callback/owned/until-release; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js_explicit_conversion "js.value.function.unaryVoid"]
opaque ofLeanVoid
    {α : Type}
    (callback : Lean.Vir.Js α → RuntimeM Unit) :
    RuntimeM (Lean.Vir.Js.Function1 (Lean.Vir.Js α) Unit)

/--
Generated binding for reviewed VIR protocol `javascript.function.call`.

Calls an exact unary JavaScript function with one exact JavaScript argument and returns its exact JavaScript result.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1`: receiver none; function js-resource/borrowed/call; argument js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "js.function.call"]
opaque call
    {α : Type}
    {β : Type}
    (function : @& Lean.Vir.Js.Function1 (Lean.Vir.Js α) (Lean.Vir.Js β))
    (argument : @& Lean.Vir.Js α) :
    RuntimeM (Lean.Vir.Js β)

/--
Generated binding for reviewed VIR protocol `javascript.function.call-void`.

Calls the exact JavaScript function with one exact JavaScript argument and discards its void result.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1`: receiver none; function js-resource/borrowed/call; argument js-resource/borrowed/call; result immediate/value.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "js.function.callVoid"]
opaque callVoid
    {α : Type}
    (function : @& Lean.Vir.Js.Function1 (Lean.Vir.Js α) Unit)
    (argument : @& Lean.Vir.Js α) :
    RuntimeM Unit

end Js.Function

namespace Js.NodeList

/--
Generated binding for reviewed VIR protocol `javascript.node-list.length`.

Returns the exact native JavaScript Number stored in NodeList.length.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1`: receiver none; nodes js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "js.nodeList.length"]
opaque length
    {α : Type}
    (nodes : @& Lean.Vir.Js.NodeList α) :
    RuntimeM (Lean.Vir.Js Float)

/--
Generated binding for reviewed VIR protocol `javascript.node-list.item`.

Calls NodeList.item and represents a missing entry as JavaScript null.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1`: receiver none; nodes js-resource/borrowed/call; index js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "js.nodeList.item"]
opaque item
    {α : Type}
    (nodes : @& Lean.Vir.Js.NodeList (Lean.Vir.Js α))
    (index : @& Lean.Vir.Js Float) :
    RuntimeM (Lean.Vir.Js.Nullable α)

/--
Generated binding for reviewed VIR protocol `javascript.node-list.to-array`.

Copies a NodeList into a JavaScript Array without crossing its entries into Lean.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1`: receiver none; nodes js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "js.nodeList.toArray"]
opaque toArray
    {α : Type}
    (nodes : @& Lean.Vir.Js.NodeList (Lean.Vir.Js α)) :
    RuntimeM (Lean.Vir.Js.Array α)

end Js.NodeList

namespace Js.Nullable

/--
Generated binding for reviewed VIR protocol `javascript.nullable.null`.

Constructs a JavaScript null resource for a statically selected phantom type.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1`: receiver none; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "js.nullable.null"]
opaque null
    {α : Type} :
    RuntimeM (Lean.Vir.Js.Nullable α)

/--
Generated binding for reviewed VIR protocol `javascript.nullable.of`.

Injects a JavaScript resource into VIR's JavaScript nullable representation.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1`: receiver none; value js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "js.nullable.of"]
opaque ofJs
    {α : Type}
    (value : @& Lean.Vir.Js α) :
    RuntimeM (Lean.Vir.Js.Nullable α)

/--
Generated binding for reviewed VIR protocol `javascript.nullable.is-null`.

Tests a JavaScript nullable resource without decoding its payload.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1`: receiver none; value js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "js.nullable.isNull"]
opaque isNull
    {α : Type}
    (value : @& Lean.Vir.Js.Nullable α) :
    RuntimeM (Lean.Vir.Js Bool)

/--
Generated binding for reviewed VIR protocol `javascript.nullable.value`.

Extracts the non-null payload of a JavaScript nullable resource.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1`: receiver none; value js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "js.nullable.value"]
opaque get
    {α : Type}
    (value : @& Lean.Vir.Js.Nullable α) :
    RuntimeM (Lean.Vir.Js α)

end Js.Nullable

namespace Js.Object

/--
Generated binding for reviewed VIR protocol `javascript.object.empty`.

Constructs an ordinary empty JavaScript object without a VIR-specific props representation.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1`: receiver none; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "js.object.empty"]
opaque empty : RuntimeM (Lean.Vir.Js.Object)

/--
Generated binding for reviewed VIR protocol `javascript.object.set`.

Assigns the exact JavaScript value to the exact property name on an ordinary JavaScript object.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1`: receiver none; object js-resource/borrowed/call; name js-resource/borrowed/call; value js-resource/borrowed/call; result immediate/value.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "js.object.set"]
opaque set
    {α : Type}
    (object : @& Lean.Vir.Js.Object)
    (name : @& Lean.Vir.Js String)
    (value : @& Lean.Vir.Js α) :
    RuntimeM Unit

/--
Generated binding for reviewed VIR protocol `javascript.object.get`.

Reads an exact property value with an erased static shape, including undefined for missing properties. A dynamic field name provides no evidence for a caller-selected result type; typed reads require a declared field contract or an explicit narrow check.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1`: receiver none; object js-resource/borrowed/call; name js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "js.object.get"]
opaque get
    {object : Type}
    (object : @& Lean.Vir.Js object)
    (name : @& Lean.Vir.Js String) :
    RuntimeM (Lean.Vir.Js.Any)

end Js.Object

namespace Js.Promise

/--
Generated binding for reviewed VIR protocol `javascript.promise.then-value`.

Selects Promise.then<B>'s B callback-return alternative and returns the exact native chain. B is not constrained to exclude promises or thenables: native resolution recursively assimilates them. This selected TypeScript relationship does not compute Awaited<B> or prove runtime settlement shape.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1`: receiver none; promise js-resource/borrowed/call; onFulfilled js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "js.promise.thenValue"]
opaque thenValue
    {α : Type}
    {β : Type}
    (promise : @& Lean.Vir.Js.Promise α)
    (onFulfilled : @& Lean.Vir.Js.Function1 (Lean.Vir.Js α) (Lean.Vir.Js β)) :
    RuntimeM (Lean.Vir.Js.Promise β)

/--
Generated binding for reviewed VIR protocol `javascript.promise.then-promise`.

Selects Promise.then<B>'s PromiseLike<B> callback-return alternative with a native Promise<B>. Returns the exact native chain, with recursive thenable assimilation and no VIR scheduling or payload validation. This is a selected TypeScript relationship, not a computed Awaited type.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1`: receiver none; promise js-resource/borrowed/call; onFulfilled js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "js.promise.thenPromise"]
opaque thenPromise
    {α : Type}
    {β : Type}
    (promise : @& Lean.Vir.Js.Promise α)
    (onFulfilled : @& Lean.Vir.Js.Function1 (Lean.Vir.Js α) (Lean.Vir.Js.Promise β)) :
    RuntimeM (Lean.Vir.Js.Promise β)

/--
Generated binding for reviewed VIR protocol `javascript.promise.then-void`.

Calls native Promise.then with an exact JavaScript callback whose result is undefined and returns the exact chained Promise.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1`: receiver none; promise js-resource/borrowed/call; onFulfilled js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "js.promise.thenVoid"]
opaque thenVoid
    {α : Type}
    (promise : @& Lean.Vir.Js.Promise α)
    (onFulfilled : @& Lean.Vir.Js.Function1 (Lean.Vir.Js α) Unit) :
    RuntimeM (Lean.Vir.Js.Promise Lean.Vir.Js.Undefined.Value)

/--
Generated binding for reviewed VIR protocol `javascript.promise.then-value-with-rejection`.

Selects Promise.then<B, B> with both handlers returning the same B shape, so B | B remains B. Rejection input is Js.Any; B does not exclude thenables, which native resolution recursively assimilates. The rejection handler handles the input Promise's rejection, not exceptions thrown by the fulfillment handler. No full overload inference or settlement-shape proof is supplied.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1`: receiver none; promise js-resource/borrowed/call; onFulfilled js-resource/borrowed/call; onRejected js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "js.promise.thenValueWithRejection"]
opaque thenValueWithRejection
    {α : Type}
    {β : Type}
    (promise : @& Lean.Vir.Js.Promise α)
    (onFulfilled : @& Lean.Vir.Js.Function1 (Lean.Vir.Js α) (Lean.Vir.Js β))
    (onRejected : @& Lean.Vir.Js.Function1 Lean.Vir.Js.Any (Lean.Vir.Js β)) :
    RuntimeM (Lean.Vir.Js.Promise β)

/--
Generated binding for reviewed VIR protocol `javascript.promise.then-void-with-rejection`.

Calls native Promise.then with both exact handlers returning undefined and returns its exact chained Promise. The rejection handler handles the input Promise's rejection, not exceptions thrown by the fulfillment handler; no callback conversion or error swallowing is added.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1`: receiver none; promise js-resource/borrowed/call; onFulfilled js-resource/borrowed/call; onRejected js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "js.promise.thenVoidWithRejection"]
opaque thenVoidWithRejection
    {α : Type}
    (promise : @& Lean.Vir.Js.Promise α)
    (onFulfilled : @& Lean.Vir.Js.Function1 (Lean.Vir.Js α) Unit)
    (onRejected : @& Lean.Vir.Js.Function1 Lean.Vir.Js.Any Unit) :
    RuntimeM (Lean.Vir.Js.Promise Lean.Vir.Js.Undefined.Value)

/--
Generated binding for reviewed VIR protocol `javascript.promise.catch-value`.

Selects Promise<T>.catch<T> with a Js.Any rejection input and recovery to the same T, so T | T remains T. Returns the exact native chain. Rejection reasons are passed unchanged; returned promises and thenables are recursively assimilated. The generic result is a selected TypeScript relationship, not runtime payload validation.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1`: receiver none; promise js-resource/borrowed/call; onRejected js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "js.promise.catchValue"]
opaque catchValue
    {α : Type}
    (promise : @& Lean.Vir.Js.Promise α)
    (onRejected : @& Lean.Vir.Js.Function1 Lean.Vir.Js.Any (Lean.Vir.Js α)) :
    RuntimeM (Lean.Vir.Js.Promise α)

end Js.Promise

namespace Js.String

/--
Generated binding for reviewed VIR protocol `javascript.string.from-any`.

Checks for a primitive JavaScript string and returns that exact value. Throws TypeError for undefined, null, boxed strings and every other kind before typed use; never coerces or calls user conversion methods.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1`: receiver none; value js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "js.string.fromAny"]
opaque fromAny
    (value : @& Lean.Vir.Js.Any) :
    RuntimeM (Lean.Vir.Js String)

end Js.String

namespace Js.Tuple2

/--
Generated binding for reviewed VIR protocol `javascript.tuple2.first`.

Projects position 0 of an exact native two-element tuple, preserving the first position's type and value identity.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1`: receiver none; tuple js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "js.tuple2.first"]
opaque first
    {α : Type}
    {β : Type}
    (tuple : @& Lean.Vir.Js.Tuple2 (Lean.Vir.Js α) (Lean.Vir.Js β)) :
    RuntimeM (Lean.Vir.Js α)

/--
Generated binding for reviewed VIR protocol `javascript.tuple2.second`.

Projects position 1 of an exact native two-element tuple, preserving the second position's type and value identity.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1`: receiver none; tuple js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "js.tuple2.second"]
opaque second
    {α : Type}
    {β : Type}
    (tuple : @& Lean.Vir.Js.Tuple2 (Lean.Vir.Js α) (Lean.Vir.Js β)) :
    RuntimeM (Lean.Vir.Js β)

end Js.Tuple2

namespace Js.UndefinedOr

/--
Generated binding for reviewed VIR protocol `javascript.undefined`.

Returns the exact JavaScript undefined value, with no Option encoding or object wrapper.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1`: receiver none; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "js.undefined"]
opaque undefined
    {α : Type} :
    RuntimeM (Lean.Vir.Js.UndefinedOr α)

end Js.UndefinedOr

namespace JsValue

/--
Generated binding for reviewed VIR protocol `javascript.string.of`.

Explicitly converts a Lean-owned String into a JavaScript string resource.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1`: receiver none; value lean-owned/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js_explicit_conversion "js.string"]
opaque ofString
    (value : @& String) :
    RuntimeM (Js String)

/--
Generated binding for reviewed VIR protocol `javascript.string.value`.

Explicitly decodes a JavaScript string resource into a Lean-owned String.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1`: receiver none; value js-resource/borrowed/call; result lean-owned/value.

This declaration is generated; edit the binding configuration.
-/
@[vir_js_explicit_conversion "js.string.value"]
opaque toString
    (value : @& Js String) :
    RuntimeM (String)

/--
Generated binding for reviewed VIR protocol `javascript.nat.of`.

Explicitly converts a Lean Nat into a nonnegative JavaScript bigint resource, preserving arbitrary precision. This is not a JavaScript number or a JSON wire number.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1`: receiver none; value immediate/value/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js_explicit_conversion "js.nat"]
opaque ofNat
    (value : Nat) :
    RuntimeM (Js Nat)

/--
Generated binding for reviewed VIR protocol `javascript.nat.value`.

Explicitly decodes a nonnegative JavaScript bigint resource as a Lean Nat, preserving arbitrary precision. Rejects JavaScript number values and negative bigints.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1`: receiver none; value js-resource/borrowed/call; result immediate/value.

This declaration is generated; edit the binding configuration.
-/
@[vir_js_explicit_conversion "js.nat.value"]
opaque toNat
    (value : @& Js Nat) :
    RuntimeM (Nat)

/--
Generated binding for reviewed VIR protocol `javascript.bool.of`.

Explicitly converts a Lean Bool into a JavaScript boolean resource.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1`: receiver none; value immediate/value/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js_explicit_conversion "js.bool"]
opaque ofBool
    (value : Bool) :
    RuntimeM (Js Bool)

/--
Generated binding for reviewed VIR protocol `javascript.bool.value`.

Explicitly decodes a JavaScript boolean resource as a Lean Bool.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1`: receiver none; value js-resource/borrowed/call; result immediate/value.

This declaration is generated; edit the binding configuration.
-/
@[vir_js_explicit_conversion "js.bool.value"]
opaque toBool
    (value : @& Js Bool) :
    RuntimeM (Bool)

/--
Generated binding for reviewed VIR protocol `javascript.float.of`.

Explicitly preserves a Lean Float as a JavaScript IEEE-754 number resource.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1`: receiver none; value immediate/value/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js_explicit_conversion "js.float"]
opaque ofFloat
    (value : Float) :
    RuntimeM (Js Float)

/--
Generated binding for reviewed VIR protocol `javascript.float.value`.

Explicitly decodes a JavaScript IEEE-754 number resource as a Lean Float.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1`: receiver none; value js-resource/borrowed/call; result immediate/value.

This declaration is generated; edit the binding configuration.
-/
@[vir_js_explicit_conversion "js.float.value"]
opaque toFloat
    (value : @& Js Float) :
    RuntimeM (Float)

end JsValue

namespace LeanRef

/--
Generated binding for reviewed VIR protocol `javascript.lean-ref.create`.

Creates an ordinary self-owning JavaScript object that retains the Lean-owned value until JavaScript collection or runtime teardown.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1`: receiver none; value lean-owned/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "js.leanRef"]
opaque toJSL
    {α : Type}
    (value : @& α) :
    RuntimeM (JSL α)

/--
Generated binding for reviewed VIR protocol `javascript.lean-ref.value`.

Returns a fresh owned Lean reference from a live self-owning JavaScript object.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1`: receiver none; value js-resource/borrowed/call; result lean-owned/value.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "js.leanRef.value"]
opaque fromJSL
    {α : Type}
    (value : @& JSL α) :
    RuntimeM (α)

end LeanRef

end Lean.Vir
