/-
Copyright (c) 2026 Lean FRO LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Author: Emilio J. Gallego Arias
-/

-- Generated by scripts/bindings/generate-lean-bindings.mjs. Do not edit.

module

public import Vir.Js.Types

public section

namespace Lean.Vir

namespace Js.Array

/--
Generated binding for reviewed VIR protocol `javascript.array.empty`.

Constructs an empty native JavaScript Array.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1` (bridge-handle retention): receiver none; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "js.array.empty"]
opaque empty
    {α : Type} :
    RuntimeM (Lean.Vir.Js.Array α)

/--
Generated binding for reviewed VIR protocol `javascript.array.push`.

Selects the one-item arity of Array<T>.push(...items: T[]): number. The receiver and item share T; no erasure or conversion occurs.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1` (bridge-handle retention): receiver none; array js-resource/borrowed/call; value js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "js.array.push"]
opaque push
    {α : Type}
    (array : @& Lean.Vir.Js.Array α)
    (value : @& Lean.Vir.Js α) :
    RuntimeM (Lean.Vir.Js Float)

/--
Generated binding for reviewed VIR protocol `javascript.array.map`.

Selects Array<T>.map<U>'s exact three-argument callback with no thisArg. The declared Js.Function3 receives the element, native number index and original native source array. The provider calls array.map(callback) directly: holes, species construction, the initial iteration bound, mutations during iteration, callback errors and result identity remain native. This does not expose the optional thisArg signature.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1` (bridge-handle retention): receiver none; array js-resource/borrowed/call; callback js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "js.array.map"]
opaque map
    {α : Type}
    {β : Type}
    (array : @& Lean.Vir.Js.Array α)
    (callback : @& Lean.Vir.Js.Function3 (Lean.Vir.Js α) (Lean.Vir.Js Float) (Lean.Vir.Js.Array α) (Lean.Vir.Js β)) :
    RuntimeM (Lean.Vir.Js.Array β)

/--
Generated binding for reviewed VIR protocol `javascript.array.filter`.

Selects Array<T>.filter's ordinary predicate overload with no thisArg and no type-guard narrowing. The three-argument callback receives the native element, number index and original native source array; its generic native result uses JavaScript truthiness. The provider calls array.filter(callback) directly, preserving holes, species construction, the initial iteration bound, mutations, short-circuiting and callback errors.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1` (bridge-handle retention): receiver none; array js-resource/borrowed/call; callback js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "js.array.filter"]
opaque filter
    {α : Type}
    {β : Type}
    (array : @& Lean.Vir.Js.Array α)
    (callback : @& Lean.Vir.Js.Function3 (Lean.Vir.Js α) (Lean.Vir.Js Float) (Lean.Vir.Js.Array α) (Lean.Vir.Js β)) :
    RuntimeM (Lean.Vir.Js.Array α)

/--
Generated binding for reviewed VIR protocol `javascript.array.find`.

Selects Array<T>.find's ordinary predicate overload with no thisArg and no type-guard narrowing. The three-argument callback receives the native value, number index and original native source array; its generic native result uses JavaScript truthiness. The provider calls array.find(callback) directly, preserving native hole visits, the initial iteration bound, mutations, short-circuiting and callback errors.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1` (bridge-handle retention): receiver none; array js-resource/borrowed/call; callback js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "js.array.find"]
opaque find
    {α : Type}
    {β : Type}
    (array : @& Lean.Vir.Js.Array α)
    (callback : @& Lean.Vir.Js.Function3 (Lean.Vir.Js α) (Lean.Vir.Js Float) (Lean.Vir.Js.Array α) (Lean.Vir.Js β)) :
    RuntimeM (Lean.Vir.Js.UndefinedOr α)

/--
Generated binding for reviewed VIR protocol `javascript.array.some`.

Selects Array<T>.some's ordinary three-argument predicate with no thisArg. Its generic native result uses JavaScript truthiness, rather than restricting the callback to Bool; native short-circuiting, holes, mutations and callback errors are preserved by array.some(callback).

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1` (bridge-handle retention): receiver none; array js-resource/borrowed/call; callback js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "js.array.some"]
opaque some
    {α : Type}
    {β : Type}
    (array : @& Lean.Vir.Js.Array α)
    (callback : @& Lean.Vir.Js.Function3 (Lean.Vir.Js α) (Lean.Vir.Js Float) (Lean.Vir.Js.Array α) (Lean.Vir.Js β)) :
    RuntimeM (Lean.Vir.Js Bool)

/--
Generated binding for reviewed VIR protocol `javascript.array.every`.

Selects Array<T>.every's ordinary predicate overload with no thisArg and no type-guard narrowing. Its generic native result uses JavaScript truthiness, rather than restricting the callback to Bool; native short-circuiting, holes, mutations and callback errors are preserved by array.every(callback).

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1` (bridge-handle retention): receiver none; array js-resource/borrowed/call; callback js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "js.array.every"]
opaque every
    {α : Type}
    {β : Type}
    (array : @& Lean.Vir.Js.Array α)
    (callback : @& Lean.Vir.Js.Function3 (Lean.Vir.Js α) (Lean.Vir.Js Float) (Lean.Vir.Js.Array α) (Lean.Vir.Js β)) :
    RuntimeM (Lean.Vir.Js Bool)

/--
Generated binding for reviewed VIR protocol `javascript.array.for-each`.

Selects Array<T>.forEach's exact three-argument void callback with no thisArg. The provider calls array.forEach(callback) directly, preserving holes, the initial iteration bound, mutations and callback errors.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1` (bridge-handle retention): receiver none; array js-resource/borrowed/call; callback js-resource/borrowed/call; result immediate/value.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "js.array.forEach"]
opaque forEach
    {α : Type}
    (array : @& Lean.Vir.Js.Array α)
    (callback : @& Lean.Vir.Js.Function3 (Lean.Vir.Js α) (Lean.Vir.Js Float) (Lean.Vir.Js.Array α) Unit) :
    RuntimeM Unit

/--
Generated binding for reviewed VIR protocol `javascript.array.join`.

Selects Array<T>.join's optional separator as an explicit JavaScript UndefinedOr String. The provider calls array.join(separator) directly, preserving native coercion of values, null, undefined and holes without a Lean-side conversion.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1` (bridge-handle retention): receiver none; array js-resource/borrowed/call; separator js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "js.array.join"]
opaque join
    {α : Type}
    (array : @& Lean.Vir.Js.Array α)
    (separator : @& Lean.Vir.Js.UndefinedOr String) :
    RuntimeM (Lean.Vir.Js String)

/--
Generated binding for reviewed VIR protocol `javascript.array.length`.

Returns the exact native JavaScript Number stored in Array.length.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1` (bridge-handle retention): receiver none; array js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "js.array.length"]
opaque length
    {α : Type}
    (array : @& Lean.Vir.Js.Array α) :
    RuntimeM (Lean.Vir.Js Float)

/--
Generated binding for reviewed VIR protocol `javascript.array.item`.

Preserves Array<T>'s [n: number]: T relationship. This is the TypeScript unchecked-index lane: native holes and missing entries remain undefined, without a bounds check or null conversion. It does not implement noUncheckedIndexedAccess.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1` (bridge-handle retention): receiver none; array js-resource/borrowed/call; index js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "js.array.item"]
opaque get
    {α : Type}
    (array : @& Lean.Vir.Js.Array α)
    (index : @& Lean.Vir.Js Float) :
    RuntimeM (Lean.Vir.Js α)

end Js.Array

namespace Js.Boolean

/--
Generated binding for reviewed VIR protocol `javascript.boolean.not`.

VIR-owned native JavaScript ! operator for boolean resources, without a Lean Bool conversion.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1` (bridge-handle retention): receiver none; value js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "js.boolean.not"]
opaque not
    (value : @& Js Bool) :
    RuntimeM (Js Bool)

/--
Generated binding for reviewed VIR protocol `javascript.boolean.equal`.

VIR-owned native JavaScript boolean strict-equality operator, without a Lean Bool conversion or eager logical operation.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1` (bridge-handle retention): receiver none; left js-resource/borrowed/call; right js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "js.boolean.equal"]
opaque equal
    (left : @& Js Bool)
    (right : @& Js Bool) :
    RuntimeM (Js Bool)

end Js.Boolean

namespace Js.Construction

/--
Generated binding for reviewed VIR protocol `javascript.construction.field`.

Compiler lowering for native object/JSX literals: CreateDataPropertyOrThrow semantics, defining an own writable enumerable configurable property without invoking inherited setters. Not ordinary assignment or the full Object.defineProperty API.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1` (bridge-handle retention): receiver none; object js-resource/borrowed/call; name js-resource/borrowed/call; value js-resource/borrowed/call; result immediate/value.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "js.construction.field"]
opaque field
    {α : Type}
    (object : @& Lean.Vir.Js.Object)
    (name : @& Lean.Vir.Js String)
    (value : @& Lean.Vir.Js α) :
    RuntimeM Unit

/--
Generated binding for reviewed VIR protocol `javascript.construction.element`.

Compiler lowering for dense native array/JSX child-argument literals: defines the next own data property at array.length without calling push or inherited setters. The element shape remains correlated with the array shape. Not the general Array.push API.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1` (bridge-handle retention): receiver none; array js-resource/borrowed/call; value js-resource/borrowed/call; result immediate/value.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "js.construction.element"]
opaque element
    {α : Type}
    (array : @& Lean.Vir.Js.Array α)
    (value : @& Lean.Vir.Js α) :
    RuntimeM Unit

end Js.Construction

namespace Js.Function

/--
Generated binding for reviewed VIR protocol `javascript.function.of-lean-nullary`.

Converts a Lean action to an exact zero-argument JavaScript function returning its native result.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1` (bridge-handle retention): receiver none; callback callback/owned/until-release; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js_explicit_conversion "js.value.function.nullary"]
opaque ofLean0
    {α : Type}
    (callback : RuntimeM (Lean.Vir.Js α)) :
    RuntimeM (Lean.Vir.Js.Function0 (Lean.Vir.Js α))

/--
Generated binding for reviewed VIR protocol `javascript.function.of-lean-nullaryVoid`.

Converts a Lean action to an exact zero-argument JavaScript function returning undefined.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1` (bridge-handle retention): receiver none; callback callback/owned/until-release; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js_explicit_conversion "js.value.function.nullaryVoid"]
opaque ofLean0Void
    (callback : RuntimeM Unit) :
    RuntimeM (Lean.Vir.Js.Function0 Unit)

/--
Generated binding for reviewed VIR protocol `javascript.function.of-lean-binary`.

Converts a Lean binary callback to an exact JavaScript function with the same argument and result shapes.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1` (bridge-handle retention): receiver none; callback callback/owned/until-release; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js_explicit_conversion "js.value.function.binary"]
opaque ofLean2
    {α : Type}
    {β : Type}
    {γ : Type}
    (callback : Lean.Vir.Js α → Lean.Vir.Js β → RuntimeM (Lean.Vir.Js γ)) :
    RuntimeM (Lean.Vir.Js.Function2 (Lean.Vir.Js α) (Lean.Vir.Js β) (Lean.Vir.Js γ))

/--
Generated binding for reviewed VIR protocol `javascript.function.of-lean-unary`.

Explicitly converts a transferred Lean unary callback into an ordinary JavaScript function with the same call shape.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1` (bridge-handle retention): receiver none; callback callback/owned/until-release; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js_explicit_conversion "js.value.function.unary"]
opaque ofLean
    {α : Type}
    {β : Type}
    (callback : Lean.Vir.Js α → RuntimeM (Lean.Vir.Js β)) :
    RuntimeM (Lean.Vir.Js.Function1 (Lean.Vir.Js α) (Lean.Vir.Js β))

/--
Generated binding for reviewed VIR protocol `javascript.function.of-lean-ternary`.

Explicitly converts a transferred Lean ternary callback into an ordinary JavaScript function with the same three-argument and result call shape.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1` (bridge-handle retention): receiver none; callback callback/owned/until-release; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js_explicit_conversion "js.value.function.ternary"]
opaque ofLean3
    {α : Type}
    {β : Type}
    {γ : Type}
    {δ : Type}
    (callback : Lean.Vir.Js α → Lean.Vir.Js β → Lean.Vir.Js γ → RuntimeM (Lean.Vir.Js δ)) :
    RuntimeM (Lean.Vir.Js.Function3 (Lean.Vir.Js α) (Lean.Vir.Js β) (Lean.Vir.Js γ) (Lean.Vir.Js δ))

/--
Generated binding for reviewed VIR protocol `javascript.function.of-lean-binary-void`.

Explicitly converts a transferred Lean binary callback with a discarded result into an ordinary JavaScript function.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1` (bridge-handle retention): receiver none; callback callback/owned/until-release; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js_explicit_conversion "js.value.function.binaryVoid"]
opaque ofLean2Void
    {α : Type}
    {β : Type}
    (callback : Lean.Vir.Js α → Lean.Vir.Js β → RuntimeM Unit) :
    RuntimeM (Lean.Vir.Js.Function2 (Lean.Vir.Js α) (Lean.Vir.Js β) Unit)

/--
Generated binding for reviewed VIR protocol `javascript.function.of-lean-ternary-void`.

Explicitly converts a transferred Lean ternary callback with a discarded result into an ordinary JavaScript function.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1` (bridge-handle retention): receiver none; callback callback/owned/until-release; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js_explicit_conversion "js.value.function.ternaryVoid"]
opaque ofLean3Void
    {α : Type}
    {β : Type}
    {γ : Type}
    (callback : Lean.Vir.Js α → Lean.Vir.Js β → Lean.Vir.Js γ → RuntimeM Unit) :
    RuntimeM (Lean.Vir.Js.Function3 (Lean.Vir.Js α) (Lean.Vir.Js β) (Lean.Vir.Js γ) Unit)

/--
Generated binding for reviewed VIR protocol `javascript.function.of-lean-unary-void`.

Explicitly converts a transferred Lean unary callback with a discarded result into an ordinary JavaScript function.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1` (bridge-handle retention): receiver none; callback callback/owned/until-release; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js_explicit_conversion "js.value.function.unaryVoid"]
opaque ofLeanVoid
    {α : Type}
    (callback : Lean.Vir.Js α → RuntimeM Unit) :
    RuntimeM (Lean.Vir.Js.Function1 (Lean.Vir.Js α) Unit)

/--
Generated binding for reviewed VIR protocol `javascript.function.call`.

Calls an exact unary JavaScript function with one exact JavaScript argument and returns its exact JavaScript result.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1` (bridge-handle retention): receiver none; function js-resource/borrowed/call; argument js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "js.function.call"]
opaque call
    {α : Type}
    {β : Type}
    (function : @& Lean.Vir.Js.Function1 (Lean.Vir.Js α) (Lean.Vir.Js β))
    (argument : @& Lean.Vir.Js α) :
    RuntimeM (Lean.Vir.Js β)

/--
Generated binding for reviewed VIR protocol `javascript.function.call-void`.

Calls the exact JavaScript function with one exact JavaScript argument and discards its void result.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1` (bridge-handle retention): receiver none; function js-resource/borrowed/call; argument js-resource/borrowed/call; result immediate/value.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "js.function.callVoid"]
opaque callVoid
    {α : Type}
    (function : @& Lean.Vir.Js.Function1 (Lean.Vir.Js α) Unit)
    (argument : @& Lean.Vir.Js α) :
    RuntimeM Unit

/--
Generated binding for reviewed VIR protocol `javascript.function.call0`.

Calls the exact JavaScript function with 0 exact arguments and returns its exact JavaScript result; this is a plain call without a receiver.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1` (bridge-handle retention): receiver none; function js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "js.function.call0"]
opaque call0
    {α : Type}
    (function : @& Lean.Vir.Js.Function0 (Lean.Vir.Js α)) :
    RuntimeM (Lean.Vir.Js α)

/--
Generated binding for reviewed VIR protocol `javascript.function.call0-void`.

Calls the exact JavaScript function with 0 exact arguments and discards its void return; this is a plain call without a receiver.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1` (bridge-handle retention): receiver none; function js-resource/borrowed/call; result immediate/value.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "js.function.call0Void"]
opaque call0Void
    (function : @& Lean.Vir.Js.Function0 Unit) :
    RuntimeM Unit

/--
Generated binding for reviewed VIR protocol `javascript.function.call2-void`.

Calls the exact JavaScript function with 2 exact arguments and discards its void return; this is a plain call without a receiver.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1` (bridge-handle retention): receiver none; function js-resource/borrowed/call; argument1 js-resource/borrowed/call; argument2 js-resource/borrowed/call; result immediate/value.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "js.function.call2Void"]
opaque call2Void
    {α : Type}
    {β : Type}
    (function : @& Lean.Vir.Js.Function2 (Lean.Vir.Js α) (Lean.Vir.Js β) Unit)
    (argument1 : @& Lean.Vir.Js α)
    (argument2 : @& Lean.Vir.Js β) :
    RuntimeM Unit

end Js.Function

namespace Js.Function.Internal

/--
Generated binding for reviewed VIR protocol `javascript.function.call2`.

Calls the exact JavaScript function with 2 exact arguments and returns its exact JavaScript result; this is a plain call without a receiver. Internal monomorphic import keeps erased Lean type parameters out of the fixed-arity host ABI; the public inline declaration preserves the call's argument/result relationships.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1` (bridge-handle retention): receiver none; function js-resource/borrowed/call; argument1 js-resource/borrowed/call; argument2 js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "js.function.call2"]
opaque call2
    (function : @& Lean.Vir.Js.Function2 Lean.Vir.Js.Any Lean.Vir.Js.Any Lean.Vir.Js.Any)
    (argument1 : @& Lean.Vir.Js.Any)
    (argument2 : @& Lean.Vir.Js.Any) :
    RuntimeM (Lean.Vir.Js.Any)

/--
Generated binding for reviewed VIR protocol `javascript.function.call3`.

Calls the exact JavaScript function with 3 exact arguments and returns its exact JavaScript result; this is a plain call without a receiver. Internal monomorphic import keeps erased Lean type parameters out of the fixed-arity host ABI; the public inline declaration preserves the call's argument/result relationships.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1` (bridge-handle retention): receiver none; function js-resource/borrowed/call; argument1 js-resource/borrowed/call; argument2 js-resource/borrowed/call; argument3 js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "js.function.call3"]
opaque call3
    (function : @& Lean.Vir.Js.Function3 Lean.Vir.Js.Any Lean.Vir.Js.Any Lean.Vir.Js.Any Lean.Vir.Js.Any)
    (argument1 : @& Lean.Vir.Js.Any)
    (argument2 : @& Lean.Vir.Js.Any)
    (argument3 : @& Lean.Vir.Js.Any) :
    RuntimeM (Lean.Vir.Js.Any)

/--
Generated binding for reviewed VIR protocol `javascript.function.call3-void`.

Calls the exact JavaScript function with 3 exact arguments and discards its void return; this is a plain call without a receiver. Internal monomorphic import keeps erased Lean type parameters out of the fixed-arity host ABI; the public inline declaration preserves the call's argument/result relationships.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1` (bridge-handle retention): receiver none; function js-resource/borrowed/call; argument1 js-resource/borrowed/call; argument2 js-resource/borrowed/call; argument3 js-resource/borrowed/call; result immediate/value.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "js.function.call3Void"]
opaque call3Void
    (function : @& Lean.Vir.Js.Function3 Lean.Vir.Js.Any Lean.Vir.Js.Any Lean.Vir.Js.Any Unit)
    (argument1 : @& Lean.Vir.Js.Any)
    (argument2 : @& Lean.Vir.Js.Any)
    (argument3 : @& Lean.Vir.Js.Any) :
    RuntimeM Unit

end Js.Function.Internal

namespace Js.Nat

/--
Generated binding for reviewed VIR protocol `javascript.nat.to-string`.

Calls the native numeric toString method with an explicit value-or-undefined radix; formatting, range errors and radix conversion remain native.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1` (bridge-handle retention): receiver none; value js-resource/borrowed/call; radix js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "js.nat.toString"]
opaque toString
    (value : @& Lean.Vir.Js Nat)
    (radix : @& Lean.Vir.Js.UndefinedOr Float) :
    RuntimeM (Lean.Vir.Js String)

/--
Generated binding for reviewed VIR protocol `javascript.nat.add`.

VIR-owned native JavaScript bigint + operator for nonnegative bigint resources. TypeScript does not declare operators; addition closes the Nat subset without decoding, coercion, or checks.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1` (bridge-handle retention): receiver none; left js-resource/borrowed/call; right js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "js.nat.add"]
opaque add
    (left : @& Js Nat)
    (right : @& Js Nat) :
    RuntimeM (Js Nat)

/--
Generated binding for reviewed VIR protocol `javascript.nat.mul`.

VIR-owned native JavaScript bigint * operator for the nonnegative bigint Nat subset, without decoding, coercion, or checks.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1` (bridge-handle retention): receiver none; left js-resource/borrowed/call; right js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "js.nat.mul"]
opaque mul
    (left : @& Js Nat)
    (right : @& Js Nat) :
    RuntimeM (Js Nat)

/--
Generated binding for reviewed VIR protocol `javascript.nat.equal`.

VIR-owned native JavaScript bigint strict-equality operator for the nonnegative bigint Nat subset, without coercion.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1` (bridge-handle retention): receiver none; left js-resource/borrowed/call; right js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "js.nat.equal"]
opaque equal
    (left : @& Js Nat)
    (right : @& Js Nat) :
    RuntimeM (Js Bool)

/--
Generated binding for reviewed VIR protocol `javascript.nat.lt`.

VIR-owned native JavaScript bigint < operator for the nonnegative bigint Nat subset, without coercion.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1` (bridge-handle retention): receiver none; left js-resource/borrowed/call; right js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "js.nat.lt"]
opaque lt
    (left : @& Js Nat)
    (right : @& Js Nat) :
    RuntimeM (Js Bool)

/--
Generated binding for reviewed VIR protocol `javascript.nat.le`.

VIR-owned native JavaScript bigint <= operator for the nonnegative bigint Nat subset, without coercion.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1` (bridge-handle retention): receiver none; left js-resource/borrowed/call; right js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "js.nat.le"]
opaque le
    (left : @& Js Nat)
    (right : @& Js Nat) :
    RuntimeM (Js Bool)

end Js.Nat

namespace Js.NodeList

/--
Generated binding for reviewed VIR protocol `javascript.node-list.length`.

Returns the exact native JavaScript Number stored in NodeList.length.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1` (bridge-handle retention): receiver none; nodes js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "js.nodeList.length"]
opaque length
    {α : Type}
    (nodes : @& Lean.Vir.Js.NodeList α) :
    RuntimeM (Lean.Vir.Js Float)

/--
Generated binding for reviewed VIR protocol `javascript.node-list.item`.

Calls NodeList.item and represents a missing entry as JavaScript null.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1` (bridge-handle retention): receiver none; nodes js-resource/borrowed/call; index js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "js.nodeList.item"]
opaque item
    {α : Type}
    (nodes : @& Lean.Vir.Js.NodeList (Lean.Vir.Js α))
    (index : @& Lean.Vir.Js Float) :
    RuntimeM (Lean.Vir.Js.Nullable α)

/--
Generated binding for reviewed VIR protocol `javascript.node-list.to-array`.

Copies a NodeList into a JavaScript Array without crossing its entries into Lean.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1` (bridge-handle retention): receiver none; nodes js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "js.nodeList.toArray"]
opaque toArray
    {α : Type}
    (nodes : @& Lean.Vir.Js.NodeList (Lean.Vir.Js α)) :
    RuntimeM (Lean.Vir.Js.Array α)

end Js.NodeList

namespace Js.Nullable

/--
Generated binding for reviewed VIR protocol `javascript.nullable.null`.

Constructs a JavaScript null resource for a statically selected phantom type.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1` (bridge-handle retention): receiver none; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "js.nullable.null"]
opaque null
    {α : Type} :
    RuntimeM (Lean.Vir.Js.Nullable α)

/--
Generated binding for reviewed VIR protocol `javascript.nullable.of`.

Injects a JavaScript resource into VIR's JavaScript nullable representation.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1` (bridge-handle retention): receiver none; value js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "js.nullable.of"]
opaque ofJs
    {α : Type}
    (value : @& Lean.Vir.Js α) :
    RuntimeM (Lean.Vir.Js.Nullable α)

/--
Generated binding for reviewed VIR protocol `javascript.nullable.is-null`.

Tests a JavaScript nullable resource without decoding its payload.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1` (bridge-handle retention): receiver none; value js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "js.nullable.isNull"]
opaque isNull
    {α : Type}
    (value : @& Lean.Vir.Js.Nullable α) :
    RuntimeM (Lean.Vir.Js Bool)

/--
Generated binding for reviewed VIR protocol `javascript.nullable.value`.

Extracts the non-null payload of a JavaScript nullable resource.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1` (bridge-handle retention): receiver none; value js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "js.nullable.value"]
opaque get
    {α : Type}
    (value : @& Lean.Vir.Js.Nullable α) :
    RuntimeM (Lean.Vir.Js α)

end Js.Nullable

namespace Js.Number

/--
Generated binding for reviewed VIR protocol `javascript.number.to-string`.

Calls the native numeric toString method with an explicit value-or-undefined radix; formatting, range errors and radix conversion remain native.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1` (bridge-handle retention): receiver none; value js-resource/borrowed/call; radix js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "js.number.toString"]
opaque toString
    (value : @& Lean.Vir.Js Float)
    (radix : @& Lean.Vir.Js.UndefinedOr Float) :
    RuntimeM (Lean.Vir.Js String)

/--
Generated binding for reviewed VIR protocol `javascript.number.add`.

VIR-owned native JavaScript number + operator, with native IEEE-754 semantics and no coercion.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1` (bridge-handle retention): receiver none; left js-resource/borrowed/call; right js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "js.number.add"]
opaque add
    (left : @& Js Float)
    (right : @& Js Float) :
    RuntimeM (Js Float)

/--
Generated binding for reviewed VIR protocol `javascript.number.sub`.

VIR-owned native JavaScript number - operator, with native IEEE-754 semantics and no coercion.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1` (bridge-handle retention): receiver none; left js-resource/borrowed/call; right js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "js.number.sub"]
opaque sub
    (left : @& Js Float)
    (right : @& Js Float) :
    RuntimeM (Js Float)

/--
Generated binding for reviewed VIR protocol `javascript.number.mul`.

VIR-owned native JavaScript number * operator, with native IEEE-754 semantics and no coercion.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1` (bridge-handle retention): receiver none; left js-resource/borrowed/call; right js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "js.number.mul"]
opaque mul
    (left : @& Js Float)
    (right : @& Js Float) :
    RuntimeM (Js Float)

/--
Generated binding for reviewed VIR protocol `javascript.number.div`.

VIR-owned native JavaScript number / operator, including native zero-divisor behavior, without coercion.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1` (bridge-handle retention): receiver none; left js-resource/borrowed/call; right js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "js.number.div"]
opaque div
    (left : @& Js Float)
    (right : @& Js Float) :
    RuntimeM (Js Float)

/--
Generated binding for reviewed VIR protocol `javascript.number.rem`.

VIR-owned native JavaScript number % operator, with native IEEE-754 semantics and no coercion.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1` (bridge-handle retention): receiver none; left js-resource/borrowed/call; right js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "js.number.rem"]
opaque rem
    (left : @& Js Float)
    (right : @& Js Float) :
    RuntimeM (Js Float)

/--
Generated binding for reviewed VIR protocol `javascript.number.neg`.

VIR-owned native JavaScript unary - operator, preserving native IEEE-754 signed-zero and NaN behavior.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1` (bridge-handle retention): receiver none; value js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "js.number.neg"]
opaque neg
    (value : @& Js Float) :
    RuntimeM (Js Float)

/--
Generated binding for reviewed VIR protocol `javascript.number.equal`.

VIR-owned native JavaScript number strict-equality operator, preserving NaN and signed-zero behavior without coercion.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1` (bridge-handle retention): receiver none; left js-resource/borrowed/call; right js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "js.number.equal"]
opaque equal
    (left : @& Js Float)
    (right : @& Js Float) :
    RuntimeM (Js Bool)

/--
Generated binding for reviewed VIR protocol `javascript.number.lt`.

VIR-owned native JavaScript number < operator, preserving NaN behavior without coercion.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1` (bridge-handle retention): receiver none; left js-resource/borrowed/call; right js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "js.number.lt"]
opaque lt
    (left : @& Js Float)
    (right : @& Js Float) :
    RuntimeM (Js Bool)

/--
Generated binding for reviewed VIR protocol `javascript.number.le`.

VIR-owned native JavaScript number <= operator, preserving NaN behavior without coercion.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1` (bridge-handle retention): receiver none; left js-resource/borrowed/call; right js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "js.number.le"]
opaque le
    (left : @& Js Float)
    (right : @& Js Float) :
    RuntimeM (Js Bool)

/--
Generated binding for reviewed VIR protocol `javascript.number.is-nan`.

Forwards Number.isNaN without coercion or conversion to a Lean Bool.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1` (bridge-handle retention): receiver none; value js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "js.number.isNaN"]
opaque isNaN
    (value : @& Js Float) :
    RuntimeM (Js Bool)

/--
Generated binding for reviewed VIR protocol `javascript.number.is-finite`.

Forwards Number.isFinite without coercion or conversion to a Lean Bool.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1` (bridge-handle retention): receiver none; value js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "js.number.isFinite"]
opaque isFinite
    (value : @& Js Float) :
    RuntimeM (Js Bool)

/--
Generated binding for reviewed VIR protocol `javascript.number.is-integer`.

Forwards Number.isInteger without coercion or conversion to a Lean Bool.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1` (bridge-handle retention): receiver none; value js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "js.number.isInteger"]
opaque isInteger
    (value : @& Js Float) :
    RuntimeM (Js Bool)

end Js.Number

namespace Js.Object

/--
Generated binding for reviewed VIR protocol `javascript.object.empty`.

Constructs an ordinary empty JavaScript object without a VIR-specific props representation.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1` (bridge-handle retention): receiver none; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "js.object.empty"]
opaque empty : RuntimeM (Lean.Vir.Js.Object)

/--
Generated binding for reviewed VIR protocol `javascript.object.set`.

Assigns the exact JavaScript value to the exact property name on an ordinary JavaScript object.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1` (bridge-handle retention): receiver none; object js-resource/borrowed/call; name js-resource/borrowed/call; value js-resource/borrowed/call; result immediate/value.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "js.object.set"]
opaque set
    {α : Type}
    (object : @& Lean.Vir.Js.Object)
    (name : @& Lean.Vir.Js String)
    (value : @& Lean.Vir.Js α) :
    RuntimeM Unit

/--
Generated binding for reviewed VIR protocol `javascript.object.get`.

Reads an exact property value with an erased static shape, including undefined for missing properties. A dynamic field name provides no evidence for a caller-selected result type; typed reads require a declared field contract or an explicit narrow check.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1` (bridge-handle retention): receiver none; object js-resource/borrowed/call; name js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "js.object.get"]
opaque get
    {object : Type}
    (object : @& Lean.Vir.Js object)
    (name : @& Lean.Vir.Js String) :
    RuntimeM (Lean.Vir.Js.Any)

end Js.Object

namespace Js.Promise

/--
Generated binding for reviewed VIR protocol `javascript.promise.then-value`.

Selects Promise.then<B>'s B callback-return alternative and returns the exact native chain. B is not constrained to exclude promises or thenables: native resolution recursively assimilates them. This selected TypeScript relationship does not compute Awaited<B> or prove runtime settlement shape.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1` (bridge-handle retention): receiver none; promise js-resource/borrowed/call; onFulfilled js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "js.promise.thenValue"]
opaque thenValue
    {α : Type}
    {β : Type}
    (promise : @& Lean.Vir.Js.Promise α)
    (onFulfilled : @& Lean.Vir.Js.Function1 (Lean.Vir.Js α) (Lean.Vir.Js β)) :
    RuntimeM (Lean.Vir.Js.Promise β)

/--
Generated binding for reviewed VIR protocol `javascript.promise.then-promise`.

Selects Promise.then<B>'s PromiseLike<B> callback-return alternative with a native Promise<B>. Returns the exact native chain, with recursive thenable assimilation and no VIR scheduling or payload validation. This is a selected TypeScript relationship, not a computed Awaited type.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1` (bridge-handle retention): receiver none; promise js-resource/borrowed/call; onFulfilled js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "js.promise.thenPromise"]
opaque thenPromise
    {α : Type}
    {β : Type}
    (promise : @& Lean.Vir.Js.Promise α)
    (onFulfilled : @& Lean.Vir.Js.Function1 (Lean.Vir.Js α) (Lean.Vir.Js.Promise β)) :
    RuntimeM (Lean.Vir.Js.Promise β)

/--
Generated binding for reviewed VIR protocol `javascript.promise.then-void`.

Calls native Promise.then with an exact JavaScript callback whose result is undefined and returns the exact chained Promise.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1` (bridge-handle retention): receiver none; promise js-resource/borrowed/call; onFulfilled js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "js.promise.thenVoid"]
opaque thenVoid
    {α : Type}
    (promise : @& Lean.Vir.Js.Promise α)
    (onFulfilled : @& Lean.Vir.Js.Function1 (Lean.Vir.Js α) Unit) :
    RuntimeM (Lean.Vir.Js.Promise Lean.Vir.Js.Undefined.Value)

/--
Generated binding for reviewed VIR protocol `javascript.promise.then-value-with-rejection`.

Selects Promise.then<B, B> with both handlers returning the same B shape, so B | B remains B. Rejection input is Js.Any; B does not exclude thenables, which native resolution recursively assimilates. The rejection handler handles the input Promise's rejection, not exceptions thrown by the fulfillment handler. No full overload inference or settlement-shape proof is supplied.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1` (bridge-handle retention): receiver none; promise js-resource/borrowed/call; onFulfilled js-resource/borrowed/call; onRejected js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "js.promise.thenValueWithRejection"]
opaque thenValueWithRejection
    {α : Type}
    {β : Type}
    (promise : @& Lean.Vir.Js.Promise α)
    (onFulfilled : @& Lean.Vir.Js.Function1 (Lean.Vir.Js α) (Lean.Vir.Js β))
    (onRejected : @& Lean.Vir.Js.Function1 Lean.Vir.Js.Any (Lean.Vir.Js β)) :
    RuntimeM (Lean.Vir.Js.Promise β)

/--
Generated binding for reviewed VIR protocol `javascript.promise.then-void-with-rejection`.

Calls native Promise.then with both exact handlers returning undefined and returns its exact chained Promise. The rejection handler handles the input Promise's rejection, not exceptions thrown by the fulfillment handler; no callback conversion or error swallowing is added.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1` (bridge-handle retention): receiver none; promise js-resource/borrowed/call; onFulfilled js-resource/borrowed/call; onRejected js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "js.promise.thenVoidWithRejection"]
opaque thenVoidWithRejection
    {α : Type}
    (promise : @& Lean.Vir.Js.Promise α)
    (onFulfilled : @& Lean.Vir.Js.Function1 (Lean.Vir.Js α) Unit)
    (onRejected : @& Lean.Vir.Js.Function1 Lean.Vir.Js.Any Unit) :
    RuntimeM (Lean.Vir.Js.Promise Lean.Vir.Js.Undefined.Value)

/--
Generated binding for reviewed VIR protocol `javascript.promise.catch-value`.

Selects Promise<T>.catch<T> with a Js.Any rejection input and recovery to the same T, so T | T remains T. Returns the exact native chain. Rejection reasons are passed unchanged; returned promises and thenables are recursively assimilated. The generic result is a selected TypeScript relationship, not runtime payload validation.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1` (bridge-handle retention): receiver none; promise js-resource/borrowed/call; onRejected js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "js.promise.catchValue"]
opaque catchValue
    {α : Type}
    (promise : @& Lean.Vir.Js.Promise α)
    (onRejected : @& Lean.Vir.Js.Function1 Lean.Vir.Js.Any (Lean.Vir.Js α)) :
    RuntimeM (Lean.Vir.Js.Promise α)

end Js.Promise

namespace Js.String

/--
Generated binding for reviewed VIR protocol `javascript.string.interpolate`.

VIR-owned untagged native template interpolation step: appends JavaScript ToString(value) to the native prefix, including native coercion order, Symbol rejection and exceptions. No Lean ToString is used.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1` (bridge-handle retention): receiver none; text js-resource/borrowed/call; value js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "js.string.interpolate"]
opaque interpolate
    {α : Type}
    (text : @& Lean.Vir.Js String)
    (value : @& Lean.Vir.Js α) :
    RuntimeM (Lean.Vir.Js String)

/--
Generated binding for reviewed VIR protocol `javascript.string.length`.

Reads native String.length as a JavaScript number of UTF-16 code units, without decoding the string or counting Unicode code points.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1` (bridge-handle retention): receiver none; value js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "js.string.length"]
opaque length
    (value : @& Lean.Vir.Js String) :
    RuntimeM (Lean.Vir.Js Float)

/--
Generated binding for reviewed VIR protocol `javascript.string.equal`.

VIR-owned native JavaScript strict-equality operator for string resources, preserving UTF-16 code-unit identity without decoding or coercion.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1` (bridge-handle retention): receiver none; left js-resource/borrowed/call; right js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "js.string.equal"]
opaque equal
    (left : @& Js String)
    (right : @& Js String) :
    RuntimeM (Js Bool)

/--
Generated binding for reviewed VIR protocol `javascript.string.concat`.

Forwards one JavaScript string argument to String.prototype.concat without decoding, coercion, or a variadic adapter.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1` (bridge-handle retention): receiver none; value js-resource/borrowed/call; suffix js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "js.string.concat"]
opaque concat
    (value : @& Js String)
    (suffix : @& Js String) :
    RuntimeM (Js String)

/--
Generated binding for reviewed VIR protocol `javascript.string.slice`.

Forwards String.prototype.slice's selected start and optional end arguments, preserving native UTF-16 indexing and JavaScript coercion.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1` (bridge-handle retention): receiver none; value js-resource/borrowed/call; start js-resource/borrowed/call; «end» js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "js.string.slice"]
opaque slice
    (value : @& Js String)
    (start : @& Js Float)
    («end» : @& Lean.Vir.Js.UndefinedOr Float) :
    RuntimeM (Js String)

/--
Generated binding for reviewed VIR protocol `javascript.string.includes`.

Forwards one search string to String.prototype.includes and leaves its position at the native default.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1` (bridge-handle retention): receiver none; value js-resource/borrowed/call; search js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "js.string.includes"]
opaque includes
    (value : @& Js String)
    (search : @& Js String) :
    RuntimeM (Js Bool)

/--
Generated binding for reviewed VIR protocol `javascript.string.starts-with`.

Forwards one search string to String.prototype.startsWith and leaves its position at the native default.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1` (bridge-handle retention): receiver none; value js-resource/borrowed/call; search js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "js.string.startsWith"]
opaque startsWith
    (value : @& Js String)
    (search : @& Js String) :
    RuntimeM (Js Bool)

/--
Generated binding for reviewed VIR protocol `javascript.string.ends-with`.

Forwards one search string to String.prototype.endsWith and leaves its position at the native default.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1` (bridge-handle retention): receiver none; value js-resource/borrowed/call; search js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "js.string.endsWith"]
opaque endsWith
    (value : @& Js String)
    (search : @& Js String) :
    RuntimeM (Js Bool)

/--
Generated binding for reviewed VIR protocol `javascript.string.trim`.

Forwards String.prototype.trim on the native receiver without decoding or replacement whitespace semantics.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1` (bridge-handle retention): receiver none; value js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "js.string.trim"]
opaque trim
    (value : @& Js String) :
    RuntimeM (Js String)

/--
Generated binding for reviewed VIR protocol `javascript.string.to-lower-case`.

Forwards String.prototype.toLowerCase on the native receiver without decoding or locale-specific replacement semantics.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1` (bridge-handle retention): receiver none; value js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "js.string.toLowerCase"]
opaque toLowerCase
    (value : @& Js String) :
    RuntimeM (Js String)

/--
Generated binding for reviewed VIR protocol `javascript.string.to-upper-case`.

Forwards String.prototype.toUpperCase on the native receiver without decoding or locale-specific replacement semantics.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1` (bridge-handle retention): receiver none; value js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "js.string.toUpperCase"]
opaque toUpperCase
    (value : @& Js String) :
    RuntimeM (Js String)

/--
Generated binding for reviewed VIR protocol `javascript.string.from-any`.

Checks for a primitive JavaScript string and returns that exact value. Throws TypeError for undefined, null, boxed strings and every other kind before typed use; never coerces or calls user conversion methods.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1` (bridge-handle retention): receiver none; value js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "js.string.fromAny"]
opaque fromAny
    (value : @& Lean.Vir.Js.Any) :
    RuntimeM (Lean.Vir.Js String)

end Js.String

namespace Js.Tuple2

/--
Generated binding for reviewed VIR protocol `javascript.tuple2.first`.

Projects position 0 of an exact native two-element tuple, preserving the first position's type and value identity.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1` (bridge-handle retention): receiver none; tuple js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "js.tuple2.first"]
opaque first
    {α : Type}
    {β : Type}
    (tuple : @& Lean.Vir.Js.Tuple2 α β) :
    RuntimeM (Lean.Vir.Js α)

/--
Generated binding for reviewed VIR protocol `javascript.tuple2.second`.

Projects position 1 of an exact native two-element tuple, preserving the second position's type and value identity.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1` (bridge-handle retention): receiver none; tuple js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "js.tuple2.second"]
opaque second
    {α : Type}
    {β : Type}
    (tuple : @& Lean.Vir.Js.Tuple2 α β) :
    RuntimeM (Lean.Vir.Js β)

end Js.Tuple2

namespace Js.UndefinedOr

/--
Generated binding for reviewed VIR protocol `javascript.undefined`.

Returns the exact JavaScript undefined value, with no Option encoding or object wrapper.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1` (bridge-handle retention): receiver none; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "js.undefined"]
opaque undefined
    {α : Type} :
    RuntimeM (Lean.Vir.Js.UndefinedOr α)

/--
Generated binding for reviewed VIR protocol `javascript.undefined-or.is-undefined`.

Tests for the exact JavaScript undefined value without decoding the payload or treating null as absent.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1` (bridge-handle retention): receiver none; value js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "js.undefinedOr.isUndefined"]
opaque isUndefined
    {α : Type}
    (value : @& Lean.Vir.Js.UndefinedOr α) :
    RuntimeM (Js Bool)

/--
Generated binding for reviewed VIR protocol `javascript.undefined-or.value`.

Returns the exact defined payload, throwing TypeError on undefined. Checks absence, not the caller-declared payload shape.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1` (bridge-handle retention): receiver none; value js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "js.undefinedOr.value"]
opaque get
    {α : Type}
    (value : @& Lean.Vir.Js.UndefinedOr α) :
    RuntimeM (Js α)

end Js.UndefinedOr

namespace JsValue

/--
Generated binding for reviewed VIR protocol `javascript.string.of`.

Explicitly converts a Lean-owned String into a JavaScript string resource.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1` (bridge-handle retention): receiver none; value lean-owned/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js_explicit_conversion "js.string"]
opaque ofString
    (value : @& String) :
    RuntimeM (Js String)

/--
Generated binding for reviewed VIR protocol `javascript.string.value`.

Explicitly decodes a JavaScript string resource into a Lean-owned String.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1` (bridge-handle retention): receiver none; value js-resource/borrowed/call; result lean-owned/value.

This declaration is generated; edit the binding configuration.
-/
@[vir_js_explicit_conversion "js.string.value"]
opaque toString
    (value : @& Js String) :
    RuntimeM (String)

/--
Generated binding for reviewed VIR protocol `javascript.nat.of`.

Explicitly converts a Lean Nat into a nonnegative JavaScript bigint resource, preserving arbitrary precision. This is not a JavaScript number or a JSON wire number.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1` (bridge-handle retention): receiver none; value immediate/value/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js_explicit_conversion "js.nat"]
opaque ofNat
    (value : Nat) :
    RuntimeM (Js Nat)

/--
Generated binding for reviewed VIR protocol `javascript.nat.value`.

Explicitly decodes a nonnegative JavaScript bigint resource as a Lean Nat, preserving arbitrary precision. Rejects JavaScript number values and negative bigints.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1` (bridge-handle retention): receiver none; value js-resource/borrowed/call; result immediate/value.

This declaration is generated; edit the binding configuration.
-/
@[vir_js_explicit_conversion "js.nat.value"]
opaque toNat
    (value : @& Js Nat) :
    RuntimeM (Nat)

/--
Generated binding for reviewed VIR protocol `javascript.bool.of`.

Explicitly converts a Lean Bool into a JavaScript boolean resource.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1` (bridge-handle retention): receiver none; value immediate/value/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js_explicit_conversion "js.bool"]
opaque ofBool
    (value : Bool) :
    RuntimeM (Js Bool)

/--
Generated binding for reviewed VIR protocol `javascript.bool.value`.

Explicitly decodes a JavaScript boolean resource as a Lean Bool.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1` (bridge-handle retention): receiver none; value js-resource/borrowed/call; result immediate/value.

This declaration is generated; edit the binding configuration.
-/
@[vir_js_explicit_conversion "js.bool.value"]
opaque toBool
    (value : @& Js Bool) :
    RuntimeM (Bool)

/--
Generated binding for reviewed VIR protocol `javascript.float.of`.

Explicitly preserves a Lean Float as a JavaScript IEEE-754 number resource.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1` (bridge-handle retention): receiver none; value immediate/value/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js_explicit_conversion "js.float"]
opaque ofFloat
    (value : Float) :
    RuntimeM (Js Float)

/--
Generated binding for reviewed VIR protocol `javascript.float.value`.

Explicitly decodes a JavaScript IEEE-754 number resource as a Lean Float.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1` (bridge-handle retention): receiver none; value js-resource/borrowed/call; result immediate/value.

This declaration is generated; edit the binding configuration.
-/
@[vir_js_explicit_conversion "js.float.value"]
opaque toFloat
    (value : @& Js Float) :
    RuntimeM (Float)

end JsValue

namespace LeanRef

/--
Generated binding for reviewed VIR protocol `javascript.lean-ref.create`.

Creates an ordinary self-owning JavaScript object that retains the Lean-owned value until JavaScript collection or runtime teardown.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1` (bridge-handle retention): receiver none; value lean-owned/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "js.leanRef"]
opaque toJSL
    {α : Type}
    (value : @& α) :
    RuntimeM (JSL α)

/--
Generated binding for reviewed VIR protocol `javascript.lean-ref.value`.

Returns a fresh owned Lean reference from a live self-owning JavaScript object.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1` (bridge-handle retention): receiver none; value js-resource/borrowed/call; result lean-owned/value.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "js.leanRef.value"]
opaque fromJSL
    {α : Type}
    (value : @& JSL α) :
    RuntimeM (α)

end LeanRef

end Lean.Vir
