/-
Copyright (c) 2026 Lean FRO LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Author: Emilio J. Gallego Arias
-/

-- Generated by scripts/bindings/generate-lean-bindings.mjs. Do not edit.

import Vir.Js.Types

namespace Lean.Vir

namespace Js.Array

/--
Generated binding for reviewed VIR protocol `javascript.array.length`.

Reads Array.length while keeping the array contents in JavaScript land.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1`: receiver none; array js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "js.array.length"]
opaque lengthJs
    {α : Type}
    (array : @& Lean.Vir.Js.Array α) :
    RuntimeM (Lean.Vir.Js Nat)

/--
Generated explicit protocol operation semantic adapter for TypeScript `Array`.

Adapter policy: Reads an Array entry as a nullable resource and normalizes JavaScript undefined to null, so this is an explicit safe-lookup adapter rather than raw bracket access.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1`: receiver none; array js-resource/borrowed/call; index js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "js.array.item"]
opaque itemNullable
    {α : Type}
    (array : @& Lean.Vir.Js.Array (Lean.Vir.Js α))
    (index : @& Lean.Vir.Js Nat) :
    RuntimeM (Lean.Vir.Js.Nullable α)

end Js.Array

namespace Js.NodeList

/--
Generated binding for reviewed VIR protocol `javascript.node-list.length`.

Reads NodeList.length while keeping the collection in JavaScript land.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1`: receiver none; nodes js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "js.nodeList.length"]
opaque lengthJs
    {α : Type}
    (nodes : @& Lean.Vir.Js.NodeList α) :
    RuntimeM (Lean.Vir.Js Nat)

/--
Generated binding for reviewed VIR protocol `javascript.node-list.item`.

Calls NodeList.item and represents a missing entry as JavaScript null.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1`: receiver none; nodes js-resource/borrowed/call; index js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "js.nodeList.item"]
opaque itemNullable
    {α : Type}
    (nodes : @& Lean.Vir.Js.NodeList (Lean.Vir.Js α))
    (index : @& Lean.Vir.Js Nat) :
    RuntimeM (Lean.Vir.Js.Nullable α)

/--
Generated binding for reviewed VIR protocol `javascript.node-list.to-array`.

Copies a NodeList into a JavaScript Array without crossing its entries into Lean.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1`: receiver none; nodes js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "js.nodeList.toArray"]
opaque toArray
    {α : Type}
    (nodes : @& Lean.Vir.Js.NodeList α) :
    RuntimeM (Lean.Vir.Js.Array α)

end Js.NodeList

namespace Js.Nullable

/--
Generated binding for reviewed VIR protocol `javascript.nullable.null`.

Constructs a JavaScript null resource for a statically selected phantom type.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1`: receiver none; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "js.nullable.null"]
opaque null
    {α : Type} :
    RuntimeM (Lean.Vir.Js.Nullable α)

/--
Generated binding for reviewed VIR protocol `javascript.nullable.of`.

Injects a JavaScript resource into VIR's JavaScript nullable representation.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1`: receiver none; value js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "js.nullable.of"]
opaque ofJs
    {α : Type}
    (value : @& Lean.Vir.Js α) :
    RuntimeM (Lean.Vir.Js.Nullable α)

/--
Generated binding for reviewed VIR protocol `javascript.nullable.is-null`.

Tests a JavaScript nullable resource without decoding its payload.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1`: receiver none; value js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "js.nullable.isNull"]
opaque isNullJs
    {α : Type}
    (value : @& Lean.Vir.Js.Nullable α) :
    RuntimeM (Lean.Vir.Js Bool)

/--
Generated binding for reviewed VIR protocol `javascript.nullable.value`.

Extracts the non-null payload of a JavaScript nullable resource.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1`: receiver none; value js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "js.nullable.value"]
opaque get
    {α : Type}
    (value : @& Lean.Vir.Js.Nullable α) :
    RuntimeM (Lean.Vir.Js α)

end Js.Nullable

namespace JsValue

/--
Generated binding for reviewed VIR protocol `javascript.string.of`.

Explicitly converts a Lean-owned String into a JavaScript string resource.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1`: receiver none; value lean-owned/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js_explicit_conversion "js.string"]
opaque ofString
    (value : @& String) :
    RuntimeM (Js String)

/--
Generated binding for reviewed VIR protocol `javascript.string.value`.

Explicitly decodes a JavaScript string resource into a Lean-owned String.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1`: receiver none; value js-resource/borrowed/call; result lean-owned/value.

This declaration is generated; edit the binding configuration.
-/
@[vir_js_explicit_conversion "js.string.value"]
opaque toString
    (value : @& Js String) :
    RuntimeM (String)

/--
Generated binding for reviewed VIR protocol `javascript.nat.of`.

Explicitly converts a Lean Nat into a JavaScript number resource.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1`: receiver none; value immediate/value/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js_explicit_conversion "js.nat"]
opaque ofNat
    (value : Nat) :
    RuntimeM (Js Nat)

/--
Generated binding for reviewed VIR protocol `javascript.nat.value`.

Explicitly decodes a JavaScript number resource as a Lean Nat.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1`: receiver none; value js-resource/borrowed/call; result immediate/value.

This declaration is generated; edit the binding configuration.
-/
@[vir_js_explicit_conversion "js.nat.value"]
opaque toNat
    (value : @& Js Nat) :
    RuntimeM (Nat)

/--
Generated binding for reviewed VIR protocol `javascript.bool.of`.

Explicitly converts a Lean Bool into a JavaScript boolean resource.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1`: receiver none; value immediate/value/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js_explicit_conversion "js.bool"]
opaque ofBool
    (value : Bool) :
    RuntimeM (Js Bool)

/--
Generated binding for reviewed VIR protocol `javascript.bool.value`.

Explicitly decodes a JavaScript boolean resource as a Lean Bool.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1`: receiver none; value js-resource/borrowed/call; result immediate/value.

This declaration is generated; edit the binding configuration.
-/
@[vir_js_explicit_conversion "js.bool.value"]
opaque toBool
    (value : @& Js Bool) :
    RuntimeM (Bool)

/--
Generated binding for reviewed VIR protocol `javascript.float.of`.

Explicitly preserves a Lean Float as a JavaScript IEEE-754 number resource.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1`: receiver none; value immediate/value/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js_explicit_conversion "js.float"]
opaque ofFloat
    (value : Float) :
    RuntimeM (Js Float)

/--
Generated binding for reviewed VIR protocol `javascript.float.value`.

Explicitly decodes a JavaScript IEEE-754 number resource as a Lean Float.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1`: receiver none; value js-resource/borrowed/call; result immediate/value.

This declaration is generated; edit the binding configuration.
-/
@[vir_js_explicit_conversion "js.float.value"]
opaque toFloat
    (value : @& Js Float) :
    RuntimeM (Float)

end JsValue

namespace LeanRef

/--
Generated binding for reviewed VIR protocol `javascript.lean-ref.create`.

Creates an ordinary self-owning JavaScript object that retains the Lean-owned value until JavaScript collection or runtime teardown.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1`: receiver none; value lean-owned/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "js.leanRef"]
opaque toJSL
    {α : Type}
    (value : @& α) :
    RuntimeM (JSL α)

/--
Generated binding for reviewed VIR protocol `javascript.lean-ref.value`.

Returns a fresh owned Lean reference from a live self-owning JavaScript object.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-javascript-protocol-v1`: receiver none; value js-resource/borrowed/call; result lean-owned/value.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "js.leanRef.value"]
opaque fromJSL
    {α : Type}
    (value : @& JSL α) :
    RuntimeM (α)

end LeanRef

end Lean.Vir
