/-
Copyright (c) 2026 Lean FRO LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Author: Emilio J. Gallego Arias
-/

-- Generated by scripts/bindings/generate-lean-bindings.mjs. Do not edit.

module

public import Vir.Browser.Types

public section

namespace Lean.Vir.Browser

namespace Animation

/--
Generated reviewed function specialization of TypeScript `cancelAnimationFrame`.

[MDN Reference](https://developer.mozilla.org/docs/Web/API/DedicatedWorkerGlobalScope/cancelAnimationFrame)

Specialization policy: Lean gives the exact browser animation-frame token a phantom Js AnimationFrame type; the host passes that token unchanged to cancelAnimationFrame.

Upstream declaration: node_modules/typescript/lib/lib.dom.d.ts

ABI profile `browser-dom-faithful-v1`: receiver none; handle js-resource/consumed/call; result immediate/value.

This declaration is generated; edit the TypeScript source or binding configuration.
-/
@[vir_js "browser.animation.cancelAnimationFrame"]
opaque cancelAnimationFrame
    (handle : Lean.Vir.Js AnimationFrame) :
    DomM Unit

/--
Generated reviewed function specialization of TypeScript `requestAnimationFrame`.

[MDN Reference](https://developer.mozilla.org/docs/Web/API/DedicatedWorkerGlobalScope/requestAnimationFrame)

Specialization policy: VIR adapts the Lean callback and privately records pending cancellation for teardown, while returning the exact token produced by requestAnimationFrame.

Upstream declaration: node_modules/typescript/lib/lib.dom.d.ts

ABI profile `browser-dom-faithful-v1`: receiver none; callback callback/owned/until-release; result js-resource/owned.

This declaration is generated; edit the TypeScript source or binding configuration.
-/
@[vir_js "browser.animation.requestAnimationFrame"]
opaque requestAnimationFrameJs
    (callback : Lean.Vir.Js Float → DomM Unit) :
    DomM (Lean.Vir.Js AnimationFrame)

end Animation

namespace CanvasRenderingContext2D

/--
Generated reviewed method call policy for TypeScript `CanvasRenderingContext2D.arc`.

[MDN Reference](https://developer.mozilla.org/docs/Web/API/CanvasRenderingContext2D/arc)

Call policy: Omitting counterclockwise preserves the TypeScript default value false.

Upstream declaration: node_modules/typescript/lib/lib.dom.d.ts

ABI profile `browser-dom-faithful-v1`: canvasRenderingContext2D js-resource/borrowed/call; x js-resource/borrowed/call; y js-resource/borrowed/call; radius js-resource/borrowed/call; startAngle js-resource/borrowed/call; endAngle js-resource/borrowed/call; result immediate/value.

This declaration is generated; edit the TypeScript source or binding configuration.
-/
@[vir_js "browser.canvas2d.arc"]
opaque arcJs
    (canvasRenderingContext2D : @& Lean.Vir.Js CanvasRenderingContext2D)
    (x : @& Lean.Vir.Js Float)
    (y : @& Lean.Vir.Js Float)
    (radius : @& Lean.Vir.Js Float)
    (startAngle : @& Lean.Vir.Js Float)
    (endAngle : @& Lean.Vir.Js Float) :
    DomM Unit

/--
Faithful generated method binding for TypeScript `CanvasRenderingContext2D.beginPath`.

[MDN Reference](https://developer.mozilla.org/docs/Web/API/CanvasRenderingContext2D/beginPath)

Upstream declaration: node_modules/typescript/lib/lib.dom.d.ts

ABI profile `browser-dom-faithful-v1`: canvasRenderingContext2D js-resource/borrowed/call; result immediate/value.

This declaration is generated; edit the TypeScript source or binding configuration.
-/
@[vir_js "browser.canvas2d.beginPath"]
opaque beginPath
    (canvasRenderingContext2D : @& Lean.Vir.Js CanvasRenderingContext2D) :
    DomM Unit

/--
Faithful generated method binding for TypeScript `CanvasRenderingContext2D.clearRect`.

[MDN Reference](https://developer.mozilla.org/docs/Web/API/CanvasRenderingContext2D/clearRect)

Upstream declaration: node_modules/typescript/lib/lib.dom.d.ts

ABI profile `browser-dom-faithful-v1`: canvasRenderingContext2D js-resource/borrowed/call; x js-resource/borrowed/call; y js-resource/borrowed/call; w js-resource/borrowed/call; h js-resource/borrowed/call; result immediate/value.

This declaration is generated; edit the TypeScript source or binding configuration.
-/
@[vir_js "browser.canvas2d.clearRect"]
opaque clearRectJs
    (canvasRenderingContext2D : @& Lean.Vir.Js CanvasRenderingContext2D)
    (x : @& Lean.Vir.Js Float)
    (y : @& Lean.Vir.Js Float)
    (w : @& Lean.Vir.Js Float)
    (h : @& Lean.Vir.Js Float) :
    DomM Unit

/--
Faithful generated method binding for TypeScript `CanvasRenderingContext2D.closePath`.

[MDN Reference](https://developer.mozilla.org/docs/Web/API/CanvasRenderingContext2D/closePath)

Upstream declaration: node_modules/typescript/lib/lib.dom.d.ts

ABI profile `browser-dom-faithful-v1`: canvasRenderingContext2D js-resource/borrowed/call; result immediate/value.

This declaration is generated; edit the TypeScript source or binding configuration.
-/
@[vir_js "browser.canvas2d.closePath"]
opaque closePath
    (canvasRenderingContext2D : @& Lean.Vir.Js CanvasRenderingContext2D) :
    DomM Unit

/--
Generated reviewed method call policy for TypeScript `CanvasRenderingContext2D.fill`.

[MDN Reference](https://developer.mozilla.org/docs/Web/API/CanvasRenderingContext2D/fill)

Call policy: The selected overload is fill(fillRule?), and omitting fillRule preserves its nonzero default.

Upstream declaration: node_modules/typescript/lib/lib.dom.d.ts

ABI profile `browser-dom-faithful-v1`: canvasRenderingContext2D js-resource/borrowed/call; result immediate/value.

This declaration is generated; edit the TypeScript source or binding configuration.
-/
@[vir_js "browser.canvas2d.fill"]
opaque fill
    (canvasRenderingContext2D : @& Lean.Vir.Js CanvasRenderingContext2D) :
    DomM Unit

/--
Faithful generated method binding for TypeScript `CanvasRenderingContext2D.fillRect`.

[MDN Reference](https://developer.mozilla.org/docs/Web/API/CanvasRenderingContext2D/fillRect)

Upstream declaration: node_modules/typescript/lib/lib.dom.d.ts

ABI profile `browser-dom-faithful-v1`: canvasRenderingContext2D js-resource/borrowed/call; x js-resource/borrowed/call; y js-resource/borrowed/call; w js-resource/borrowed/call; h js-resource/borrowed/call; result immediate/value.

This declaration is generated; edit the TypeScript source or binding configuration.
-/
@[vir_js "browser.canvas2d.fillRect"]
opaque fillRectJs
    (canvasRenderingContext2D : @& Lean.Vir.Js CanvasRenderingContext2D)
    (x : @& Lean.Vir.Js Float)
    (y : @& Lean.Vir.Js Float)
    (w : @& Lean.Vir.Js Float)
    (h : @& Lean.Vir.Js Float) :
    DomM Unit

/--
Generated reviewed getter specialization of TypeScript `CanvasRenderingContext2D.fillStyle`.

[MDN Reference](https://developer.mozilla.org/docs/Web/API/CanvasRenderingContext2D/fillStyle)

Specialization policy: The JavaScript-owned CanvasStyle marker faithfully preserves the full string, CanvasGradient, and CanvasPattern union.

Upstream declaration: node_modules/typescript/lib/lib.dom.d.ts

ABI profile `browser-dom-faithful-v1`: ctx js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the TypeScript source or binding configuration.
-/
@[vir_js "browser.canvas2d.getFillStyle"]
opaque getFillStyle
    (ctx : @& Lean.Vir.Js CanvasRenderingContext2D) :
    DomM (Lean.Vir.Js CanvasStyle)

/--
Generated reviewed setter specialization of TypeScript `CanvasRenderingContext2D.fillStyle`.

[MDN Reference](https://developer.mozilla.org/docs/Web/API/CanvasRenderingContext2D/fillStyle)

Specialization policy: The JavaScript-owned CanvasStyle marker faithfully preserves the full string, CanvasGradient, and CanvasPattern union.

Upstream declaration: node_modules/typescript/lib/lib.dom.d.ts

ABI profile `browser-dom-faithful-v1`: ctx js-resource/borrowed/call; style js-resource/borrowed/call; result immediate/value.

This declaration is generated; edit the TypeScript source or binding configuration.
-/
@[vir_js "browser.canvas2d.setFillStyleValue"]
opaque setFillStyleValue
    (ctx : @& Lean.Vir.Js CanvasRenderingContext2D)
    (style : @& Lean.Vir.Js CanvasStyle) :
    DomM Unit

/--
Faithful generated method binding for TypeScript `CanvasRenderingContext2D.lineTo`.

[MDN Reference](https://developer.mozilla.org/docs/Web/API/CanvasRenderingContext2D/lineTo)

Upstream declaration: node_modules/typescript/lib/lib.dom.d.ts

ABI profile `browser-dom-faithful-v1`: canvasRenderingContext2D js-resource/borrowed/call; x js-resource/borrowed/call; y js-resource/borrowed/call; result immediate/value.

This declaration is generated; edit the TypeScript source or binding configuration.
-/
@[vir_js "browser.canvas2d.lineTo"]
opaque lineToJs
    (canvasRenderingContext2D : @& Lean.Vir.Js CanvasRenderingContext2D)
    (x : @& Lean.Vir.Js Float)
    (y : @& Lean.Vir.Js Float) :
    DomM Unit

/--
Faithful generated getter binding for TypeScript `CanvasRenderingContext2D.lineWidth`.

[MDN Reference](https://developer.mozilla.org/docs/Web/API/CanvasRenderingContext2D/lineWidth)

Upstream declaration: node_modules/typescript/lib/lib.dom.d.ts

ABI profile `browser-dom-faithful-v1`: ctx js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the TypeScript source or binding configuration.
-/
@[vir_js "browser.canvas2d.getLineWidth"]
opaque getLineWidth
    (ctx : @& Lean.Vir.Js CanvasRenderingContext2D) :
    DomM (Lean.Vir.Js Float)

/--
Faithful generated setter binding for TypeScript `CanvasRenderingContext2D.lineWidth`.

[MDN Reference](https://developer.mozilla.org/docs/Web/API/CanvasRenderingContext2D/lineWidth)

Upstream declaration: node_modules/typescript/lib/lib.dom.d.ts

ABI profile `browser-dom-faithful-v1`: ctx js-resource/borrowed/call; width js-resource/borrowed/call; result immediate/value.

This declaration is generated; edit the TypeScript source or binding configuration.
-/
@[vir_js "browser.canvas2d.setLineWidth"]
opaque setLineWidthJs
    (ctx : @& Lean.Vir.Js CanvasRenderingContext2D)
    (width : @& Lean.Vir.Js Float) :
    DomM Unit

/--
Faithful generated method binding for TypeScript `CanvasRenderingContext2D.measureText`.

[MDN Reference](https://developer.mozilla.org/docs/Web/API/CanvasRenderingContext2D/measureText)

Upstream declaration: node_modules/typescript/lib/lib.dom.d.ts

ABI profile `browser-dom-faithful-v1`: ctx js-resource/borrowed/call; text js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the TypeScript source or binding configuration.
-/
@[vir_js "browser.canvas2d.measureText"]
opaque measureText
    (ctx : @& Lean.Vir.Js CanvasRenderingContext2D)
    (text : @& Lean.Vir.Js String) :
    DomM (Lean.Vir.Js TextMetrics)

/--
Faithful generated method binding for TypeScript `CanvasRenderingContext2D.moveTo`.

[MDN Reference](https://developer.mozilla.org/docs/Web/API/CanvasRenderingContext2D/moveTo)

Upstream declaration: node_modules/typescript/lib/lib.dom.d.ts

ABI profile `browser-dom-faithful-v1`: canvasRenderingContext2D js-resource/borrowed/call; x js-resource/borrowed/call; y js-resource/borrowed/call; result immediate/value.

This declaration is generated; edit the TypeScript source or binding configuration.
-/
@[vir_js "browser.canvas2d.moveTo"]
opaque moveToJs
    (canvasRenderingContext2D : @& Lean.Vir.Js CanvasRenderingContext2D)
    (x : @& Lean.Vir.Js Float)
    (y : @& Lean.Vir.Js Float) :
    DomM Unit

/--
Faithful generated method binding for TypeScript `CanvasRenderingContext2D.restore`.

[MDN Reference](https://developer.mozilla.org/docs/Web/API/CanvasRenderingContext2D/restore)

Upstream declaration: node_modules/typescript/lib/lib.dom.d.ts

ABI profile `browser-dom-faithful-v1`: canvasRenderingContext2D js-resource/borrowed/call; result immediate/value.

This declaration is generated; edit the TypeScript source or binding configuration.
-/
@[vir_js "browser.canvas2d.restore"]
opaque restore
    (canvasRenderingContext2D : @& Lean.Vir.Js CanvasRenderingContext2D) :
    DomM Unit

/--
Faithful generated method binding for TypeScript `CanvasRenderingContext2D.rotate`.

[MDN Reference](https://developer.mozilla.org/docs/Web/API/CanvasRenderingContext2D/rotate)

Upstream declaration: node_modules/typescript/lib/lib.dom.d.ts

ABI profile `browser-dom-faithful-v1`: canvasRenderingContext2D js-resource/borrowed/call; angle js-resource/borrowed/call; result immediate/value.

This declaration is generated; edit the TypeScript source or binding configuration.
-/
@[vir_js "browser.canvas2d.rotate"]
opaque rotateJs
    (canvasRenderingContext2D : @& Lean.Vir.Js CanvasRenderingContext2D)
    (angle : @& Lean.Vir.Js Float) :
    DomM Unit

/--
Faithful generated method binding for TypeScript `CanvasRenderingContext2D.save`.

[MDN Reference](https://developer.mozilla.org/docs/Web/API/CanvasRenderingContext2D/save)

Upstream declaration: node_modules/typescript/lib/lib.dom.d.ts

ABI profile `browser-dom-faithful-v1`: canvasRenderingContext2D js-resource/borrowed/call; result immediate/value.

This declaration is generated; edit the TypeScript source or binding configuration.
-/
@[vir_js "browser.canvas2d.save"]
opaque save
    (canvasRenderingContext2D : @& Lean.Vir.Js CanvasRenderingContext2D) :
    DomM Unit

/--
Generated reviewed method call policy for TypeScript `CanvasRenderingContext2D.stroke`.

[MDN Reference](https://developer.mozilla.org/docs/Web/API/CanvasRenderingContext2D/stroke)

Call policy: The selected zero-argument overload is the complete current-path stroke operation.

Upstream declaration: node_modules/typescript/lib/lib.dom.d.ts

ABI profile `browser-dom-faithful-v1`: canvasRenderingContext2D js-resource/borrowed/call; result immediate/value.

This declaration is generated; edit the TypeScript source or binding configuration.
-/
@[vir_js "browser.canvas2d.stroke"]
opaque stroke
    (canvasRenderingContext2D : @& Lean.Vir.Js CanvasRenderingContext2D) :
    DomM Unit

/--
Faithful generated method binding for TypeScript `CanvasRenderingContext2D.strokeRect`.

[MDN Reference](https://developer.mozilla.org/docs/Web/API/CanvasRenderingContext2D/strokeRect)

Upstream declaration: node_modules/typescript/lib/lib.dom.d.ts

ABI profile `browser-dom-faithful-v1`: canvasRenderingContext2D js-resource/borrowed/call; x js-resource/borrowed/call; y js-resource/borrowed/call; w js-resource/borrowed/call; h js-resource/borrowed/call; result immediate/value.

This declaration is generated; edit the TypeScript source or binding configuration.
-/
@[vir_js "browser.canvas2d.strokeRect"]
opaque strokeRectJs
    (canvasRenderingContext2D : @& Lean.Vir.Js CanvasRenderingContext2D)
    (x : @& Lean.Vir.Js Float)
    (y : @& Lean.Vir.Js Float)
    (w : @& Lean.Vir.Js Float)
    (h : @& Lean.Vir.Js Float) :
    DomM Unit

/--
Generated reviewed getter specialization of TypeScript `CanvasRenderingContext2D.strokeStyle`.

[MDN Reference](https://developer.mozilla.org/docs/Web/API/CanvasRenderingContext2D/strokeStyle)

Specialization policy: The JavaScript-owned CanvasStyle marker faithfully preserves the full string, CanvasGradient, and CanvasPattern union.

Upstream declaration: node_modules/typescript/lib/lib.dom.d.ts

ABI profile `browser-dom-faithful-v1`: ctx js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the TypeScript source or binding configuration.
-/
@[vir_js "browser.canvas2d.getStrokeStyle"]
opaque getStrokeStyle
    (ctx : @& Lean.Vir.Js CanvasRenderingContext2D) :
    DomM (Lean.Vir.Js CanvasStyle)

/--
Generated reviewed setter specialization of TypeScript `CanvasRenderingContext2D.strokeStyle`.

[MDN Reference](https://developer.mozilla.org/docs/Web/API/CanvasRenderingContext2D/strokeStyle)

Specialization policy: The JavaScript-owned CanvasStyle marker faithfully preserves the full string, CanvasGradient, and CanvasPattern union.

Upstream declaration: node_modules/typescript/lib/lib.dom.d.ts

ABI profile `browser-dom-faithful-v1`: ctx js-resource/borrowed/call; style js-resource/borrowed/call; result immediate/value.

This declaration is generated; edit the TypeScript source or binding configuration.
-/
@[vir_js "browser.canvas2d.setStrokeStyleValue"]
opaque setStrokeStyleValue
    (ctx : @& Lean.Vir.Js CanvasRenderingContext2D)
    (style : @& Lean.Vir.Js CanvasStyle) :
    DomM Unit

/--
Faithful generated method binding for TypeScript `CanvasRenderingContext2D.translate`.

[MDN Reference](https://developer.mozilla.org/docs/Web/API/CanvasRenderingContext2D/translate)

Upstream declaration: node_modules/typescript/lib/lib.dom.d.ts

ABI profile `browser-dom-faithful-v1`: canvasRenderingContext2D js-resource/borrowed/call; x js-resource/borrowed/call; y js-resource/borrowed/call; result immediate/value.

This declaration is generated; edit the TypeScript source or binding configuration.
-/
@[vir_js "browser.canvas2d.translate"]
opaque translateJs
    (canvasRenderingContext2D : @& Lean.Vir.Js CanvasRenderingContext2D)
    (x : @& Lean.Vir.Js Float)
    (y : @& Lean.Vir.Js Float) :
    DomM Unit

end CanvasRenderingContext2D

namespace CanvasStyle

/--
Generated binding for reviewed VIR protocol `browser.canvas-style.of-string`.

Explicitly injects a Lean-owned string into the string arm of the exact JavaScript CanvasStyle union without changing its value.

Binding contract: `generation.protocolOperations`.

ABI profile `browser-dom-faithful-v1`: receiver none; style lean-owned/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js_explicit_conversion "js.value.browser.canvasStyle.string"]
opaque ofString
    (style : @& String) :
    Lean.Vir.RuntimeM (Lean.Vir.Js CanvasStyle)

end CanvasStyle

namespace Console

/--
Generated reviewed method specialization of TypeScript `Console.log`.

The **`console.log()`** static method outputs a message to the console.

[MDN Reference](https://developer.mozilla.org/docs/Web/API/console/log_static)

Specialization policy: The selected one-message call passes the exact Console receiver and JavaScript string unchanged; additional variadic values remain an explicit coverage gap.

Upstream declaration: node_modules/typescript/lib/lib.dom.d.ts

ABI profile `browser-dom-faithful-v1`: console js-resource/borrowed/call; message js-resource/borrowed/call; result immediate/value.

This declaration is generated; edit the TypeScript source or binding configuration.
-/
@[vir_js "browser.console.log"]
opaque logJs
    (console : @& Lean.Vir.Js Console)
    (message : @& Lean.Vir.Js String) :
    Lean.Vir.RuntimeM Unit

/--
Generated binding for reviewed VIR protocol `browser.console.current`.

Returns the host-global Console as an exact JavaScript value; this is explicit environment access rather than an implicit receiver adapter.

Binding contract: `generation.protocolOperations`.

ABI profile `browser-dom-faithful-v1`: receiver none; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "browser.console.current"]
opaque current : Lean.Vir.RuntimeM (Lean.Vir.Js Console)

end Console

namespace CSSStyleDeclaration

/--
Generated reviewed method call policy for TypeScript `CSSStyleDeclaration.setProperty`.

The **`CSSStyleDeclaration.setProperty()`** method interface sets a new value for a property on a CSS style declaration object.

[MDN Reference](https://developer.mozilla.org/docs/Web/API/CSSStyleDeclaration/setProperty)

Call policy: Omitting priority preserves CSSStyleDeclaration.setProperty's default empty priority while passing the exact declaration, property, value, and result unchanged.

Upstream declaration: https://unpkg.com/typescript@6.0.3/lib/lib.dom.d.ts#L6588

ABI profile `browser-dom-faithful-v1`: declaration js-resource/borrowed/call; property js-resource/borrowed/call; value js-resource/borrowed/call; result immediate/value.

This declaration is generated; edit the TypeScript source or binding configuration.
-/
@[vir_js "browser.cssStyleDeclaration.setProperty"]
opaque setProperty
    (declaration : @& Lean.Vir.Js CSSStyleDeclaration)
    (property : @& Lean.Vir.Js String)
    (value : @& Lean.Vir.Js.Nullable String) :
    DomM Unit

end CSSStyleDeclaration

namespace Document

/--
Generated reviewed method specialization of TypeScript `Document.createElement`.

In an HTML document, the **`document.createElement()`** method creates the HTML element specified by localName, or an HTMLUnknownElement if localName isn't recognized.

[MDN Reference](https://developer.mozilla.org/docs/Web/API/Document/createElement)

Specialization policy: The selected non-generic string overload passes the exact Document receiver and tag name unchanged and returns the exact element under VIR's common Element phantom type.

Upstream declaration: https://unpkg.com/typescript@6.0.3/lib/lib.dom.d.ts#L12929

ABI profile `browser-dom-faithful-v1`: document js-resource/borrowed/call; tagName js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the TypeScript source or binding configuration.
-/
@[vir_js "browser.document.createElement"]
opaque createElement
    (document : @& Lean.Vir.Js Document)
    (tagName : @& Lean.Vir.Js String) :
    DomM (Lean.Vir.Js Element)

/--
Generated reviewed method specialization of TypeScript `Document.querySelector`.

Returns the first element that is a descendant of node that matches selectors.

[MDN Reference](https://developer.mozilla.org/docs/Web/API/Document/querySelector)

Specialization policy: The selected non-generic selector overload passes the exact Document receiver and selector unchanged and returns the exact nullable value under VIR's common Element phantom type.

Upstream declaration: https://unpkg.com/typescript@6.0.3/lib/lib.dom.d.ts#L27086

ABI profile `browser-dom-faithful-v1`: document js-resource/borrowed/call; selectors js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the TypeScript source or binding configuration.
-/
@[vir_js "browser.document.querySelector"]
opaque querySelector
    (document : @& Lean.Vir.Js Document)
    (selectors : @& Lean.Vir.Js String) :
    DomM (Lean.Vir.Js.Nullable Element)

/--
Generated reviewed method specialization of TypeScript `Document.querySelectorAll`.

Returns all element descendants of node that match selectors.

[MDN Reference](https://developer.mozilla.org/docs/Web/API/Document/querySelectorAll)

Specialization policy: The selected non-generic selector overload passes the exact Document receiver and selector unchanged and returns the exact NodeList under VIR's common Element phantom type.

Upstream declaration: https://unpkg.com/typescript@6.0.3/lib/lib.dom.d.ts#L27097

ABI profile `browser-dom-faithful-v1`: document js-resource/borrowed/call; selectors js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the TypeScript source or binding configuration.
-/
@[vir_js "browser.document.querySelectorAll"]
opaque querySelectorAll
    (document : @& Lean.Vir.Js Document)
    (selectors : @& Lean.Vir.Js String) :
    DomM (Lean.Vir.Js.NodeList (Lean.Vir.Js Element))

/--
Faithful generated getter binding for TypeScript `Document.title`.

The **`document.title`** property gets or sets the current title of the document. When present, it defaults to the value of the <title>.

[MDN Reference](https://developer.mozilla.org/docs/Web/API/Document/title)

Upstream declaration: https://unpkg.com/typescript@6.0.3/lib/lib.dom.d.ts#L12848

ABI profile `browser-dom-faithful-v1`: document js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the TypeScript source or binding configuration.
-/
@[vir_js "browser.document.getTitle"]
opaque getTitle
    (document : @& Lean.Vir.Js Document) :
    DomM (Lean.Vir.Js String)

/--
Faithful generated setter binding for TypeScript `Document.title`.

The **`document.title`** property gets or sets the current title of the document. When present, it defaults to the value of the <title>.

[MDN Reference](https://developer.mozilla.org/docs/Web/API/Document/title)

Upstream declaration: https://unpkg.com/typescript@6.0.3/lib/lib.dom.d.ts#L12848

ABI profile `browser-dom-faithful-v1`: document js-resource/borrowed/call; title js-resource/borrowed/call; result immediate/value.

This declaration is generated; edit the TypeScript source or binding configuration.
-/
@[vir_js "browser.document.setTitle"]
opaque setTitle
    (document : @& Lean.Vir.Js Document)
    (title : @& Lean.Vir.Js String) :
    DomM Unit

/--
Generated binding for reviewed VIR protocol `browser.document.current`.

Returns the host-global Document as an exact JavaScript value; this is explicit environment access rather than an implicit receiver adapter.

Binding contract: `generation.protocolOperations`.

ABI profile `browser-dom-faithful-v1`: receiver none; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "browser.document.current"]
opaque current : DomM (Lean.Vir.Js Document)

end Document

namespace DOMTokenList

/--
Generated reviewed method call policy for TypeScript `DOMTokenList.add`.

The **`add()`** method of the DOMTokenList interface adds the given tokens to the list, omitting any that are already present.

[MDN Reference](https://developer.mozilla.org/docs/Web/API/DOMTokenList/add)

Call policy: The selected one-token call passes the exact DOMTokenList receiver and token unchanged; additional variadic tokens remain an explicit coverage gap.

Upstream declaration: https://unpkg.com/typescript@6.0.3/lib/lib.dom.d.ts#L12165

ABI profile `browser-dom-faithful-v1`: tokenList js-resource/borrowed/call; className js-resource/borrowed/call; result immediate/value.

This declaration is generated; edit the TypeScript source or binding configuration.
-/
@[vir_js "browser.domTokenList.add"]
opaque add
    (tokenList : @& Lean.Vir.Js DOMTokenList)
    (className : @& Lean.Vir.Js String) :
    DomM Unit

/--
Generated reviewed method call policy for TypeScript `DOMTokenList.remove`.

The **`remove()`** method of the DOMTokenList interface removes the specified tokens from the list.

[MDN Reference](https://developer.mozilla.org/docs/Web/API/DOMTokenList/remove)

Call policy: The selected one-token call passes the exact DOMTokenList receiver and token unchanged; additional variadic tokens remain an explicit coverage gap.

Upstream declaration: https://unpkg.com/typescript@6.0.3/lib/lib.dom.d.ts#L12183

ABI profile `browser-dom-faithful-v1`: tokenList js-resource/borrowed/call; className js-resource/borrowed/call; result immediate/value.

This declaration is generated; edit the TypeScript source or binding configuration.
-/
@[vir_js "browser.domTokenList.remove"]
opaque remove
    (tokenList : @& Lean.Vir.Js DOMTokenList)
    (className : @& Lean.Vir.Js String) :
    DomM Unit

/--
Generated reviewed method call policy for TypeScript `DOMTokenList.toggle`.

The **`toggle()`** method of the DOMTokenList interface removes an existing token from the list and returns false. If the token doesn't exist it's added and the function returns true.

[MDN Reference](https://developer.mozilla.org/docs/Web/API/DOMTokenList/toggle)

Call policy: Omitting force selects DOMTokenList.toggle's standard toggle behavior without changing the receiver, token, or result.

Upstream declaration: https://unpkg.com/typescript@6.0.3/lib/lib.dom.d.ts#L12201

ABI profile `browser-dom-faithful-v1`: tokenList js-resource/borrowed/call; token js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the TypeScript source or binding configuration.
-/
@[vir_js "browser.domTokenList.toggle"]
opaque toggle
    (tokenList : @& Lean.Vir.Js DOMTokenList)
    (token : @& Lean.Vir.Js String) :
    DomM (Lean.Vir.Js Bool)

end DOMTokenList

namespace Element

/--
Generated reviewed method specialization of TypeScript `Element.addEventListener`.

Specialization policy: VIR selects the JavaScript function arm of EventListenerOrEventListenerObject and passes the exact listener to Element.addEventListener; options remain an explicit coverage gap.

Upstream declaration: https://unpkg.com/typescript@6.0.3/lib/lib.dom.d.ts#L13915

ABI profile `browser-dom-faithful-v1`: element js-resource/borrowed/call; event js-resource/borrowed/call; listener js-resource/borrowed/call; result immediate/value.

This declaration is generated; edit the TypeScript source or binding configuration.
-/
@[vir_js "browser.element.addEventListener"]
opaque addEventListenerJs
    (element : @& Lean.Vir.Js Element)
    (event : @& Lean.Vir.Js String)
    (listener : @& Lean.Vir.Js EventListener) :
    DomM Unit

/--
Generated reviewed method specialization of TypeScript `Element.appendChild`.

The **`appendChild()`** method of the Node interface adds a node to the end of the list of children of a specified parent node.

[MDN Reference](https://developer.mozilla.org/docs/Web/API/Node/appendChild)

Specialization policy: VIR currently specializes Node's generic appendChild operation to exact values carrying the Element phantom type.

Upstream declaration: https://unpkg.com/typescript@6.0.3/lib/lib.dom.d.ts#L26125

ABI profile `browser-dom-faithful-v1`: element js-resource/borrowed/call; node js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the TypeScript source or binding configuration.
-/
@[vir_js "browser.element.appendChild"]
opaque appendChild
    (element : @& Lean.Vir.Js Element)
    (node : @& Lean.Vir.Js Element) :
    DomM (Lean.Vir.Js Element)

/--
Faithful generated getter binding for TypeScript `Element.classList`.

The read-only **`classList`** property of the Element interface contains a live DOMTokenList collection representing the class attribute of the element. This can then be used to manipulate the class list.

[MDN Reference](https://developer.mozilla.org/docs/Web/API/Element/classList)

Upstream declaration: https://unpkg.com/typescript@6.0.3/lib/lib.dom.d.ts#L13520

ABI profile `browser-dom-faithful-v1`: element js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the TypeScript source or binding configuration.
-/
@[vir_js "browser.element.getClassList"]
opaque getClassList
    (element : @& Lean.Vir.Js Element) :
    DomM (Lean.Vir.Js DOMTokenList)

/--
Faithful generated setter binding for TypeScript `Element.classList`.

The read-only **`classList`** property of the Element interface contains a live DOMTokenList collection representing the class attribute of the element. This can then be used to manipulate the class list.

[MDN Reference](https://developer.mozilla.org/docs/Web/API/Element/classList)

Upstream declaration: https://unpkg.com/typescript@6.0.3/lib/lib.dom.d.ts#L13520

ABI profile `browser-dom-faithful-v1`: element js-resource/borrowed/call; classList js-resource/borrowed/call; result immediate/value.

This declaration is generated; edit the TypeScript source or binding configuration.
-/
@[vir_js "browser.element.setClassList"]
opaque setClassList
    (element : @& Lean.Vir.Js Element)
    (classList : @& Lean.Vir.Js String) :
    DomM Unit

/--
Faithful generated method binding for TypeScript `Element.getAttribute`.

The **`getAttribute()`** method of the Element interface returns the value of a specified attribute on the element.

[MDN Reference](https://developer.mozilla.org/docs/Web/API/Element/getAttribute)

Upstream declaration: https://unpkg.com/typescript@6.0.3/lib/lib.dom.d.ts#L13681

ABI profile `browser-dom-faithful-v1`: element js-resource/borrowed/call; qualifiedName js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the TypeScript source or binding configuration.
-/
@[vir_js "browser.element.getAttribute"]
opaque getAttribute
    (element : @& Lean.Vir.Js Element)
    (qualifiedName : @& Lean.Vir.Js String) :
    DomM (Lean.Vir.Js.Nullable String)

/--
Faithful generated getter binding for TypeScript `Element.innerHTML`.

The **`innerHTML`** property of the Element interface gets or sets the HTML or XML markup contained within the element, omitting any shadow roots in both cases.

[MDN Reference](https://developer.mozilla.org/docs/Web/API/Element/innerHTML)

Upstream declaration: https://unpkg.com/typescript@6.0.3/lib/lib.dom.d.ts#L13570

ABI profile `browser-dom-faithful-v1`: element js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the TypeScript source or binding configuration.
-/
@[vir_js "browser.element.getInnerHTML"]
opaque getInnerHTML
    (element : @& Lean.Vir.Js Element) :
    DomM (Lean.Vir.Js String)

/--
Faithful generated setter binding for TypeScript `Element.innerHTML`.

The **`innerHTML`** property of the Element interface gets or sets the HTML or XML markup contained within the element, omitting any shadow roots in both cases.

[MDN Reference](https://developer.mozilla.org/docs/Web/API/Element/innerHTML)

Upstream declaration: https://unpkg.com/typescript@6.0.3/lib/lib.dom.d.ts#L13570

ABI profile `browser-dom-faithful-v1`: element js-resource/borrowed/call; innerHTML js-resource/borrowed/call; result immediate/value.

This declaration is generated; edit the TypeScript source or binding configuration.
-/
@[vir_js "browser.element.setInnerHTML"]
opaque setInnerHTML
    (element : @& Lean.Vir.Js Element)
    (innerHTML : @& Lean.Vir.Js String) :
    DomM Unit

/--
Generated reviewed method specialization of TypeScript `Element.querySelector`.

Returns the first element that is a descendant of node that matches selectors.

[MDN Reference](https://developer.mozilla.org/docs/Web/API/Document/querySelector)

Specialization policy: The non-generic selector overload returns the exact element under VIR's common Element phantom type.

Upstream declaration: https://unpkg.com/typescript@6.0.3/lib/lib.dom.d.ts#L27086

ABI profile `browser-dom-faithful-v1`: element js-resource/borrowed/call; selectors js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the TypeScript source or binding configuration.
-/
@[vir_js "browser.element.querySelector"]
opaque querySelector
    (element : @& Lean.Vir.Js Element)
    (selectors : @& Lean.Vir.Js String) :
    DomM (Lean.Vir.Js.Nullable Element)

/--
Generated reviewed method specialization of TypeScript `Element.querySelectorAll`.

Returns all element descendants of node that match selectors.

[MDN Reference](https://developer.mozilla.org/docs/Web/API/Document/querySelectorAll)

Specialization policy: The non-generic selector overload returns the exact JavaScript NodeList with Element-typed entries.

Upstream declaration: https://unpkg.com/typescript@6.0.3/lib/lib.dom.d.ts#L27097

ABI profile `browser-dom-faithful-v1`: element js-resource/borrowed/call; selectors js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the TypeScript source or binding configuration.
-/
@[vir_js "browser.element.querySelectorAll"]
opaque querySelectorAll
    (element : @& Lean.Vir.Js Element)
    (selectors : @& Lean.Vir.Js String) :
    DomM (Lean.Vir.Js.NodeList (Lean.Vir.Js Element))

/--
Faithful generated method binding for TypeScript `Element.remove`.

Removes node.

[MDN Reference](https://developer.mozilla.org/docs/Web/API/CharacterData/remove)

Upstream declaration: https://unpkg.com/typescript@6.0.3/lib/lib.dom.d.ts#L10671

ABI profile `browser-dom-faithful-v1`: element js-resource/borrowed/call; result immediate/value.

This declaration is generated; edit the TypeScript source or binding configuration.
-/
@[vir_js "browser.element.remove"]
opaque remove
    (element : @& Lean.Vir.Js Element) :
    DomM Unit

/--
Generated reviewed method specialization of TypeScript `Element.removeEventListener`.

Specialization policy: VIR selects the JavaScript function arm of EventListenerOrEventListenerObject and passes the exact receiver, event name, and listener to Element.removeEventListener; options remain an explicit coverage gap.

Upstream declaration: https://unpkg.com/typescript@6.0.3/lib/lib.dom.d.ts#L13917

ABI profile `browser-dom-faithful-v1`: element js-resource/borrowed/call; event js-resource/borrowed/call; listener js-resource/borrowed/call; result immediate/value.

This declaration is generated; edit the TypeScript source or binding configuration.
-/
@[vir_js "browser.element.removeEventListener"]
opaque removeEventListenerJs
    (element : @& Lean.Vir.Js Element)
    (event : @& Lean.Vir.Js String)
    (listener : @& Lean.Vir.Js EventListener) :
    DomM Unit

/--
Faithful generated method binding for TypeScript `Element.setAttribute`.

The **`setAttribute()`** method of the Element interface sets the value of an attribute on the specified element. If the attribute already exists, the value is updated; otherwise a new attribute is added with the specified name and value.

[MDN Reference](https://developer.mozilla.org/docs/Web/API/Element/setAttribute)

Upstream declaration: https://unpkg.com/typescript@6.0.3/lib/lib.dom.d.ts#L13869

ABI profile `browser-dom-faithful-v1`: element js-resource/borrowed/call; qualifiedName js-resource/borrowed/call; value js-resource/borrowed/call; result immediate/value.

This declaration is generated; edit the TypeScript source or binding configuration.
-/
@[vir_js "browser.element.setAttribute"]
opaque setAttribute
    (element : @& Lean.Vir.Js Element)
    (qualifiedName : @& Lean.Vir.Js String)
    (value : @& Lean.Vir.Js String) :
    DomM Unit

/--
Faithful generated getter binding for TypeScript `Element.textContent`.

[MDN Reference](https://developer.mozilla.org/docs/Web/API/Node/textContent)

Upstream declaration: https://unpkg.com/typescript@6.0.3/lib/lib.dom.d.ts#L13913

ABI profile `browser-dom-faithful-v1`: element js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the TypeScript source or binding configuration.
-/
@[vir_js "browser.element.getTextContent"]
opaque getTextContent
    (element : @& Lean.Vir.Js Element) :
    DomM (Lean.Vir.Js String)

/--
Faithful generated setter binding for TypeScript `Element.textContent`.

[MDN Reference](https://developer.mozilla.org/docs/Web/API/Node/textContent)

Upstream declaration: https://unpkg.com/typescript@6.0.3/lib/lib.dom.d.ts#L13913

ABI profile `browser-dom-faithful-v1`: element js-resource/borrowed/call; textContent js-resource/borrowed/call; result immediate/value.

This declaration is generated; edit the TypeScript source or binding configuration.
-/
@[vir_js "browser.element.setTextContent"]
opaque setTextContent
    (element : @& Lean.Vir.Js Element)
    (textContent : @& Lean.Vir.Js.Nullable String) :
    DomM Unit

end Element

namespace ElementCSSInlineStyle

/--
Faithful generated getter binding for TypeScript `ElementCSSInlineStyle.style`.

[MDN Reference](https://developer.mozilla.org/docs/Web/API/HTMLElement/style)

Upstream declaration: https://unpkg.com/typescript@6.0.3/lib/lib.dom.d.ts#L13930

ABI profile `browser-dom-faithful-v1`: elementCSSInlineStyle js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the TypeScript source or binding configuration.
-/
@[vir_js "browser.elementCSSInlineStyle.getStyle"]
opaque getStyle
    (elementCSSInlineStyle : @& Lean.Vir.Js ElementCSSInlineStyle) :
    DomM (Lean.Vir.Js CSSStyleDeclaration)

/--
Faithful generated setter binding for TypeScript `ElementCSSInlineStyle.style`.

[MDN Reference](https://developer.mozilla.org/docs/Web/API/HTMLElement/style)

Upstream declaration: https://unpkg.com/typescript@6.0.3/lib/lib.dom.d.ts#L13930

ABI profile `browser-dom-faithful-v1`: elementCSSInlineStyle js-resource/borrowed/call; style js-resource/borrowed/call; result immediate/value.

This declaration is generated; edit the TypeScript source or binding configuration.
-/
@[vir_js "browser.elementCSSInlineStyle.setStyle"]
opaque setStyle
    (elementCSSInlineStyle : @& Lean.Vir.Js ElementCSSInlineStyle)
    (style : @& Lean.Vir.Js String) :
    DomM Unit

/--
Generated binding for reviewed VIR protocol `browser.element-css-inline-style.from-element`.

This checked structural narrowing preserves the exact JavaScript element value when it implements ElementCSSInlineStyle.

Binding contract: `generation.protocolOperations`.

ABI profile `browser-dom-faithful-v1`: receiver none; element js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "browser.elementCSSInlineStyle.fromElement"]
opaque fromElementNullable
    (element : @& Lean.Vir.Js Element) :
    DomM (Lean.Vir.Js.Nullable ElementCSSInlineStyle)

end ElementCSSInlineStyle

namespace Event

/--
Faithful generated getter binding for TypeScript `Event.currentTarget`.

The **`currentTarget`** read-only property of the Event interface identifies the element to which the event handler has been attached.

[MDN Reference](https://developer.mozilla.org/docs/Web/API/Event/currentTarget)

Upstream declaration: node_modules/typescript/lib/lib.dom.d.ts

ABI profile `browser-dom-faithful-v1`: event js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the TypeScript source or binding configuration.
-/
@[vir_js "browser.event.currentTarget"]
opaque getCurrentTarget
    (event : @& Lean.Vir.Js Event) :
    DomM (Lean.Vir.Js.Nullable EventTarget)

/--
Faithful generated method binding for TypeScript `Event.preventDefault`.

The **`preventDefault()`** method of the Event interface tells the user agent that the event is being explicitly handled, so its default action, such as page scrolling, link navigation, or pasting text, should not be taken.

[MDN Reference](https://developer.mozilla.org/docs/Web/API/Event/preventDefault)

Upstream declaration: node_modules/typescript/lib/lib.dom.d.ts

ABI profile `browser-dom-faithful-v1`: event js-resource/borrowed/call; result immediate/value.

This declaration is generated; edit the TypeScript source or binding configuration.
-/
@[vir_js "browser.event.preventDefault"]
opaque preventDefault
    (event : @& Lean.Vir.Js Event) :
    DomM Unit

/--
Faithful generated method binding for TypeScript `Event.stopPropagation`.

The **`stopPropagation()`** method of the Event interface prevents further propagation of the current event in the capturing and bubbling phases. It does not, however, prevent any default behaviors from occurring; for instance, clicks on links are still processed. If you want to stop those behaviors, see the preventDefault() method. It also does not prevent propagation to other event-handlers of the current element. If you want to stop those, see stopImmediatePropagation().

[MDN Reference](https://developer.mozilla.org/docs/Web/API/Event/stopPropagation)

Upstream declaration: node_modules/typescript/lib/lib.dom.d.ts

ABI profile `browser-dom-faithful-v1`: event js-resource/borrowed/call; result immediate/value.

This declaration is generated; edit the TypeScript source or binding configuration.
-/
@[vir_js "browser.event.stopPropagation"]
opaque stopPropagation
    (event : @& Lean.Vir.Js Event) :
    DomM Unit

/--
Faithful generated getter binding for TypeScript `Event.target`.

The read-only **`target`** property of the Event interface is a reference to the object onto which the event was dispatched. It is different from Event.currentTarget when the event handler is called during the bubbling or capturing phase of the event.

[MDN Reference](https://developer.mozilla.org/docs/Web/API/Event/target)

Upstream declaration: node_modules/typescript/lib/lib.dom.d.ts

ABI profile `browser-dom-faithful-v1`: event js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the TypeScript source or binding configuration.
-/
@[vir_js "browser.event.target"]
opaque getTarget
    (event : @& Lean.Vir.Js Event) :
    DomM (Lean.Vir.Js.Nullable EventTarget)

/--
Generated binding for reviewed VIR protocol `browser.event.formValue`.

This local protocol extracts the common value property from supported form-control event targets.

Binding contract: `generation.protocolOperations`.

ABI profile `browser-dom-faithful-v1`: receiver none; event js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "browser.event.formValue"]
opaque formValueNullable
    (event : @& Lean.Vir.Js Event) :
    DomM (Lean.Vir.Js.Nullable String)

end Event

namespace EventListener

/--
Generated binding for reviewed VIR protocol `browser.event-listener.of-lean`.

Explicitly converts a transferred Lean event callback into an ordinary JavaScript function that can be passed unchanged to addEventListener and removeEventListener.

Binding contract: `generation.protocolOperations`.

ABI profile `browser-dom-faithful-v1`: receiver none; callback callback/owned/until-release; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js_explicit_conversion "js.value.browser.eventListener"]
opaque ofLean
    (callback : Lean.Vir.Js Event → DomM Unit) :
    Lean.Vir.RuntimeM (Lean.Vir.Js EventListener)

end EventListener

namespace EventTarget

/--
Generated binding for reviewed VIR protocol `browser.event-target.as-element`.

Checks whether an EventTarget is an Element and preserves the exact JavaScript identity on success; this is explicit narrowing, not an Event property adapter.

Binding contract: `generation.protocolOperations`.

ABI profile `browser-dom-faithful-v1`: receiver none; target js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "browser.eventTarget.asElement"]
opaque asElementNullable
    (target : @& Lean.Vir.Js EventTarget) :
    DomM (Lean.Vir.Js.Nullable Element)

end EventTarget

namespace HTMLCanvasElement

/--
Generated reviewed method specialization of TypeScript `HTMLCanvasElement.getContext`.

The **`HTMLCanvasElement.getContext()`** method returns a drawing context on the canvas, or null if the context identifier is not supported, or the canvas has already been set to a different context mode.

[MDN Reference](https://developer.mozilla.org/docs/Web/API/HTMLCanvasElement/getContext)

Specialization policy: VIR specializes HTMLCanvasElement.getContext to the fixed 2d context id and default options.

Upstream declaration: node_modules/typescript/lib/lib.dom.d.ts

ABI profile `browser-dom-faithful-v1`: canvas js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the TypeScript source or binding configuration.
-/
@[vir_js "browser.htmlCanvasElement.getContext2D"]
opaque getContext2DNullable
    (canvas : @& Lean.Vir.Js HTMLCanvasElement) :
    DomM (Lean.Vir.Js.Nullable CanvasRenderingContext2D)

/--
Faithful generated getter binding for TypeScript `HTMLCanvasElement.height`.

The **`HTMLCanvasElement.height`** property is a positive integer reflecting the height HTML attribute of the <canvas> element interpreted in CSS pixels. When the attribute is not specified, or if it is set to an invalid value, like a negative, the default value of 150 is used.

[MDN Reference](https://developer.mozilla.org/docs/Web/API/HTMLCanvasElement/height)

Upstream declaration: node_modules/typescript/lib/lib.dom.d.ts

ABI profile `browser-dom-faithful-v1`: hTMLCanvasElement js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the TypeScript source or binding configuration.
-/
@[vir_js "browser.htmlCanvasElement.getHeight"]
opaque getHeight
    (hTMLCanvasElement : @& Lean.Vir.Js HTMLCanvasElement) :
    DomM (Lean.Vir.Js Float)

/--
Faithful generated setter binding for TypeScript `HTMLCanvasElement.height`.

The **`HTMLCanvasElement.height`** property is a positive integer reflecting the height HTML attribute of the <canvas> element interpreted in CSS pixels. When the attribute is not specified, or if it is set to an invalid value, like a negative, the default value of 150 is used.

[MDN Reference](https://developer.mozilla.org/docs/Web/API/HTMLCanvasElement/height)

Upstream declaration: node_modules/typescript/lib/lib.dom.d.ts

ABI profile `browser-dom-faithful-v1`: hTMLCanvasElement js-resource/borrowed/call; height js-resource/borrowed/call; result immediate/value.

This declaration is generated; edit the TypeScript source or binding configuration.
-/
@[vir_js "browser.htmlCanvasElement.setHeight"]
opaque setHeight
    (hTMLCanvasElement : @& Lean.Vir.Js HTMLCanvasElement)
    (height : @& Lean.Vir.Js Float) :
    DomM Unit

/--
Faithful generated getter binding for TypeScript `HTMLCanvasElement.width`.

The **`HTMLCanvasElement.width`** property is a positive integer reflecting the width HTML attribute of the <canvas> element interpreted in CSS pixels. When the attribute is not specified, or if it is set to an invalid value, like a negative, the default value of 300 is used.

[MDN Reference](https://developer.mozilla.org/docs/Web/API/HTMLCanvasElement/width)

Upstream declaration: node_modules/typescript/lib/lib.dom.d.ts

ABI profile `browser-dom-faithful-v1`: hTMLCanvasElement js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the TypeScript source or binding configuration.
-/
@[vir_js "browser.htmlCanvasElement.getWidth"]
opaque getWidth
    (hTMLCanvasElement : @& Lean.Vir.Js HTMLCanvasElement) :
    DomM (Lean.Vir.Js Float)

/--
Faithful generated setter binding for TypeScript `HTMLCanvasElement.width`.

The **`HTMLCanvasElement.width`** property is a positive integer reflecting the width HTML attribute of the <canvas> element interpreted in CSS pixels. When the attribute is not specified, or if it is set to an invalid value, like a negative, the default value of 300 is used.

[MDN Reference](https://developer.mozilla.org/docs/Web/API/HTMLCanvasElement/width)

Upstream declaration: node_modules/typescript/lib/lib.dom.d.ts

ABI profile `browser-dom-faithful-v1`: hTMLCanvasElement js-resource/borrowed/call; width js-resource/borrowed/call; result immediate/value.

This declaration is generated; edit the TypeScript source or binding configuration.
-/
@[vir_js "browser.htmlCanvasElement.setWidth"]
opaque setWidth
    (hTMLCanvasElement : @& Lean.Vir.Js HTMLCanvasElement)
    (width : @& Lean.Vir.Js Float) :
    DomM Unit

/--
Generated binding for reviewed VIR protocol `browser.canvas.fromElement`.

This checked narrowing preserves the exact JavaScript value and has no corresponding JavaScript method.

Binding contract: `generation.protocolOperations`.

ABI profile `browser-dom-faithful-v1`: receiver none; element js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "browser.htmlCanvasElement.fromElement"]
opaque fromElementNullable
    (element : @& Lean.Vir.Js Element) :
    DomM (Lean.Vir.Js.Nullable HTMLCanvasElement)

end HTMLCanvasElement

namespace HTMLInputElement

/--
Faithful generated getter binding for TypeScript `HTMLInputElement.checked`.

The **`checked`** property of the HTMLInputElement interface specifies the current checkedness of the element; that is, whether the form control is checked or not.

[MDN Reference](https://developer.mozilla.org/docs/Web/API/HTMLInputElement/checked)

Upstream declaration: node_modules/typescript/lib/lib.dom.d.ts

ABI profile `browser-dom-faithful-v1`: hTMLInputElement js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the TypeScript source or binding configuration.
-/
@[vir_js "browser.htmlInputElement.getChecked"]
opaque getChecked
    (hTMLInputElement : @& Lean.Vir.Js HTMLInputElement) :
    DomM (Lean.Vir.Js Bool)

/--
Faithful generated setter binding for TypeScript `HTMLInputElement.checked`.

The **`checked`** property of the HTMLInputElement interface specifies the current checkedness of the element; that is, whether the form control is checked or not.

[MDN Reference](https://developer.mozilla.org/docs/Web/API/HTMLInputElement/checked)

Upstream declaration: node_modules/typescript/lib/lib.dom.d.ts

ABI profile `browser-dom-faithful-v1`: hTMLInputElement js-resource/borrowed/call; checked js-resource/borrowed/call; result immediate/value.

This declaration is generated; edit the TypeScript source or binding configuration.
-/
@[vir_js "browser.htmlInputElement.setChecked"]
opaque setChecked
    (hTMLInputElement : @& Lean.Vir.Js HTMLInputElement)
    (checked : @& Lean.Vir.Js Bool) :
    DomM Unit

/--
Faithful generated getter binding for TypeScript `HTMLInputElement.value`.

The **`value`** property of the HTMLInputElement interface represents the current value of the <input> element as a string.

[MDN Reference](https://developer.mozilla.org/docs/Web/API/HTMLInputElement/value)

Upstream declaration: node_modules/typescript/lib/lib.dom.d.ts

ABI profile `browser-dom-faithful-v1`: hTMLInputElement js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the TypeScript source or binding configuration.
-/
@[vir_js "browser.htmlInputElement.getValue"]
opaque getValue
    (hTMLInputElement : @& Lean.Vir.Js HTMLInputElement) :
    DomM (Lean.Vir.Js String)

/--
Faithful generated setter binding for TypeScript `HTMLInputElement.value`.

The **`value`** property of the HTMLInputElement interface represents the current value of the <input> element as a string.

[MDN Reference](https://developer.mozilla.org/docs/Web/API/HTMLInputElement/value)

Upstream declaration: node_modules/typescript/lib/lib.dom.d.ts

ABI profile `browser-dom-faithful-v1`: hTMLInputElement js-resource/borrowed/call; value js-resource/borrowed/call; result immediate/value.

This declaration is generated; edit the TypeScript source or binding configuration.
-/
@[vir_js "browser.htmlInputElement.setValue"]
opaque setValue
    (hTMLInputElement : @& Lean.Vir.Js HTMLInputElement)
    (value : @& Lean.Vir.Js String) :
    DomM Unit

/--
Generated binding for reviewed VIR protocol `browser.input.fromElement`.

This checked narrowing preserves the exact JavaScript value and has no corresponding JavaScript method.

Binding contract: `generation.protocolOperations`.

ABI profile `browser-dom-faithful-v1`: receiver none; element js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "browser.htmlInputElement.fromElement"]
opaque fromElementNullable
    (element : @& Lean.Vir.Js Element) :
    DomM (Lean.Vir.Js.Nullable HTMLInputElement)

end HTMLInputElement

namespace Internal

/--
Generated binding for reviewed VIR protocol `browser.internal.ownedString`.

This explicit convenience conversion creates a JavaScript string value before calling the lower-level binding.

Binding contract: `generation.protocolOperations`.

ABI profile `browser-dom-faithful-v1`: receiver none; value lean-owned/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js_explicit_conversion "js.string.owned"]
opaque ownedString
    (value : @& String) :
    Lean.Vir.RuntimeM (Lean.Vir.Js String)

/--
Generated binding for reviewed VIR protocol `browser.internal.ownedFloat`.

This explicit convenience conversion creates a JavaScript number value for the lower-level canvas binding.

Binding contract: `generation.protocolOperations`.

ABI profile `browser-dom-faithful-v1`: receiver none; value immediate/value/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js_explicit_conversion "js.float.owned"]
opaque ownedFloat
    (value : Float) :
    Lean.Vir.RuntimeM (Lean.Vir.Js Float)

end Internal

namespace KeyboardEvent

/--
Faithful generated getter binding for TypeScript `KeyboardEvent.key`.

The KeyboardEvent interface's **`key`** read-only property returns the value of the key pressed by the user, taking into consideration the state of modifier keys such as Shift as well as the keyboard locale and layout.

[MDN Reference](https://developer.mozilla.org/docs/Web/API/KeyboardEvent/key)

Upstream declaration: node_modules/typescript/lib/lib.dom.d.ts

ABI profile `browser-dom-faithful-v1`: keyboardEvent js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the TypeScript source or binding configuration.
-/
@[vir_js "browser.keyboardEvent.getKey"]
opaque getKey
    (keyboardEvent : @& Lean.Vir.Js KeyboardEvent) :
    DomM (Lean.Vir.Js String)

/--
Generated binding for reviewed VIR protocol `browser.keyboard-event.from-event`.

This checked narrowing preserves the exact JavaScript event value and has no corresponding JavaScript method.

Binding contract: `generation.protocolOperations`.

ABI profile `browser-dom-faithful-v1`: receiver none; event js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "browser.keyboardEvent.fromEvent"]
opaque fromEventNullable
    (event : @& Lean.Vir.Js Event) :
    DomM (Lean.Vir.Js.Nullable KeyboardEvent)

end KeyboardEvent

namespace TextMetrics

/--
Faithful generated getter binding for TypeScript `TextMetrics.width`.

The read-only **`width`** property of the TextMetrics interface contains the text's advance width (the width of that inline box) in CSS pixels.

[MDN Reference](https://developer.mozilla.org/docs/Web/API/TextMetrics/width)

Upstream declaration: node_modules/typescript/lib/lib.dom.d.ts

ABI profile `browser-dom-faithful-v1`: metrics js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the TypeScript source or binding configuration.
-/
@[vir_js "browser.canvas2d.textMetrics.getWidth"]
opaque getWidth
    (metrics : @& Lean.Vir.Js TextMetrics) :
    DomM (Lean.Vir.Js Float)

end TextMetrics

namespace Timer

/--
Generated binding for reviewed VIR protocol `browser.timer.setTimeout`.

VIR selects the function callback arm, passes the callback and numeric delay in native order, privately records pending cancellation for teardown, and returns the exact token produced by setTimeout.

Binding contract: `generation.protocolOperations`.

ABI profile `browser-dom-faithful-v1`: receiver none; callback callback/owned/until-release; delayMs js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "browser.timer.setTimeout"]
opaque setTimeoutJs
    (callback : DomM Unit)
    (delayMs : @& Lean.Vir.Js Float) :
    DomM (Lean.Vir.Js Timeout)

/--
Generated binding for reviewed VIR protocol `browser.timer.clearTimeout`.

The exact timeout token is passed unchanged to clearTimeout; the terminal Lean operation also removes VIR's private pending-cancellation record without revoking JavaScript aliases.

Binding contract: `generation.protocolOperations`.

ABI profile `browser-dom-faithful-v1`: receiver none; timeout js-resource/consumed/call; result immediate/value.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "browser.timer.clearTimeout"]
opaque clearTimeout
    (timeout : Lean.Vir.Js Timeout) :
    DomM Unit

/--
Generated binding for reviewed VIR protocol `browser.timer.setInterval`.

VIR selects the function callback arm, passes the callback and numeric delay in native order, privately records pending cancellation for teardown, and returns the exact token produced by setInterval.

Binding contract: `generation.protocolOperations`.

ABI profile `browser-dom-faithful-v1`: receiver none; callback callback/owned/until-release; delayMs js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "browser.timer.setInterval"]
opaque setIntervalJs
    (callback : DomM Unit)
    (delayMs : @& Lean.Vir.Js Float) :
    DomM (Lean.Vir.Js Interval)

/--
Generated binding for reviewed VIR protocol `browser.timer.clearInterval`.

The exact interval token is passed unchanged to clearInterval; the terminal Lean operation also removes VIR's private pending-cancellation record without revoking JavaScript aliases.

Binding contract: `generation.protocolOperations`.

ABI profile `browser-dom-faithful-v1`: receiver none; interval js-resource/consumed/call; result immediate/value.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "browser.timer.clearInterval"]
opaque clearInterval
    (interval : Lean.Vir.Js Interval) :
    DomM Unit

end Timer

end Lean.Vir.Browser
