/-
Copyright (c) 2026 Lean FRO LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Author: Emilio J. Gallego Arias
-/

-- Generated by scripts/bindings/generate-lean-bindings.mjs. Do not edit.

import Vir.Browser.Types

namespace Lean.Vir.Browser

namespace Document

/--
Generated faithful JavaScript boundary for the TypeScript `Document.title` getter.
Source: https://unpkg.com/typescript@6.0.3/lib/lib.dom.d.ts#L12848

This declaration is generated; edit the TypeScript source or binding configuration.
-/
@[vir_js "browser.document.getTitle"]
private opaque getTitleJs : DomM (Lean.Vir.Js String)

/-- Faithful generated getter binding for TypeScript `Document.title`. -/
def getTitle : DomM (Lean.Vir.Js String) :=
  getTitleJs

/--
Generated faithful JavaScript boundary for the TypeScript `Document.title` setter.
Source: https://unpkg.com/typescript@6.0.3/lib/lib.dom.d.ts#L12848

This declaration is generated; edit the TypeScript source or binding configuration.
-/
@[vir_js "browser.document.setTitle"]
private opaque setTitleJs
    (title : @& Lean.Vir.Js String) :
    DomM Unit

/-- Faithful generated setter binding for TypeScript `Document.title`. -/
def setTitle
    (title : @& Lean.Vir.Js String) :
    DomM Unit :=
  setTitleJs title

end Document

namespace Element

/--
Generated faithful JavaScript boundary for the TypeScript `Element.innerHTML` getter.
Source: https://unpkg.com/typescript@6.0.3/lib/lib.dom.d.ts#L13570

This declaration is generated; edit the TypeScript source or binding configuration.
-/
@[vir_js "browser.element.getInnerHTML"]
private opaque getInnerHTMLJs
    (element : @& Lean.Vir.Js Element) :
    DomM (Lean.Vir.Js String)

/-- Faithful generated getter binding for TypeScript `Element.innerHTML`. -/
def getInnerHTML
    (element : @& Lean.Vir.Js Element) :
    DomM (Lean.Vir.Js String) :=
  getInnerHTMLJs element

/--
Generated faithful JavaScript boundary for the TypeScript `Element.innerHTML` setter.
Source: https://unpkg.com/typescript@6.0.3/lib/lib.dom.d.ts#L13570

This declaration is generated; edit the TypeScript source or binding configuration.
-/
@[vir_js "browser.element.setInnerHTML"]
private opaque setInnerHTMLJs
    (element : @& Lean.Vir.Js Element)
    (innerHTML : @& Lean.Vir.Js String) :
    DomM Unit

/-- Faithful generated setter binding for TypeScript `Element.innerHTML`. -/
def setInnerHTML
    (element : @& Lean.Vir.Js Element)
    (innerHTML : @& Lean.Vir.Js String) :
    DomM Unit :=
  setInnerHTMLJs element innerHTML

/--
Generated faithful JavaScript boundary for the TypeScript `Element.textContent` getter.
Source: https://unpkg.com/typescript@6.0.3/lib/lib.dom.d.ts#L13913

This declaration is generated; edit the TypeScript source or binding configuration.
-/
@[vir_js "browser.element.getTextContent"]
private opaque getTextContentJs
    (element : @& Lean.Vir.Js Element) :
    DomM (Lean.Vir.Js String)

/-- Faithful generated getter binding for TypeScript `Element.textContent`. -/
def getTextContent
    (element : @& Lean.Vir.Js Element) :
    DomM (Lean.Vir.Js String) :=
  getTextContentJs element

/--
Generated faithful JavaScript boundary for the TypeScript `Element.textContent` setter.
Source: https://unpkg.com/typescript@6.0.3/lib/lib.dom.d.ts#L13913

This declaration is generated; edit the TypeScript source or binding configuration.
-/
@[vir_js "browser.element.setTextContent"]
private opaque setTextContentJs
    (element : @& Lean.Vir.Js Element)
    (textContent : @& Lean.Vir.Js.Nullable String) :
    DomM Unit

/-- Faithful generated setter binding for TypeScript `Element.textContent`. -/
def setTextContent
    (element : @& Lean.Vir.Js Element)
    (textContent : @& Lean.Vir.Js.Nullable String) :
    DomM Unit :=
  setTextContentJs element textContent

end Element

end Lean.Vir.Browser
