/-
Copyright (c) 2026 Lean FRO LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Author: Emilio J. Gallego Arias
-/

-- Generated by scripts/bindings/generate-lean-bindings.mjs. Do not edit.

module

public import Vir.Infoview.Panel.Types
public import Vir.React.Types

public section

namespace Lean.Vir

namespace Infoview

/--
Generated binding for reviewed VIR protocol `infoview.interactiveCode`.

Returns the exact public upstream InteractiveCode function for React composition, not a Lean-callable render action. Supply native props with the required fmt field; the enclosing infoview owns its contexts.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-infoview-panel-native-v1` (bridge-handle retention): receiver none; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "infoview.interactiveCode"]
opaque interactiveCode : Lean.Vir.RuntimeM (React.FunctionComponent React.Props)

/--
Generated binding for reviewed VIR protocol `infoview.editorContext`.

Returns the exact upstream EditorContext for React.Hooks.useContext.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-infoview-panel-native-v1` (bridge-handle retention): receiver none; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "infoview.editorContext"]
opaque editorContext : Lean.Vir.RuntimeM (Lean.Vir.Js (React.Context Infoview.EditorConnection))

/--
Generated binding for reviewed VIR protocol `infoview.use-rpc-session`.

Calls the actual upstream React hook and returns its exact position-specific RPC session object.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-infoview-panel-native-v1` (bridge-handle retention): receiver none; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "infoview.useRpcSession"]
opaque useRpcSession : Lean.Vir.React.ReactM (Lean.Vir.Js Infoview.RpcSession)

end Infoview

namespace Infoview.CodeWithInfos

/--
Generated binding for reviewed VIR protocol `infoview.code-with-infos.text`.

Projects TaggedText.text when present, otherwise undefined. The native tagged-text union and all nested values remain unchanged.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-infoview-panel-native-v1` (bridge-handle retention): receiver none; code js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "infoview.codeWithInfos.text"]
opaque text
    (code : @& Lean.Vir.Js Infoview.CodeWithInfos) :
    Lean.Vir.RuntimeM (Lean.Vir.Js.UndefinedOr (String))

/--
Generated binding for reviewed VIR protocol `infoview.code-with-infos.append`.

Projects TaggedText.append when present, otherwise undefined. The native tagged-text union and all nested values remain unchanged.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-infoview-panel-native-v1` (bridge-handle retention): receiver none; code js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "infoview.codeWithInfos.append"]
opaque append
    (code : @& Lean.Vir.Js Infoview.CodeWithInfos) :
    Lean.Vir.RuntimeM (Lean.Vir.Js.UndefinedOr (Lean.Vir.Js.Array.Value Infoview.CodeWithInfos))

/--
Generated binding for reviewed VIR protocol `infoview.code-with-infos.tag`.

Projects TaggedText.tag when present, otherwise undefined. The native tagged-text union and all nested values remain unchanged.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-infoview-panel-native-v1` (bridge-handle retention): receiver none; code js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "infoview.codeWithInfos.tag"]
opaque tag
    (code : @& Lean.Vir.Js Infoview.CodeWithInfos) :
    Lean.Vir.RuntimeM (Lean.Vir.Js.UndefinedOr (Lean.Vir.Js.Tuple2.Value Lean.Vir.Js.Any.Value Infoview.CodeWithInfos))

/--
Generated binding for reviewed VIR protocol `infoview.code-with-infos.strip-tags`.

Specializes upstream TaggedText_stripTags to CodeWithInfos and returns its exact JavaScript string result.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-infoview-panel-native-v1` (bridge-handle retention): receiver none; code js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "infoview.codeWithInfos.stripTags"]
opaque stripTags
    (code : @& Lean.Vir.Js Infoview.CodeWithInfos) :
    Lean.Vir.RuntimeM (Lean.Vir.Js String)

end Infoview.CodeWithInfos

namespace Infoview.EditorApi

/--
Generated binding for reviewed VIR protocol `infoview.editorApi.copyToClipboard`.

Returns the native editor clipboard Promise; no browser fallback or Boolean dispatch status.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-infoview-panel-native-v1` (bridge-handle retention): receiver none; api js-resource/borrowed/call; text js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "infoview.editorApi.copyToClipboard"]
opaque copyToClipboard
    (api : @& Lean.Vir.Js Infoview.EditorApi)
    (text : @& Lean.Vir.Js String) :
    Lean.Vir.RuntimeM (Lean.Vir.Js.Promise Unit)

/--
Generated binding for reviewed VIR protocol `infoview.editorApi.insertText`.

Forwards exact text, kind and position or undefined. This upstream optional-position contract treats undefined as absence; not a universal omission equivalence. Returns the exact Promise.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-infoview-panel-native-v1` (bridge-handle retention): receiver none; api js-resource/borrowed/call; text js-resource/borrowed/call; kind js-resource/borrowed/call; position js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "infoview.editorApi.insertText"]
opaque insertText
    (api : @& Lean.Vir.Js Infoview.EditorApi)
    (text : @& Lean.Vir.Js String)
    (kind : @& Lean.Vir.Js Infoview.TextInsertKind)
    (position : @& Lean.Vir.Js.UndefinedOr Infoview.TextDocumentPositionParams) :
    Lean.Vir.RuntimeM (Lean.Vir.Js.Promise Unit)

end Infoview.EditorApi

namespace Infoview.EditorConnection

/--
Generated binding for reviewed VIR protocol `infoview.editorConnection.api`.

Returns the exact native editor API receiver.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-infoview-panel-native-v1` (bridge-handle retention): receiver none; connection js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "infoview.editorConnection.api"]
opaque api
    (connection : @& Lean.Vir.Js Infoview.EditorConnection) :
    Lean.Vir.RuntimeM (Lean.Vir.Js Infoview.EditorApi)

/--
Generated binding for reviewed VIR protocol `infoview.editorConnection.revealPosition`.

Calls the native method with exact receiver and position; returns its Promise without handling rejection.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-infoview-panel-native-v1` (bridge-handle retention): receiver none; connection js-resource/borrowed/call; position js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "infoview.editorConnection.revealPosition"]
opaque revealPosition
    (connection : @& Lean.Vir.Js Infoview.EditorConnection)
    (position : @& Lean.Vir.Js Infoview.PanelPosition) :
    Lean.Vir.RuntimeM (Lean.Vir.Js.Promise Unit)

end Infoview.EditorConnection

namespace Infoview.HoverDom

/--
Generated binding for reviewed VIR protocol `infoview.hover.modifier`.

Forwards a PointerEvent or KeyboardEvent receiver and key to getModifierState.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-infoview-panel-native-v1` (bridge-handle retention): receiver none; event js-resource/borrowed/call; key js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "infoview.hover.modifier"]
opaque modifier
    (event : @& Lean.Vir.Js Browser.Event)
    (key : @& Lean.Vir.Js String) :
    Lean.Vir.Browser.DomM (Lean.Vir.Js Bool)

/--
Generated binding for reviewed VIR protocol `infoview.hover.rect`.

Returns the exact DOMRect from Element.getBoundingClientRect; placement policy remains in Lean.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-infoview-panel-native-v1` (bridge-handle retention): receiver none; element js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "infoview.hover.rect"]
opaque rect
    (element : @& Lean.Vir.Js Browser.Element) :
    Lean.Vir.Browser.DomM (Lean.Vir.Js Infoview.HoverRect)

/--
Generated binding for reviewed VIR protocol `infoview.hover.portal`.

Calls ReactDOM.createPortal with the exact node and the embedding document.body as the selected container; no hover behavior is implemented by the host.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-infoview-panel-native-v1` (bridge-handle retention): receiver none; node js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "infoview.hover.portal"]
opaque portal
    (node : @& Lean.Vir.Js React.Node) :
    Lean.Vir.React.ReactM (Lean.Vir.Js React.Node)

/--
Generated binding for reviewed VIR protocol `infoview.hover.observe`.

Observes reference/popup size and viewport scroll/resize. The exact callback performs Lean placement; returned native cleanup disconnects observers/listeners.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-infoview-panel-native-v1` (bridge-handle retention): receiver none; reference js-resource/borrowed/call; popup js-resource/borrowed/call; callback js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "infoview.hover.observe"]
opaque observe
    (reference : @& Lean.Vir.Js Browser.Element)
    (popup : @& Lean.Vir.Js Browser.Element)
    (callback : @& Lean.Vir.Js.Function1 Lean.Vir.Js.Any Unit) :
    Lean.Vir.Browser.DomM (Lean.Vir.Js.Function1 Lean.Vir.Js.Any Unit)

end Infoview.HoverDom

namespace Infoview.InfoPopup

/--
Generated binding for reviewed VIR protocol `infoview.info-popup.type`.

Returns exact optional InfoPopup.type, preserving tagged code and undefined.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-infoview-panel-native-v1` (bridge-handle retention): receiver none; popup js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "infoview.infoPopup.type"]
opaque type
    (popup : @& Lean.Vir.Js Infoview.InfoPopup) :
    Lean.Vir.RuntimeM (Lean.Vir.Js.UndefinedOr (Infoview.CodeWithInfos))

/--
Generated binding for reviewed VIR protocol `infoview.info-popup.expr-explicit`.

Returns exact optional InfoPopup.exprExplicit, preserving tagged code and undefined.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-infoview-panel-native-v1` (bridge-handle retention): receiver none; popup js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "infoview.infoPopup.exprExplicit"]
opaque exprExplicit
    (popup : @& Lean.Vir.Js Infoview.InfoPopup) :
    Lean.Vir.RuntimeM (Lean.Vir.Js.UndefinedOr (Infoview.CodeWithInfos))

end Infoview.InfoPopup

namespace Infoview.InteractiveGoal

/--
Generated binding for reviewed VIR protocol `infoview.interactive-goal.hyps`.

Returns InteractiveGoal.hyps as its exact native array.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-infoview-panel-native-v1` (bridge-handle retention): receiver none; goal js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "infoview.interactiveGoal.hyps"]
opaque hyps
    (goal : @& Lean.Vir.Js Infoview.InteractiveGoal) :
    Lean.Vir.RuntimeM (Lean.Vir.Js.Array Infoview.InteractiveHypothesisBundle)

/--
Generated binding for reviewed VIR protocol `infoview.interactive-goal.type`.

Returns the exact InteractiveGoal.type tagged-text value.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-infoview-panel-native-v1` (bridge-handle retention): receiver none; goal js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "infoview.interactiveGoal.type"]
opaque type
    (goal : @& Lean.Vir.Js Infoview.InteractiveGoal) :
    Lean.Vir.RuntimeM (Lean.Vir.Js Infoview.CodeWithInfos)

/--
Generated binding for reviewed VIR protocol `infoview.interactive-goal.user-name`.

Returns the exact optional InteractiveGoal.userName value, retaining undefined.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-infoview-panel-native-v1` (bridge-handle retention): receiver none; goal js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "infoview.interactiveGoal.userName"]
opaque userName
    (goal : @& Lean.Vir.Js Infoview.InteractiveGoal) :
    Lean.Vir.RuntimeM (Lean.Vir.Js.UndefinedOr String)

/--
Generated binding for reviewed VIR protocol `infoview.interactive-goal.mvar-id`.

Returns the exact optional InteractiveGoal.mvarId value, retaining undefined.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-infoview-panel-native-v1` (bridge-handle retention): receiver none; goal js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "infoview.interactiveGoal.mvarId"]
opaque mvarId
    (goal : @& Lean.Vir.Js Infoview.InteractiveGoal) :
    Lean.Vir.RuntimeM (Lean.Vir.Js.UndefinedOr String)

/--
Generated binding for reviewed VIR protocol `infoview.interactive-goal.is-inserted`.

Returns the exact optional InteractiveGoal.isInserted value, retaining undefined.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-infoview-panel-native-v1` (bridge-handle retention): receiver none; goal js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "infoview.interactiveGoal.isInserted"]
opaque isInserted
    (goal : @& Lean.Vir.Js Infoview.InteractiveGoal) :
    Lean.Vir.RuntimeM (Lean.Vir.Js.UndefinedOr Bool)

/--
Generated binding for reviewed VIR protocol `infoview.interactive-goal.is-removed`.

Returns the exact optional InteractiveGoal.isRemoved value, retaining undefined.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-infoview-panel-native-v1` (bridge-handle retention): receiver none; goal js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "infoview.interactiveGoal.isRemoved"]
opaque isRemoved
    (goal : @& Lean.Vir.Js Infoview.InteractiveGoal) :
    Lean.Vir.RuntimeM (Lean.Vir.Js.UndefinedOr Bool)

/--
Generated binding for reviewed VIR protocol `infoview.interactive-goal.goal-prefix`.

Returns the exact optional InteractiveGoal.goalPrefix value, retaining undefined.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-infoview-panel-native-v1` (bridge-handle retention): receiver none; goal js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "infoview.interactiveGoal.goalPrefix"]
opaque goalPrefix
    (goal : @& Lean.Vir.Js Infoview.InteractiveGoal) :
    Lean.Vir.RuntimeM (Lean.Vir.Js.UndefinedOr String)

end Infoview.InteractiveGoal

namespace Infoview.InteractiveHypothesisBundle

/--
Generated binding for reviewed VIR protocol `infoview.interactive-hypothesis-bundle.names`.

Returns InteractiveHypothesisBundle.names as its exact native array.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-infoview-panel-native-v1` (bridge-handle retention): receiver none; hypothesis js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "infoview.interactiveHypothesisBundle.names"]
opaque names
    (hypothesis : @& Lean.Vir.Js Infoview.InteractiveHypothesisBundle) :
    Lean.Vir.RuntimeM (Lean.Vir.Js.Array String)

/--
Generated binding for reviewed VIR protocol `infoview.interactive-hypothesis-bundle.type`.

Returns the exact InteractiveHypothesisBundle.type tagged-text value.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-infoview-panel-native-v1` (bridge-handle retention): receiver none; hypothesis js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "infoview.interactiveHypothesisBundle.type"]
opaque type
    (hypothesis : @& Lean.Vir.Js Infoview.InteractiveHypothesisBundle) :
    Lean.Vir.RuntimeM (Lean.Vir.Js Infoview.CodeWithInfos)

/--
Generated binding for reviewed VIR protocol `infoview.interactive-hypothesis-bundle.val`.

Returns the exact optional InteractiveHypothesisBundle.val tagged-text value, retaining undefined.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-infoview-panel-native-v1` (bridge-handle retention): receiver none; hypothesis js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "infoview.interactiveHypothesisBundle.val"]
opaque val
    (hypothesis : @& Lean.Vir.Js Infoview.InteractiveHypothesisBundle) :
    Lean.Vir.RuntimeM (Lean.Vir.Js.UndefinedOr Infoview.CodeWithInfos)

/--
Generated binding for reviewed VIR protocol `infoview.interactive-hypothesis-bundle.is-type`.

Returns the exact optional InteractiveHypothesisBundle.isType value, retaining undefined.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-infoview-panel-native-v1` (bridge-handle retention): receiver none; hypothesis js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "infoview.interactiveHypothesisBundle.isType"]
opaque isType
    (hypothesis : @& Lean.Vir.Js Infoview.InteractiveHypothesisBundle) :
    Lean.Vir.RuntimeM (Lean.Vir.Js.UndefinedOr Bool)

/--
Generated binding for reviewed VIR protocol `infoview.interactive-hypothesis-bundle.is-instance`.

Returns the exact optional InteractiveHypothesisBundle.isInstance value, retaining undefined.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-infoview-panel-native-v1` (bridge-handle retention): receiver none; hypothesis js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "infoview.interactiveHypothesisBundle.isInstance"]
opaque isInstance
    (hypothesis : @& Lean.Vir.Js Infoview.InteractiveHypothesisBundle) :
    Lean.Vir.RuntimeM (Lean.Vir.Js.UndefinedOr Bool)

/--
Generated binding for reviewed VIR protocol `infoview.interactive-hypothesis-bundle.is-inserted`.

Returns the exact optional InteractiveHypothesisBundle.isInserted value, retaining undefined.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-infoview-panel-native-v1` (bridge-handle retention): receiver none; hypothesis js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "infoview.interactiveHypothesisBundle.isInserted"]
opaque isInserted
    (hypothesis : @& Lean.Vir.Js Infoview.InteractiveHypothesisBundle) :
    Lean.Vir.RuntimeM (Lean.Vir.Js.UndefinedOr Bool)

/--
Generated binding for reviewed VIR protocol `infoview.interactive-hypothesis-bundle.is-removed`.

Returns the exact optional InteractiveHypothesisBundle.isRemoved value, retaining undefined.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-infoview-panel-native-v1` (bridge-handle retention): receiver none; hypothesis js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "infoview.interactiveHypothesisBundle.isRemoved"]
opaque isRemoved
    (hypothesis : @& Lean.Vir.Js Infoview.InteractiveHypothesisBundle) :
    Lean.Vir.RuntimeM (Lean.Vir.Js.UndefinedOr Bool)

end Infoview.InteractiveHypothesisBundle

namespace Infoview.InteractiveTermGoal

/--
Generated binding for reviewed VIR protocol `infoview.interactive-term-goal.hyps`.

Returns InteractiveTermGoal.hyps as its exact native array.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-infoview-panel-native-v1` (bridge-handle retention): receiver none; goal js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "infoview.interactiveTermGoal.hyps"]
opaque hyps
    (goal : @& Lean.Vir.Js Infoview.InteractiveTermGoal) :
    Lean.Vir.RuntimeM (Lean.Vir.Js.Array Infoview.InteractiveHypothesisBundle)

/--
Generated binding for reviewed VIR protocol `infoview.interactive-term-goal.type`.

Returns the exact InteractiveTermGoal.type tagged-text value.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-infoview-panel-native-v1` (bridge-handle retention): receiver none; goal js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "infoview.interactiveTermGoal.type"]
opaque type
    (goal : @& Lean.Vir.Js Infoview.InteractiveTermGoal) :
    Lean.Vir.RuntimeM (Lean.Vir.Js Infoview.CodeWithInfos)

end Infoview.InteractiveTermGoal

namespace Infoview.PanelPosition

/--
Generated binding for reviewed VIR protocol `infoview.panelPosition.toTdpp`.

Delegates to upstream DocumentPosition.toTdpp without a VIR position record.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-infoview-panel-native-v1` (bridge-handle retention): receiver none; position js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "infoview.panelPosition.toTdpp"]
opaque toTdpp
    (position : @& Lean.Vir.Js Infoview.PanelPosition) :
    Lean.Vir.RuntimeM (Lean.Vir.Js Infoview.TextDocumentPositionParams)

/--
Generated binding for reviewed VIR protocol `infoview.panel-position.uri`.

Returns the exact DocumentPosition.uri string.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-infoview-panel-native-v1` (bridge-handle retention): receiver none; position js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "infoview.panelPosition.uri"]
opaque uri
    (position : @& Lean.Vir.Js Infoview.PanelPosition) :
    Lean.Vir.RuntimeM (Lean.Vir.Js String)

/--
Generated binding for reviewed VIR protocol `infoview.panel-position.line`.

Returns the exact native JavaScript number in DocumentPosition.line; it is not narrowed to Nat.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-infoview-panel-native-v1` (bridge-handle retention): receiver none; position js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "infoview.panelPosition.line"]
opaque line
    (position : @& Lean.Vir.Js Infoview.PanelPosition) :
    Lean.Vir.RuntimeM (Lean.Vir.Js Float)

/--
Generated binding for reviewed VIR protocol `infoview.panel-position.character`.

Returns the exact native JavaScript number in DocumentPosition.character; it is not narrowed to Nat.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-infoview-panel-native-v1` (bridge-handle retention): receiver none; position js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "infoview.panelPosition.character"]
opaque character
    (position : @& Lean.Vir.Js Infoview.PanelPosition) :
    Lean.Vir.RuntimeM (Lean.Vir.Js Float)

end Infoview.PanelPosition

namespace Infoview.PanelWidgetProps

/--
Generated binding for reviewed VIR protocol `infoview.panel-widget-props.pos`.

Returns the exact native PanelWidgetProps.pos value without normalizing its document position.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-infoview-panel-native-v1` (bridge-handle retention): receiver none; props js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "infoview.panelWidgetProps.pos"]
opaque pos
    (props : @& Lean.Vir.Js Infoview.PanelWidgetProps) :
    Lean.Vir.RuntimeM (Lean.Vir.Js Infoview.PanelPosition)

/--
Generated binding for reviewed VIR protocol `infoview.panel-widget-props.goals`.

Returns PanelWidgetProps.goals as the exact native array.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-infoview-panel-native-v1` (bridge-handle retention): receiver none; props js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "infoview.panelWidgetProps.goals"]
opaque goals
    (props : @& Lean.Vir.Js Infoview.PanelWidgetProps) :
    Lean.Vir.RuntimeM (Lean.Vir.Js.Array Infoview.InteractiveGoal)

/--
Generated binding for reviewed VIR protocol `infoview.panel-widget-props.term-goal`.

Returns the exact optional PanelWidgetProps.termGoal value, retaining undefined rather than supplying a default.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-infoview-panel-native-v1` (bridge-handle retention): receiver none; props js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "infoview.panelWidgetProps.termGoal"]
opaque termGoal
    (props : @& Lean.Vir.Js Infoview.PanelWidgetProps) :
    Lean.Vir.RuntimeM (Lean.Vir.Js.UndefinedOr Infoview.InteractiveTermGoal)

end Infoview.PanelWidgetProps

namespace Infoview.TextInsertKind

/--
Generated binding for reviewed VIR protocol `infoview.textInsertKind.here`.

Returns the native here string union member.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-infoview-panel-native-v1` (bridge-handle retention): receiver none; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "infoview.textInsertKind.here"]
opaque here : Lean.Vir.RuntimeM (Lean.Vir.Js Infoview.TextInsertKind)

/--
Generated binding for reviewed VIR protocol `infoview.textInsertKind.above`.

Returns the native above string union member.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-infoview-panel-native-v1` (bridge-handle retention): receiver none; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "infoview.textInsertKind.above"]
opaque above : Lean.Vir.RuntimeM (Lean.Vir.Js Infoview.TextInsertKind)

end Infoview.TextInsertKind

end Lean.Vir
