/-
Copyright (c) 2026 Lean FRO LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Author: Emilio J. Gallego Arias
-/

-- Generated by scripts/bindings/generate-lean-bindings.mjs. Do not edit.

module

public import Vir.Infoview.Panel.Types
public import Vir.React.Types

public section

namespace Lean.Vir

namespace Infoview

/--
Generated binding for reviewed VIR protocol `infoview.use-rpc-session`.

Calls the actual upstream React hook and returns its exact position-specific RPC session object.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-infoview-panel-native-v1` (bridge-handle retention): receiver none; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "infoview.useRpcSession"]
opaque useRpcSession : Lean.Vir.React.ReactM (Lean.Vir.Js Infoview.RpcSession)

end Infoview

namespace Infoview.CodeWithInfos

/--
Generated binding for reviewed VIR protocol `infoview.code-with-infos.strip-tags`.

Specializes upstream TaggedText_stripTags to CodeWithInfos and returns its exact JavaScript string result.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-infoview-panel-native-v1` (bridge-handle retention): receiver none; code js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "infoview.codeWithInfos.stripTags"]
opaque stripTags
    (code : @& Lean.Vir.Js Infoview.CodeWithInfos) :
    Lean.Vir.RuntimeM (Lean.Vir.Js String)

end Infoview.CodeWithInfos

namespace Infoview.InteractiveGoal

/--
Generated binding for reviewed VIR protocol `infoview.interactive-goal.hyps`.

Returns InteractiveGoal.hyps as its exact native array.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-infoview-panel-native-v1` (bridge-handle retention): receiver none; goal js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "infoview.interactiveGoal.hyps"]
opaque hyps
    (goal : @& Lean.Vir.Js Infoview.InteractiveGoal) :
    Lean.Vir.RuntimeM (Lean.Vir.Js.Array Infoview.InteractiveHypothesisBundle)

/--
Generated binding for reviewed VIR protocol `infoview.interactive-goal.type`.

Returns the exact InteractiveGoal.type tagged-text value.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-infoview-panel-native-v1` (bridge-handle retention): receiver none; goal js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "infoview.interactiveGoal.type"]
opaque type
    (goal : @& Lean.Vir.Js Infoview.InteractiveGoal) :
    Lean.Vir.RuntimeM (Lean.Vir.Js Infoview.CodeWithInfos)

/--
Generated binding for reviewed VIR protocol `infoview.interactive-goal.user-name`.

Returns the exact optional InteractiveGoal.userName value, retaining undefined.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-infoview-panel-native-v1` (bridge-handle retention): receiver none; goal js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "infoview.interactiveGoal.userName"]
opaque userName
    (goal : @& Lean.Vir.Js Infoview.InteractiveGoal) :
    Lean.Vir.RuntimeM (Lean.Vir.Js.UndefinedOr String)

/--
Generated binding for reviewed VIR protocol `infoview.interactive-goal.mvar-id`.

Returns the exact optional InteractiveGoal.mvarId value, retaining undefined.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-infoview-panel-native-v1` (bridge-handle retention): receiver none; goal js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "infoview.interactiveGoal.mvarId"]
opaque mvarId
    (goal : @& Lean.Vir.Js Infoview.InteractiveGoal) :
    Lean.Vir.RuntimeM (Lean.Vir.Js.UndefinedOr String)

/--
Generated binding for reviewed VIR protocol `infoview.interactive-goal.is-inserted`.

Returns the exact optional InteractiveGoal.isInserted value, retaining undefined.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-infoview-panel-native-v1` (bridge-handle retention): receiver none; goal js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "infoview.interactiveGoal.isInserted"]
opaque isInserted
    (goal : @& Lean.Vir.Js Infoview.InteractiveGoal) :
    Lean.Vir.RuntimeM (Lean.Vir.Js.UndefinedOr Bool)

/--
Generated binding for reviewed VIR protocol `infoview.interactive-goal.is-removed`.

Returns the exact optional InteractiveGoal.isRemoved value, retaining undefined.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-infoview-panel-native-v1` (bridge-handle retention): receiver none; goal js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "infoview.interactiveGoal.isRemoved"]
opaque isRemoved
    (goal : @& Lean.Vir.Js Infoview.InteractiveGoal) :
    Lean.Vir.RuntimeM (Lean.Vir.Js.UndefinedOr Bool)

end Infoview.InteractiveGoal

namespace Infoview.InteractiveHypothesisBundle

/--
Generated binding for reviewed VIR protocol `infoview.interactive-hypothesis-bundle.names`.

Returns InteractiveHypothesisBundle.names as its exact native array.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-infoview-panel-native-v1` (bridge-handle retention): receiver none; hypothesis js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "infoview.interactiveHypothesisBundle.names"]
opaque names
    (hypothesis : @& Lean.Vir.Js Infoview.InteractiveHypothesisBundle) :
    Lean.Vir.RuntimeM (Lean.Vir.Js.Array String)

/--
Generated binding for reviewed VIR protocol `infoview.interactive-hypothesis-bundle.type`.

Returns the exact InteractiveHypothesisBundle.type tagged-text value.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-infoview-panel-native-v1` (bridge-handle retention): receiver none; hypothesis js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "infoview.interactiveHypothesisBundle.type"]
opaque type
    (hypothesis : @& Lean.Vir.Js Infoview.InteractiveHypothesisBundle) :
    Lean.Vir.RuntimeM (Lean.Vir.Js Infoview.CodeWithInfos)

/--
Generated binding for reviewed VIR protocol `infoview.interactive-hypothesis-bundle.val`.

Returns the exact optional InteractiveHypothesisBundle.val tagged-text value, retaining undefined.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-infoview-panel-native-v1` (bridge-handle retention): receiver none; hypothesis js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "infoview.interactiveHypothesisBundle.val"]
opaque val
    (hypothesis : @& Lean.Vir.Js Infoview.InteractiveHypothesisBundle) :
    Lean.Vir.RuntimeM (Lean.Vir.Js.UndefinedOr Infoview.CodeWithInfos)

end Infoview.InteractiveHypothesisBundle

namespace Infoview.InteractiveTermGoal

/--
Generated binding for reviewed VIR protocol `infoview.interactive-term-goal.hyps`.

Returns InteractiveTermGoal.hyps as its exact native array.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-infoview-panel-native-v1` (bridge-handle retention): receiver none; goal js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "infoview.interactiveTermGoal.hyps"]
opaque hyps
    (goal : @& Lean.Vir.Js Infoview.InteractiveTermGoal) :
    Lean.Vir.RuntimeM (Lean.Vir.Js.Array Infoview.InteractiveHypothesisBundle)

/--
Generated binding for reviewed VIR protocol `infoview.interactive-term-goal.type`.

Returns the exact InteractiveTermGoal.type tagged-text value.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-infoview-panel-native-v1` (bridge-handle retention): receiver none; goal js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "infoview.interactiveTermGoal.type"]
opaque type
    (goal : @& Lean.Vir.Js Infoview.InteractiveTermGoal) :
    Lean.Vir.RuntimeM (Lean.Vir.Js Infoview.CodeWithInfos)

end Infoview.InteractiveTermGoal

namespace Infoview.PanelPosition

/--
Generated binding for reviewed VIR protocol `infoview.panel-position.uri`.

Returns the exact DocumentPosition.uri string.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-infoview-panel-native-v1` (bridge-handle retention): receiver none; position js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "infoview.panelPosition.uri"]
opaque uri
    (position : @& Lean.Vir.Js Infoview.PanelPosition) :
    Lean.Vir.RuntimeM (Lean.Vir.Js String)

/--
Generated binding for reviewed VIR protocol `infoview.panel-position.line`.

Returns the exact native JavaScript number in DocumentPosition.line; it is not narrowed to Nat.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-infoview-panel-native-v1` (bridge-handle retention): receiver none; position js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "infoview.panelPosition.line"]
opaque line
    (position : @& Lean.Vir.Js Infoview.PanelPosition) :
    Lean.Vir.RuntimeM (Lean.Vir.Js Float)

/--
Generated binding for reviewed VIR protocol `infoview.panel-position.character`.

Returns the exact native JavaScript number in DocumentPosition.character; it is not narrowed to Nat.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-infoview-panel-native-v1` (bridge-handle retention): receiver none; position js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "infoview.panelPosition.character"]
opaque character
    (position : @& Lean.Vir.Js Infoview.PanelPosition) :
    Lean.Vir.RuntimeM (Lean.Vir.Js Float)

end Infoview.PanelPosition

namespace Infoview.PanelWidgetProps

/--
Generated binding for reviewed VIR protocol `infoview.panel-widget-props.pos`.

Returns the exact native PanelWidgetProps.pos value without normalizing its document position.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-infoview-panel-native-v1` (bridge-handle retention): receiver none; props js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "infoview.panelWidgetProps.pos"]
opaque pos
    (props : @& Lean.Vir.Js Infoview.PanelWidgetProps) :
    Lean.Vir.RuntimeM (Lean.Vir.Js Infoview.PanelPosition)

/--
Generated binding for reviewed VIR protocol `infoview.panel-widget-props.goals`.

Returns PanelWidgetProps.goals as the exact native array.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-infoview-panel-native-v1` (bridge-handle retention): receiver none; props js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "infoview.panelWidgetProps.goals"]
opaque goals
    (props : @& Lean.Vir.Js Infoview.PanelWidgetProps) :
    Lean.Vir.RuntimeM (Lean.Vir.Js.Array Infoview.InteractiveGoal)

/--
Generated binding for reviewed VIR protocol `infoview.panel-widget-props.term-goal`.

Returns the exact optional PanelWidgetProps.termGoal value, retaining undefined rather than supplying a default.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-infoview-panel-native-v1` (bridge-handle retention): receiver none; props js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "infoview.panelWidgetProps.termGoal"]
opaque termGoal
    (props : @& Lean.Vir.Js Infoview.PanelWidgetProps) :
    Lean.Vir.RuntimeM (Lean.Vir.Js.UndefinedOr Infoview.InteractiveTermGoal)

end Infoview.PanelWidgetProps

end Lean.Vir
