/*
Copyright (c) 2026 Lean FRO LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Author: Emilio J. Gallego Arias
*/

#include "decl_provider.h"

#include <stdint.h>

#include "runtime/io.h"
#include "runtime/object.h"

extern "C" {
lean::object * vir_js_call_objects(uint32_t slot, lean::object ** argv, uint32_t argc);
}

namespace lean {
namespace {

static void cleanup_object_args(uint32_t argc, object ** args) {
    if (args == nullptr) {
        return;
    }
    for (uint32_t i = 0; i < argc; i++) {
        lean_dec(args[i]);
    }
}

static object * default_host_import_result(bool is_io) {
    return is_io ? lean_io_result_mk_ok(lean_box(0)) : lean_box(0);
}

static object * call_js_import(uint32_t slot, uint32_t argc, object ** args) {
    bool is_io = vir::host_import_is_io(slot);
    uint32_t arity = vir::host_import_arity(slot);
    uint32_t erased_prefix_args = vir::host_import_erased_prefix_args(slot);
    uint32_t effect_args = is_io ? 1 : 0;
    if (arity < erased_prefix_args || arity - erased_prefix_args < effect_args || argc != arity) {
        cleanup_object_args(argc, args);
        return default_host_import_result(is_io);
    }
    uint32_t js_argc = arity - erased_prefix_args - effect_args;
    object * value = vir_js_call_objects(
        slot,
        args == nullptr ? nullptr : args + erased_prefix_args,
        js_argc);
    // JavaScript records host exceptions out of band and consumes them at the
    // owning top-level or closure call. Keep the interpreter result structurally
    // valid until that boundary reports the recorded exception.
    if (value == nullptr) {
        value = lean_box(0);
    }
    cleanup_object_args(argc, args);
    if (is_io) {
        return lean_io_result_mk_ok(value);
    }
    return value;
}

#define VIR_JS_TRAMPOLINES_FOR_SLOT(SLOT) \
extern "C" object * vir_js_import_slot_##SLOT##_0(void) { \
    return call_js_import(SLOT, 0, nullptr); \
} \
extern "C" object * vir_js_import_slot_##SLOT##_1(object * a0) { \
    object * args[] = { a0 }; \
    return call_js_import(SLOT, 1, args); \
} \
extern "C" object * vir_js_import_slot_##SLOT##_2(object * a0, object * a1) { \
    object * args[] = { a0, a1 }; \
    return call_js_import(SLOT, 2, args); \
} \
extern "C" object * vir_js_import_slot_##SLOT##_3(object * a0, object * a1, object * a2) { \
    object * args[] = { a0, a1, a2 }; \
    return call_js_import(SLOT, 3, args); \
} \
extern "C" object * vir_js_import_slot_##SLOT##_4(object * a0, object * a1, object * a2, object * a3) { \
    object * args[] = { a0, a1, a2, a3 }; \
    return call_js_import(SLOT, 4, args); \
} \
extern "C" object * vir_js_import_slot_##SLOT##_5(object * a0, object * a1, object * a2, object * a3, object * a4) { \
    object * args[] = { a0, a1, a2, a3, a4 }; \
    return call_js_import(SLOT, 5, args); \
} \
extern "C" object * vir_js_import_slot_##SLOT##_6(object * a0, object * a1, object * a2, object * a3, object * a4, object * a5) { \
    object * args[] = { a0, a1, a2, a3, a4, a5 }; \
    return call_js_import(SLOT, 6, args); \
}

VIR_JS_TRAMPOLINES_FOR_SLOT(0)
VIR_JS_TRAMPOLINES_FOR_SLOT(1)
VIR_JS_TRAMPOLINES_FOR_SLOT(2)
VIR_JS_TRAMPOLINES_FOR_SLOT(3)
VIR_JS_TRAMPOLINES_FOR_SLOT(4)
VIR_JS_TRAMPOLINES_FOR_SLOT(5)
VIR_JS_TRAMPOLINES_FOR_SLOT(6)
VIR_JS_TRAMPOLINES_FOR_SLOT(7)
VIR_JS_TRAMPOLINES_FOR_SLOT(8)
VIR_JS_TRAMPOLINES_FOR_SLOT(9)
VIR_JS_TRAMPOLINES_FOR_SLOT(10)
VIR_JS_TRAMPOLINES_FOR_SLOT(11)
VIR_JS_TRAMPOLINES_FOR_SLOT(12)
VIR_JS_TRAMPOLINES_FOR_SLOT(13)
VIR_JS_TRAMPOLINES_FOR_SLOT(14)
VIR_JS_TRAMPOLINES_FOR_SLOT(15)
VIR_JS_TRAMPOLINES_FOR_SLOT(16)
VIR_JS_TRAMPOLINES_FOR_SLOT(17)
VIR_JS_TRAMPOLINES_FOR_SLOT(18)
VIR_JS_TRAMPOLINES_FOR_SLOT(19)
VIR_JS_TRAMPOLINES_FOR_SLOT(20)
VIR_JS_TRAMPOLINES_FOR_SLOT(21)
VIR_JS_TRAMPOLINES_FOR_SLOT(22)
VIR_JS_TRAMPOLINES_FOR_SLOT(23)
VIR_JS_TRAMPOLINES_FOR_SLOT(24)
VIR_JS_TRAMPOLINES_FOR_SLOT(25)
VIR_JS_TRAMPOLINES_FOR_SLOT(26)
VIR_JS_TRAMPOLINES_FOR_SLOT(27)
VIR_JS_TRAMPOLINES_FOR_SLOT(28)
VIR_JS_TRAMPOLINES_FOR_SLOT(29)
VIR_JS_TRAMPOLINES_FOR_SLOT(30)
VIR_JS_TRAMPOLINES_FOR_SLOT(31)
VIR_JS_TRAMPOLINES_FOR_SLOT(32)
VIR_JS_TRAMPOLINES_FOR_SLOT(33)
VIR_JS_TRAMPOLINES_FOR_SLOT(34)
VIR_JS_TRAMPOLINES_FOR_SLOT(35)
VIR_JS_TRAMPOLINES_FOR_SLOT(36)
VIR_JS_TRAMPOLINES_FOR_SLOT(37)
VIR_JS_TRAMPOLINES_FOR_SLOT(38)
VIR_JS_TRAMPOLINES_FOR_SLOT(39)
VIR_JS_TRAMPOLINES_FOR_SLOT(40)
VIR_JS_TRAMPOLINES_FOR_SLOT(41)
VIR_JS_TRAMPOLINES_FOR_SLOT(42)
VIR_JS_TRAMPOLINES_FOR_SLOT(43)
VIR_JS_TRAMPOLINES_FOR_SLOT(44)
VIR_JS_TRAMPOLINES_FOR_SLOT(45)
VIR_JS_TRAMPOLINES_FOR_SLOT(46)
VIR_JS_TRAMPOLINES_FOR_SLOT(47)
VIR_JS_TRAMPOLINES_FOR_SLOT(48)
VIR_JS_TRAMPOLINES_FOR_SLOT(49)
VIR_JS_TRAMPOLINES_FOR_SLOT(50)
VIR_JS_TRAMPOLINES_FOR_SLOT(51)
VIR_JS_TRAMPOLINES_FOR_SLOT(52)
VIR_JS_TRAMPOLINES_FOR_SLOT(53)
VIR_JS_TRAMPOLINES_FOR_SLOT(54)
VIR_JS_TRAMPOLINES_FOR_SLOT(55)
VIR_JS_TRAMPOLINES_FOR_SLOT(56)
VIR_JS_TRAMPOLINES_FOR_SLOT(57)
VIR_JS_TRAMPOLINES_FOR_SLOT(58)
VIR_JS_TRAMPOLINES_FOR_SLOT(59)
VIR_JS_TRAMPOLINES_FOR_SLOT(60)
VIR_JS_TRAMPOLINES_FOR_SLOT(61)
VIR_JS_TRAMPOLINES_FOR_SLOT(62)
VIR_JS_TRAMPOLINES_FOR_SLOT(63)
VIR_JS_TRAMPOLINES_FOR_SLOT(64)
VIR_JS_TRAMPOLINES_FOR_SLOT(65)
VIR_JS_TRAMPOLINES_FOR_SLOT(66)
VIR_JS_TRAMPOLINES_FOR_SLOT(67)
VIR_JS_TRAMPOLINES_FOR_SLOT(68)
VIR_JS_TRAMPOLINES_FOR_SLOT(69)
VIR_JS_TRAMPOLINES_FOR_SLOT(70)
VIR_JS_TRAMPOLINES_FOR_SLOT(71)
VIR_JS_TRAMPOLINES_FOR_SLOT(72)
VIR_JS_TRAMPOLINES_FOR_SLOT(73)
VIR_JS_TRAMPOLINES_FOR_SLOT(74)
VIR_JS_TRAMPOLINES_FOR_SLOT(75)
VIR_JS_TRAMPOLINES_FOR_SLOT(76)
VIR_JS_TRAMPOLINES_FOR_SLOT(77)
VIR_JS_TRAMPOLINES_FOR_SLOT(78)
VIR_JS_TRAMPOLINES_FOR_SLOT(79)
VIR_JS_TRAMPOLINES_FOR_SLOT(80)
VIR_JS_TRAMPOLINES_FOR_SLOT(81)
VIR_JS_TRAMPOLINES_FOR_SLOT(82)
VIR_JS_TRAMPOLINES_FOR_SLOT(83)
VIR_JS_TRAMPOLINES_FOR_SLOT(84)
VIR_JS_TRAMPOLINES_FOR_SLOT(85)
VIR_JS_TRAMPOLINES_FOR_SLOT(86)
VIR_JS_TRAMPOLINES_FOR_SLOT(87)
VIR_JS_TRAMPOLINES_FOR_SLOT(88)
VIR_JS_TRAMPOLINES_FOR_SLOT(89)
VIR_JS_TRAMPOLINES_FOR_SLOT(90)
VIR_JS_TRAMPOLINES_FOR_SLOT(91)
VIR_JS_TRAMPOLINES_FOR_SLOT(92)
VIR_JS_TRAMPOLINES_FOR_SLOT(93)
VIR_JS_TRAMPOLINES_FOR_SLOT(94)
VIR_JS_TRAMPOLINES_FOR_SLOT(95)
VIR_JS_TRAMPOLINES_FOR_SLOT(96)
VIR_JS_TRAMPOLINES_FOR_SLOT(97)
VIR_JS_TRAMPOLINES_FOR_SLOT(98)
VIR_JS_TRAMPOLINES_FOR_SLOT(99)
VIR_JS_TRAMPOLINES_FOR_SLOT(100)
VIR_JS_TRAMPOLINES_FOR_SLOT(101)
VIR_JS_TRAMPOLINES_FOR_SLOT(102)
VIR_JS_TRAMPOLINES_FOR_SLOT(103)
VIR_JS_TRAMPOLINES_FOR_SLOT(104)
VIR_JS_TRAMPOLINES_FOR_SLOT(105)
VIR_JS_TRAMPOLINES_FOR_SLOT(106)
VIR_JS_TRAMPOLINES_FOR_SLOT(107)
VIR_JS_TRAMPOLINES_FOR_SLOT(108)
VIR_JS_TRAMPOLINES_FOR_SLOT(109)
VIR_JS_TRAMPOLINES_FOR_SLOT(110)
VIR_JS_TRAMPOLINES_FOR_SLOT(111)
VIR_JS_TRAMPOLINES_FOR_SLOT(112)
VIR_JS_TRAMPOLINES_FOR_SLOT(113)
VIR_JS_TRAMPOLINES_FOR_SLOT(114)
VIR_JS_TRAMPOLINES_FOR_SLOT(115)
VIR_JS_TRAMPOLINES_FOR_SLOT(116)
VIR_JS_TRAMPOLINES_FOR_SLOT(117)
VIR_JS_TRAMPOLINES_FOR_SLOT(118)
VIR_JS_TRAMPOLINES_FOR_SLOT(119)
VIR_JS_TRAMPOLINES_FOR_SLOT(120)
VIR_JS_TRAMPOLINES_FOR_SLOT(121)
VIR_JS_TRAMPOLINES_FOR_SLOT(122)
VIR_JS_TRAMPOLINES_FOR_SLOT(123)
VIR_JS_TRAMPOLINES_FOR_SLOT(124)
VIR_JS_TRAMPOLINES_FOR_SLOT(125)
VIR_JS_TRAMPOLINES_FOR_SLOT(126)
VIR_JS_TRAMPOLINES_FOR_SLOT(127)

#undef VIR_JS_TRAMPOLINES_FOR_SLOT

#define VIR_JS_TRAMPOLINE_CASE(SLOT, ARITY) \
    if (slot == SLOT && arity == ARITY) { \
        return reinterpret_cast<void *>(vir_js_import_slot_##SLOT##_##ARITY); \
    }

#define VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(SLOT) \
    VIR_JS_TRAMPOLINE_CASE(SLOT, 0) \
    VIR_JS_TRAMPOLINE_CASE(SLOT, 1) \
    VIR_JS_TRAMPOLINE_CASE(SLOT, 2) \
    VIR_JS_TRAMPOLINE_CASE(SLOT, 3) \
    VIR_JS_TRAMPOLINE_CASE(SLOT, 4) \
    VIR_JS_TRAMPOLINE_CASE(SLOT, 5) \
    VIR_JS_TRAMPOLINE_CASE(SLOT, 6)

static void * host_import_trampoline_for(uint32_t slot, uint32_t arity) {
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(0)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(1)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(2)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(3)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(4)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(5)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(6)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(7)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(8)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(9)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(10)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(11)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(12)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(13)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(14)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(15)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(16)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(17)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(18)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(19)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(20)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(21)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(22)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(23)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(24)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(25)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(26)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(27)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(28)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(29)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(30)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(31)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(32)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(33)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(34)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(35)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(36)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(37)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(38)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(39)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(40)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(41)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(42)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(43)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(44)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(45)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(46)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(47)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(48)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(49)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(50)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(51)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(52)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(53)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(54)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(55)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(56)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(57)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(58)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(59)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(60)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(61)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(62)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(63)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(64)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(65)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(66)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(67)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(68)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(69)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(70)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(71)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(72)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(73)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(74)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(75)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(76)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(77)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(78)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(79)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(80)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(81)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(82)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(83)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(84)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(85)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(86)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(87)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(88)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(89)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(90)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(91)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(92)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(93)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(94)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(95)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(96)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(97)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(98)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(99)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(100)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(101)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(102)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(103)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(104)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(105)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(106)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(107)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(108)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(109)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(110)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(111)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(112)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(113)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(114)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(115)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(116)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(117)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(118)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(119)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(120)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(121)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(122)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(123)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(124)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(125)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(126)
    VIR_JS_TRAMPOLINE_CASES_FOR_SLOT(127)
    return nullptr;
}

#undef VIR_JS_TRAMPOLINE_CASES_FOR_SLOT
#undef VIR_JS_TRAMPOLINE_CASE

} // namespace

namespace vir {

void * host_import_trampoline(char const * symbol) {
    int32_t slot = host_import_slot_for_symbol(symbol);
    if (slot < 0) {
        return nullptr;
    }
    return host_import_trampoline_for(
        static_cast<uint32_t>(slot),
        host_import_arity(static_cast<uint32_t>(slot)));
}

} // namespace vir
} // namespace lean
