/*
Generated by `node scripts/check-ir-codec-tags.mjs --write`.
Source of truth: `scripts/ir-codec-tags.mjs`.
*/

#pragma once

#include <stdint.h>

namespace lean::vir::package_ir_tags {

enum class name_tag : uint8_t {
    Anonymous = 0,
    String = 1,
    Numeral = 2,
};

enum class ir_type_tag : uint8_t {
    Float = 0,
    UInt8 = 1,
    UInt16 = 2,
    UInt32 = 3,
    UInt64 = 4,
    USize = 5,
    Erased = 6,
    Object = 7,
    TObject = 8,
    Float32 = 9,
    Tagged = 12,
    Void = 13,
};

enum class arg_tag : uint8_t {
    Var = 0,
    Erased = 1,
};

enum class literal_tag : uint8_t {
    Num = 0,
    String = 1,
};

enum class expr_tag : uint8_t {
    Ctor = 0,
    Reset = 1,
    Reuse = 2,
    Proj = 3,
    UProj = 4,
    SProj = 5,
    Fap = 6,
    Pap = 7,
    Ap = 8,
    Box = 9,
    Unbox = 10,
    Lit = 11,
    IsShared = 12,
};

enum class alt_tag : uint8_t {
    Ctor = 0,
    Default = 1,
};

enum class body_tag : uint8_t {
    VDecl = 0,
    JDecl = 1,
    Set = 2,
    SetTag = 3,
    USet = 4,
    SSet = 5,
    Inc = 6,
    Dec = 7,
    Del = 8,
    Case = 9,
    Ret = 10,
    Jmp = 11,
    Unreachable = 12,
};

enum class decl_tag : uint8_t {
    Fun = 0,
    Extern = 1,
};

} // namespace lean::vir::package_ir_tags
