/-
Copyright (c) 2026 Lean FRO LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Author: Emilio J. Gallego Arias
-/

-- Generated by scripts/bindings/generate-lean-bindings.mjs. Do not edit.

module

public import Vir.Browser.Types
public import Vir.ProofWidgets.Rpc.Types

public section

namespace Lean.Vir

namespace ProofWidgets

/--
Generated binding for reviewed VIR protocol `proofwidgets.rpc.ref-base`.

Constructs the base host-side ProofWidgets reference descriptor from explicit JavaScript strings.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-proofwidgets-protocol-v1`: receiver none; id js-resource/borrowed/call; label js-resource/borrowed/call; typeName js-resource/borrowed/call; summary js-resource/borrowed/call; expression js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "proofwidgets.rpc.ref"]
opaque rpcRefBaseJs
    (id : @& Lean.Vir.Js String)
    (label : @& Lean.Vir.Js String)
    (typeName : @& Lean.Vir.Js String)
    (summary : @& Lean.Vir.Js String)
    (expression : @& Lean.Vir.Js String) :
    Lean.Vir.RuntimeM (Lean.Vir.Js ProofWidgets.RpcRef)

/--
Generated binding for reviewed VIR protocol `proofwidgets.rpc.ref-finish`.

Completes a host-side ProofWidgets reference with optional server state and contextual text.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-proofwidgets-protocol-v1`: receiver none; ref js-resource/borrowed/call; typeText js-resource/borrowed/call; context js-resource/borrowed/call; serverRef js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "proofwidgets.rpc.ref.finish"]
opaque rpcRefFinishJs
    (ref : @& Lean.Vir.Js ProofWidgets.RpcRef)
    (typeText : @& Lean.Vir.Js String)
    (context : @& Lean.Vir.Js String)
    (serverRef : @& Lean.Vir.Js.Nullable ProofWidgets.ServerRef) :
    Lean.Vir.RuntimeM (Lean.Vir.Js ProofWidgets.RpcRef)

end ProofWidgets

namespace ProofWidgets.Rpc

/--
Generated binding for reviewed VIR protocol `proofwidgets.rpc.resolved-value`.

Explicitly decodes the fixed ResolvedRef record returned by the ProofWidgets host protocol.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-proofwidgets-protocol-v1`: receiver none; ref js-resource/borrowed/call; result lean-owned/value.

This declaration is generated; edit the binding configuration.
-/
@[vir_js_explicit_conversion "js.value.proofwidgets.resolvedRef.value"]
opaque resolvedRefValueJs
    (ref : @& Lean.Vir.Js ProofWidgets.ResolvedRef) :
    Lean.Vir.RuntimeM (ProofWidgets.ResolvedRef)

/--
Generated binding for reviewed VIR protocol `proofwidgets.rpc.inspect`.

Asks the host whether a ProofWidgets reference can be inspected.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-proofwidgets-protocol-v1`: receiver none; ref js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "proofwidgets.rpc.inspectRef"]
opaque inspectRefJs
    (ref : @& Lean.Vir.Js ProofWidgets.RpcRef) :
    Lean.Vir.Browser.DomM (Lean.Vir.Js Bool)

/--
Generated binding for reviewed VIR protocol `proofwidgets.rpc.resolve`.

Starts a one-shot host resolution and retains the callback until resolution or runtime disposal.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-proofwidgets-protocol-v1`: receiver none; ref js-resource/borrowed/call; callback callback/owned/until-release; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "proofwidgets.rpc.resolveRef"]
opaque resolveRefJs
    (ref : @& Lean.Vir.Js ProofWidgets.RpcRef)
    (callback : Lean.Vir.Js ProofWidgets.ResolvedRef → Lean.Vir.Browser.DomM Unit) :
    Lean.Vir.Browser.DomM (Lean.Vir.Js Bool)

end ProofWidgets.Rpc

end Lean.Vir
