/-
Copyright (c) 2026 Lean FRO LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Author: Emilio J. Gallego Arias
-/

-- Generated by scripts/bindings/generate-lean-bindings.mjs. Do not edit.

module

public import Vir.Browser.Types
public import Vir.Infoview.Surface.Types

public section

namespace Lean.Vir

namespace Infoview

/--
Generated binding for reviewed VIR protocol `infoview.document-position`.

Constructs the fixed host-side document-position record used by editor commands.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-infoview-protocol-v1`: receiver none; uri js-resource/borrowed/call; fileName js-resource/borrowed/call; line js-resource/borrowed/call; character js-resource/borrowed/call; label js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "infoview.documentPosition"]
opaque documentPositionJs
    (uri : @& Lean.Vir.Js String)
    (fileName : @& Lean.Vir.Js String)
    (line : @& Lean.Vir.Js Nat)
    (character : @& Lean.Vir.Js Nat)
    (label : @& Lean.Vir.Js String) :
    Lean.Vir.RuntimeM (Lean.Vir.Js Infoview.DocumentPosition)

end Infoview

namespace Infoview.Clipboard

/--
Generated binding for reviewed VIR protocol `infoview.clipboard.write-text`.

Implements the local synchronous infoview clipboard capability. It returns false when no copy request can be dispatched, true after synchronous copy or native async dispatch, and reports a later Promise rejection through the host error channel.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-infoview-protocol-v1`: receiver none; text js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "infoview.clipboard.writeText"]
opaque writeTextJs
    (text : @& Lean.Vir.Js String) :
    Lean.Vir.Browser.DomM (Lean.Vir.Js Bool)

end Infoview.Clipboard

namespace Infoview.Command

/--
Generated binding for reviewed VIR protocol `infoview.command.reveal`.

Dispatches the local editor reveal-position capability and reports whether a dispatcher handled it.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-infoview-protocol-v1`: receiver none; position js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "infoview.command.revealPosition"]
opaque revealPositionJs
    (position : @& Lean.Vir.Js Infoview.DocumentPosition) :
    Lean.Vir.Browser.DomM (Lean.Vir.Js Bool)

/--
Generated binding for reviewed VIR protocol `infoview.command.insert`.

Dispatches the local editor insert-text capability and reports whether it was applied.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-infoview-protocol-v1`: receiver none; position js-resource/borrowed/call; text js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "infoview.command.insertText"]
opaque insertTextJs
    (position : @& Lean.Vir.Js Infoview.DocumentPosition)
    (text : @& Lean.Vir.Js String) :
    Lean.Vir.Browser.DomM (Lean.Vir.Js Bool)

end Infoview.Command

end Lean.Vir
