/-
Copyright (c) 2026 Lean FRO LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Author: Emilio J. Gallego Arias
-/

-- Generated by scripts/bindings/generate-lean-bindings.mjs. Do not edit.

module

public import Vir.Browser.Types
public import Vir.Infoview.Surface.Types
public import Vir.React.Types

public section

namespace Lean.Vir

namespace Infoview

/--
Generated binding for reviewed VIR protocol `infoview.client-notification-effect-deps`.

Calls the upstream infoview hook with the exact method, native callback and explicit dependency array. The upstream EditorContext and hook own subscription and cleanup; VIR neither queues nor filters notifications.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-infoview-protocol-v1`: receiver none; method js-resource/borrowed/call; callback js-resource/borrowed/call; deps js-resource/borrowed/call; result immediate/value.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "infoview.useClientNotificationEffectWithDeps"]
private opaque useClientNotificationEffectWithDeps
    {params : Type}
    (method : @& Lean.Vir.Js String)
    (callback : @& Lean.Vir.Js.Function1 (Lean.Vir.Js params) Unit)
    (deps : @& Lean.Vir.Js React.DependencyList) :
    Lean.Vir.React.ReactM Unit

/--
Generated binding for reviewed VIR protocol `infoview.client-notification-effect`.

Calls the upstream infoview hook with the exact method and native callback, omitting the optional dependencies argument.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-infoview-protocol-v1`: receiver none; method js-resource/borrowed/call; callback js-resource/borrowed/call; result immediate/value.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "infoview.useClientNotificationEffect"]
private opaque useClientNotificationEffectWithoutDeps
    {params : Type}
    (method : @& Lean.Vir.Js String)
    (callback : @& Lean.Vir.Js.Function1 (Lean.Vir.Js params) Unit) :
    Lean.Vir.React.ReactM Unit

/--
Generated binding for reviewed VIR protocol `infoview.document-position`.

Constructs the fixed host-side document-position record used by editor commands.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-infoview-protocol-v1`: receiver none; uri js-resource/borrowed/call; fileName js-resource/borrowed/call; line js-resource/borrowed/call; character js-resource/borrowed/call; label js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "infoview.documentPosition"]
opaque documentPosition
    (uri : @& Lean.Vir.Js String)
    (fileName : @& Lean.Vir.Js String)
    (line : @& Lean.Vir.Js Nat)
    (character : @& Lean.Vir.Js Nat)
    (label : @& Lean.Vir.Js String) :
    Lean.Vir.RuntimeM (Lean.Vir.Js Infoview.DocumentPosition)

end Infoview

namespace Infoview.ClientRequestOptions

/--
Generated binding for reviewed VIR protocol `infoview.request-options.empty`.

Constructs an ordinary empty ClientRequestOptions object, omitting abortSignal rather than substituting null.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-infoview-protocol-v1`: receiver none; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "infoview.clientRequestOptions.empty"]
opaque empty : Lean.Vir.RuntimeM (Lean.Vir.Js Infoview.ClientRequestOptions)

/--
Generated binding for reviewed VIR protocol `infoview.request-options.abort-signal`.

Assigns the exact native AbortSignal to options.abortSignal without wrapping the signal or changing cancellation behavior.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-infoview-protocol-v1`: receiver none; options js-resource/borrowed/call; signal js-resource/borrowed/call; result immediate/value.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "infoview.clientRequestOptions.setAbortSignal"]
opaque setAbortSignal
    (options : @& Lean.Vir.Js Infoview.ClientRequestOptions)
    (signal : @& Lean.Vir.Js Browser.AbortSignal) :
    Lean.Vir.RuntimeM Unit

end Infoview.ClientRequestOptions

namespace Infoview.Clipboard

/--
Generated binding for reviewed VIR protocol `infoview.clipboard.write-text`.

Implements the local synchronous infoview clipboard capability. It returns false when no copy request can be dispatched, true after synchronous copy or native async dispatch, and reports a later Promise rejection through the host error channel.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-infoview-protocol-v1`: receiver none; text js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "infoview.clipboard.writeText"]
opaque writeText
    (text : @& Lean.Vir.Js String) :
    Lean.Vir.Browser.DomM (Lean.Vir.Js Bool)

end Infoview.Clipboard

namespace Infoview.Command

/--
Generated binding for reviewed VIR protocol `infoview.command.reveal`.

Dispatches the local editor reveal-position capability and reports whether a dispatcher handled it.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-infoview-protocol-v1`: receiver none; position js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "infoview.command.revealPosition"]
opaque revealPosition
    (position : @& Lean.Vir.Js Infoview.DocumentPosition) :
    Lean.Vir.Browser.DomM (Lean.Vir.Js Bool)

/--
Generated binding for reviewed VIR protocol `infoview.command.insert`.

Dispatches the local editor insert-text capability and reports whether it was applied.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-infoview-protocol-v1`: receiver none; position js-resource/borrowed/call; text js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "infoview.command.insertText"]
opaque insertText
    (position : @& Lean.Vir.Js Infoview.DocumentPosition)
    (text : @& Lean.Vir.Js String) :
    Lean.Vir.Browser.DomM (Lean.Vir.Js Bool)

end Infoview.Command

namespace Infoview.RpcSession

/--
Generated binding for reviewed VIR protocol `infoview.rpc-session.call`.

Calls the exact position-specific infoview RPC session with the exact method string and request object, omits its optional ClientRequestOptions argument, and returns its native Promise.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-infoview-protocol-v1`: receiver none; session js-resource/borrowed/call; method js-resource/borrowed/call; params js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "infoview.rpcSession.call"]
opaque call
    {params : Type}
    {result : Type}
    (session : @& Lean.Vir.Js Infoview.RpcSession)
    (method : @& Lean.Vir.Js String)
    (params : @& Lean.Vir.Js params) :
    Lean.Vir.RuntimeM (Lean.Vir.Js.Promise result)

/--
Generated binding for reviewed VIR protocol `infoview.rpc-session.call-options`.

Passes the exact ClientRequestOptions and AbortSignal to the position-specific session; params use Js.Any to fit the interpreter arity limit without changing their value. Cancellation and Promise settlement follow the official RPC client and server.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-infoview-protocol-v1`: receiver none; session js-resource/borrowed/call; method js-resource/borrowed/call; params js-resource/borrowed/call; options js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "infoview.rpcSession.callWithOptions"]
opaque callWithOptions
    {result : Type}
    (session : @& Lean.Vir.Js Infoview.RpcSession)
    (method : @& Lean.Vir.Js String)
    (params : @& Lean.Vir.Js.Any)
    (options : @& Lean.Vir.Js Infoview.ClientRequestOptions) :
    Lean.Vir.RuntimeM (Lean.Vir.Js.Promise result)

end Infoview.RpcSession

end Lean.Vir
