/-
Copyright (c) 2026 Lean FRO LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Author: Emilio J. Gallego Arias
-/

-- Generated by scripts/bindings/generate-lean-bindings.mjs. Do not edit.

import Vir.React.Types

namespace Lean.Vir

namespace React.Callback

/--
Generated binding for reviewed VIR protocol `react.callback.of-unary`.

Explicitly converts a transferred Lean unary callback into an ordinary JavaScript function.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-react-protocol-v1`: receiver none; callback callback/owned/until-release; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js_explicit_conversion "js.value.react.callback"]
opaque ofUnary
    {α : Type}
    (callback : Lean.Vir.Js α → Lean.Vir.Browser.DomM Unit) :
    Lean.Vir.RuntimeM (Lean.Vir.Js (Lean.Vir.React.Callback α))

end React.Callback

namespace React.ElementType

/--
Generated binding for reviewed VIR protocol `react.element-type.tag`.

Uses the exact DOM tag string as a React ElementType value.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-react-protocol-v1`: receiver none; tag js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "react.elementType.tag"]
opaque tagJs
    (tag : @& Lean.Vir.Js String) :
    Lean.Vir.React.ReactM (Lean.Vir.Js Lean.Vir.React.ElementType)

end React.ElementType

namespace React.EventHandler

/--
Generated binding for reviewed VIR protocol `react.event-handler.to-js`.

Explicitly lowers an event descriptor to a JavaScript object containing the exact callback function.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-react-protocol-v1`: receiver none; value lean-owned/owned/until-release; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js_explicit_conversion "js.value.react.eventHandler"]
opaque toJs
    (value : Lean.Vir.React.EventHandler) :
    Lean.Vir.RuntimeM (Lean.Vir.Js Lean.Vir.React.EventHandler)

end React.EventHandler

namespace React.Hooks

/--
Generated binding for reviewed VIR protocol `react.hooks.use-reducer`.

Passes the caller's native reducer and initial value unchanged to React.useReducer and returns React's exact result array.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-react-protocol-v1`: receiver none; reducer js-resource/borrowed/call; initial js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "react.useReducer"]
opaque useReducer
    {state : Type}
    {action : Type}
    (reducer : @& Lean.Vir.Js (Lean.Vir.React.Reducer state action))
    (initial : @& Lean.Vir.Js state) :
    Lean.Vir.React.ReactM (Lean.Vir.Js (Lean.Vir.React.ReducerTuple state action))

/--
Generated binding for reviewed VIR protocol `react.hooks.use-state`.

Passes the initial value unchanged to React.useState and returns React's exact result array.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-react-protocol-v1`: receiver none; initial js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "react.useState"]
opaque useState
    {α : Type}
    (initial : @& Lean.Vir.Js α) :
    Lean.Vir.React.ReactM (Lean.Vir.Js (Lean.Vir.React.StateTuple (Lean.Vir.Js α)))

/--
Generated binding for reviewed VIR protocol `react.hooks.use-ref`.

Creates a typed React ref object initialized with a JavaScript-owned value.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-react-protocol-v1`: receiver none; initial js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "react.useRef"]
opaque useRef
    {α : Type}
    (initial : @& Lean.Vir.Js α) :
    Lean.Vir.React.ReactM (Lean.Vir.Js (Lean.Vir.React.Ref (Lean.Vir.Js α)))

/--
Generated binding for reviewed VIR protocol `react.hooks.use-effect`.

Passes the caller's native setup function unchanged to React.useEffect without a dependency argument.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-react-protocol-v1`: receiver none; setup js-resource/borrowed/call; result immediate/value.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "react.useEffect"]
opaque useEffectWithoutDeps
    (setup : @& Lean.Vir.Js Lean.Vir.React.EffectCallback) :
    Lean.Vir.React.ReactM Unit

/--
Generated binding for reviewed VIR protocol `react.hooks.use-lean-effect`.

Explicitly adapts separate transferred Lean setup and cleanup callbacks to React's effect callback shape.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-react-protocol-v1`: receiver none; setup callback/owned/until-release; cleanup callback/owned/until-release; result immediate/value.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "react.useLeanEffect"]
opaque useLeanEffectWithoutDepsJs
    {α : Type}
    (setup : Lean.Vir.Browser.DomM (Lean.Vir.Js α))
    (cleanup : @& Lean.Vir.Js α → Lean.Vir.Browser.DomM Unit) :
    Lean.Vir.React.ReactM Unit

/--
Generated binding for reviewed VIR protocol `react.hooks.use-memo`.

Passes the caller's native calculation function and dependency array unchanged to React.useMemo.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-react-protocol-v1`: receiver none; calculate js-resource/borrowed/call; deps js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "react.useMemo"]
opaque useMemo
    {α : Type}
    (calculate : @& Lean.Vir.Js (Lean.Vir.React.MemoCalculation α))
    (deps : @& Lean.Vir.Js Lean.Vir.React.DependencyList) :
    Lean.Vir.React.ReactM (Lean.Vir.Js α)

/--
Generated binding for reviewed VIR protocol `react.hooks.use-callback`.

Passes the caller's native JavaScript function and dependency array unchanged to React.useCallback and returns React's selected function.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-react-protocol-v1`: receiver none; callback js-resource/borrowed/call; deps js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "react.useCallback"]
opaque useCallback
    {α : Type}
    (callback : @& Lean.Vir.Js (Lean.Vir.React.Callback α))
    (deps : @& Lean.Vir.Js Lean.Vir.React.DependencyList) :
    Lean.Vir.React.ReactM (Lean.Vir.Js (Lean.Vir.React.Callback α))

/--
Generated binding for reviewed VIR protocol `react.hooks.use-context`.

Passes a native React context object unchanged to React.useContext and returns its current JavaScript-owned value.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-react-protocol-v1`: receiver none; context js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "react.useContext"]
opaque useContext
    {α : Type}
    (context : @& Lean.Vir.Js (Lean.Vir.React.Context α)) :
    Lean.Vir.React.ReactM (Lean.Vir.Js α)

/--
Generated binding for reviewed VIR protocol `react.hooks.use-effect-with-deps`.

Passes the caller's native setup function and dependency array unchanged to React.useEffect.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-react-protocol-v1`: receiver none; setup js-resource/borrowed/call; deps js-resource/borrowed/call; result immediate/value.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "react.useEffectWithDeps"]
opaque useEffectWithDeps
    (setup : @& Lean.Vir.Js Lean.Vir.React.EffectCallback)
    (deps : @& Lean.Vir.Js Lean.Vir.React.DependencyList) :
    Lean.Vir.React.ReactM Unit

/--
Generated binding for reviewed VIR protocol `react.hooks.use-lean-effect-with-deps`.

Explicitly adapts separate transferred Lean setup and cleanup callbacks under a native dependency array.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-react-protocol-v1`: receiver none; deps js-resource/borrowed/call; setup callback/owned/until-release; cleanup callback/owned/until-release; result immediate/value.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "react.useLeanEffectWithDeps"]
opaque useLeanEffectWithDepsJs
    {α : Type}
    (deps : @& Lean.Vir.Js Lean.Vir.React.DependencyList)
    (setup : Lean.Vir.Browser.DomM (Lean.Vir.Js α))
    (cleanup : @& Lean.Vir.Js α → Lean.Vir.Browser.DomM Unit) :
    Lean.Vir.React.ReactM Unit

end React.Hooks

namespace React.Hooks.DependencyList

/--
Generated binding for reviewed VIR protocol `react.dependencies.empty`.

Allocates an empty JavaScript dependency list for React hooks.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-react-protocol-v1`: receiver none; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "react.deps.empty"]
opaque empty : Lean.Vir.React.ReactM (Lean.Vir.Js Lean.Vir.React.DependencyList)

/--
Generated binding for reviewed VIR protocol `react.dependencies.push`.

Appends a JavaScript-owned identity value to a hook dependency list.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-react-protocol-v1`: receiver none; deps js-resource/borrowed/call; value js-resource/borrowed/call; result immediate/value.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "react.deps.push"]
opaque push
    {α : Type}
    (deps : @& Lean.Vir.Js Lean.Vir.React.DependencyList)
    (value : @& Lean.Vir.Js α) :
    Lean.Vir.React.ReactM Unit

end React.Hooks.DependencyList

namespace React.MemoCalculation

/--
Generated binding for reviewed VIR protocol `react.memo-calculation.of-lean`.

Explicitly converts a transferred Lean calculation into an ordinary zero-argument JavaScript function.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-react-protocol-v1`: receiver none; calculate callback/owned/until-release; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js_explicit_conversion "js.value.react.memoCalculation"]
opaque ofLean
    {α : Type}
    (calculate : Lean.Vir.React.ReactM (Lean.Vir.Js α)) :
    Lean.Vir.RuntimeM (Lean.Vir.Js (Lean.Vir.React.MemoCalculation α))

end React.MemoCalculation

namespace React.Node

/--
Generated binding for reviewed VIR protocol `react.node.text`.

Uses the exact JavaScript string as a React text node.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-react-protocol-v1`: receiver none; value js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "react.node.text"]
opaque textJs
    (value : @& Lean.Vir.Js String) :
    Lean.Vir.React.ReactM (Lean.Vir.Js Lean.Vir.React.Node)

/--
Generated binding for reviewed VIR protocol `react.node.create-element`.

Calls React.createElement with the exact ElementType, props object, and child array values.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-react-protocol-v1`: receiver none; elementType js-resource/borrowed/call; props js-resource/borrowed/call; children js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "react.node.createElement"]
opaque createElement
    (elementType : @& Lean.Vir.Js Lean.Vir.React.ElementType)
    (props : @& Lean.Vir.Js Lean.Vir.React.Props)
    (children : @& Lean.Vir.Js.Array (Lean.Vir.Js Lean.Vir.React.Node)) :
    Lean.Vir.React.ReactM (Lean.Vir.Js Lean.Vir.React.Node)

/--
Generated binding for reviewed VIR protocol `react.node.component`.

Creates a React element for the explicit Lean-component adapter using a stable component type ID and render callback.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-react-protocol-v1`: receiver none; componentType js-resource/borrowed/call; component callback/owned/until-release; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "react.node.component"]
opaque componentThunkJs
    (componentType : @& Lean.Vir.Js String)
    (component : Unit → Lean.Vir.React.ReactM (Lean.Vir.Js Lean.Vir.React.Node)) :
    Lean.Vir.React.ReactM (Lean.Vir.Js Lean.Vir.React.Node)

/--
Generated binding for reviewed VIR protocol `react.node.keyed-component`.

Creates a keyed React element for the explicit Lean-component adapter using a stable component type ID and render callback.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-react-protocol-v1`: receiver none; componentType js-resource/borrowed/call; component callback/owned/until-release; key js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "react.node.keyedComponent"]
opaque keyedComponentThunkJs
    (componentType : @& Lean.Vir.Js String)
    (component : Unit → Lean.Vir.React.ReactM (Lean.Vir.Js Lean.Vir.React.Node))
    (key : @& Lean.Vir.Js String) :
    Lean.Vir.React.ReactM (Lean.Vir.Js Lean.Vir.React.Node)

/--
Generated binding for reviewed VIR protocol `react.node.fragment`.

Calls React.createElement with React.Fragment, the exact props object, and child array values.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-react-protocol-v1`: receiver none; props js-resource/borrowed/call; children js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "react.node.fragment"]
opaque fragmentWithKeyJs
    (props : @& Lean.Vir.Js Lean.Vir.React.Props)
    (children : @& Lean.Vir.Js.Array (Lean.Vir.Js Lean.Vir.React.Node)) :
    Lean.Vir.React.ReactM (Lean.Vir.Js Lean.Vir.React.Node)

end React.Node

namespace React.Property

/--
Generated binding for reviewed VIR protocol `react.property.to-js`.

Explicitly lowers VIR's reviewed React Property algebra to an ordinary JavaScript descriptor object.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-react-protocol-v1`: receiver none; value lean-owned/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js_explicit_conversion "js.value.react.property"]
opaque toJs
    (value : @& Lean.Vir.React.Property) :
    Lean.Vir.RuntimeM (Lean.Vir.Js Lean.Vir.React.Property)

end React.Property

namespace React.Props

/--
Generated binding for reviewed VIR protocol `react.props.empty`.

Allocates an empty JavaScript React props object.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-react-protocol-v1`: receiver none; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "react.props.empty"]
opaque empty : Lean.Vir.React.ReactM (Lean.Vir.Js Lean.Vir.React.Props)

/--
Generated explicit protocol operation semantic adapter for TypeScript `React.Attributes.key`.

Adapter policy: Sets React's special key field on a JavaScript props object.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-react-protocol-v1`: receiver none; props js-resource/borrowed/call; key js-resource/borrowed/call; result immediate/value.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "react.props.setKey"]
opaque setKeyJs
    (props : @& Lean.Vir.Js Lean.Vir.React.Props)
    (key : @& Lean.Vir.Js String) :
    Lean.Vir.React.ReactM Unit

/--
Generated binding for reviewed VIR protocol `react.props.set-property`.

Installs the reviewed descriptor's exact JavaScript value on the props object.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-react-protocol-v1`: receiver none; props js-resource/borrowed/call; property js-resource/borrowed/call; result immediate/value.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "react.props.setProperty"]
opaque setProperty
    (props : @& Lean.Vir.Js Lean.Vir.React.Props)
    (property : @& Lean.Vir.Js Lean.Vir.React.Property) :
    Lean.Vir.React.ReactM Unit

/--
Generated binding for reviewed VIR protocol `react.props.set-event-handler`.

Installs the descriptor's exact callback function on the JavaScript props object.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-react-protocol-v1`: receiver none; props js-resource/borrowed/call; handler js-resource/borrowed/call; result immediate/value.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "react.props.setEventHandler"]
opaque setEventHandler
    (props : @& Lean.Vir.Js Lean.Vir.React.Props)
    (handler : @& Lean.Vir.Js Lean.Vir.React.EventHandler) :
    Lean.Vir.React.ReactM Unit

/--
Generated binding for reviewed VIR protocol `react.props.set-ref`.

Installs the exact React ref object on a JavaScript props object.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-react-protocol-v1`: receiver none; props js-resource/borrowed/call; ref js-resource/borrowed/call; result immediate/value.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "react.props.setRef"]
opaque setRef
    {α : Type}
    (props : @& Lean.Vir.Js Lean.Vir.React.Props)
    (ref : @& Lean.Vir.Js (Lean.Vir.React.Ref (Lean.Vir.Js α))) :
    Lean.Vir.React.ReactM Unit

end React.Props

namespace React.Reducer

/--
Generated binding for reviewed VIR protocol `react.reducer.of-lean`.

Explicitly converts a transferred Lean reducer callback into an ordinary JavaScript function; React remains responsible for invocation and replay semantics.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-react-protocol-v1`: receiver none; reducer callback/owned/until-release; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js_explicit_conversion "js.value.react.reducer"]
opaque ofLean
    {state : Type}
    {action : Type}
    (reducer : Lean.Vir.Js state → Lean.Vir.Js action → Lean.Vir.RuntimeM (Lean.Vir.Js state)) :
    Lean.Vir.RuntimeM (Lean.Vir.Js (Lean.Vir.React.Reducer state action))

end React.Reducer

namespace React.ReducerDispatch

/--
Generated binding for reviewed VIR protocol `react.reducer.dispatch`.

Passes the exact JavaScript action to React's reducer dispatch function.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-react-protocol-v1`: receiver none; dispatch js-resource/borrowed/call; action js-resource/borrowed/call; result immediate/value.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "react.reducer.dispatch"]
opaque dispatchJs
    {state : Type}
    {action : Type}
    (dispatch : @& Lean.Vir.Js (Lean.Vir.React.ReducerDispatch state action))
    (action : @& Lean.Vir.Js action) :
    Lean.Vir.RuntimeM Unit

end React.ReducerDispatch

namespace React.ReducerTuple

/--
Generated binding for reviewed VIR protocol `react.reducer-tuple.value`.

Projects index zero from the exact JavaScript array returned by React.useReducer.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-react-protocol-v1`: receiver none; result js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "react.reducerTuple.value"]
opaque value
    {state : Type}
    {action : Type}
    (result : @& Lean.Vir.Js (Lean.Vir.React.ReducerTuple state action)) :
    Lean.Vir.RuntimeM (Lean.Vir.Js state)

/--
Generated binding for reviewed VIR protocol `react.reducer-tuple.dispatch`.

Projects the exact native dispatch function from index one of React.useReducer's result array.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-react-protocol-v1`: receiver none; result js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "react.reducerTuple.dispatch"]
opaque dispatch
    {state : Type}
    {action : Type}
    (result : @& Lean.Vir.Js (Lean.Vir.React.ReducerTuple state action)) :
    Lean.Vir.RuntimeM (Lean.Vir.Js (Lean.Vir.React.ReducerDispatch state action))

end React.ReducerTuple

namespace React.Ref

/--
Generated binding for reviewed VIR protocol `react.ref.get`.

Reads the current value from React's exact mutable ref object.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-react-protocol-v1`: receiver none; ref js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "react.ref.get"]
opaque get
    {α : Type}
    (ref : @& Lean.Vir.Js (Lean.Vir.React.Ref (Lean.Vir.Js α))) :
    Lean.Vir.RuntimeM (Lean.Vir.Js α)

/--
Generated binding for reviewed VIR protocol `react.ref.set`.

Writes the exact JavaScript value to React's mutable ref object without scheduling a render.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-react-protocol-v1`: receiver none; ref js-resource/borrowed/call; value js-resource/borrowed/call; result immediate/value.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "react.ref.set"]
opaque set
    {α : Type}
    (ref : @& Lean.Vir.Js (Lean.Vir.React.Ref (Lean.Vir.Js α)))
    (value : @& Lean.Vir.Js α) :
    Lean.Vir.RuntimeM Unit

end React.Ref

namespace React.Root

/--
Generated reviewed method specialization of TypeScript `Root.render`.

Specialization policy: Root rendering is a DOM effect; the exact ReactNode JavaScript value is forwarded without conversion.

Upstream declaration: https://unpkg.com/@types/react-dom@19.2.4/client.d.ts#L62

ABI profile `vir-react-protocol-v1`: root js-resource/borrowed/call; children js-resource/borrowed/call; result immediate/value.

This declaration is generated; edit the TypeScript source or binding configuration.
-/
@[vir_js "react.root.renderNode"]
opaque renderNode
    (root : @& Lean.Vir.Js Lean.Vir.React.Root)
    (children : @& Lean.Vir.Js Lean.Vir.React.Node) :
    Lean.Vir.Browser.DomM Unit

/--
Generated reviewed method specialization of TypeScript `Root.unmount`.

Specialization policy: Unmount is terminal for the Lean root argument: it removes VIR's private active-root record and calls React's root.unmount without revoking JavaScript aliases.

Upstream declaration: https://unpkg.com/@types/react-dom@19.2.4/client.d.ts#L63

ABI profile `vir-react-protocol-v1`: root js-resource/consumed/call; result immediate/value.

This declaration is generated; edit the TypeScript source or binding configuration.
-/
@[vir_js "react.root.unmount"]
opaque unmount
    (root : Lean.Vir.Js Lean.Vir.React.Root) :
    Lean.Vir.Browser.DomM Unit

/--
Generated reviewed function specialization of TypeScript `createRoot`.

createRoot lets you create a root to display React components inside a browser DOM node.

Specialization policy: VIR restricts the TypeScript Container union to Element and uses default RootOptions; within that supported lane it passes the exact container to createRoot and returns the exact Root.

Upstream declaration: https://unpkg.com/@types/react-dom@19.2.4/client.d.ts#L86

ABI profile `vir-react-protocol-v1`: receiver none; container js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the TypeScript source or binding configuration.
-/
@[vir_js "react.root.create"]
opaque create
    (container : @& Lean.Vir.Js Lean.Vir.Browser.Element) :
    Lean.Vir.Browser.DomM (Lean.Vir.Js Lean.Vir.React.Root)

/--
Generated explicit protocol operation semantic adapter for TypeScript `Root.render`.

Adapter policy: Runs a Lean ReactM construction action once and forwards its JavaScript-owned ReactNode to Root.render.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-react-protocol-v1`: receiver none; root js-resource/borrowed/call; children callback/owned/call; result immediate/value.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "react.root.render"]
opaque render
    (root : @& Lean.Vir.Js Lean.Vir.React.Root)
    (children : Lean.Vir.React.ReactM (Lean.Vir.Js Lean.Vir.React.Node)) :
    Lean.Vir.Browser.DomM Unit

/--
Generated binding for reviewed VIR protocol `react.root.render-component`.

Renders the explicit Lean-component adapter and preserves its React type while the supplied component ID remains stable.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-react-protocol-v1`: receiver none; root js-resource/borrowed/call; componentType js-resource/borrowed/call; component callback/owned/until-release; result immediate/value.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "react.root.renderComponent"]
opaque renderComponentThunk
    (root : @& Lean.Vir.Js Lean.Vir.React.Root)
    (componentType : @& Lean.Vir.Js String)
    (component : Unit → Lean.Vir.React.ReactM (Lean.Vir.Js Lean.Vir.React.Node)) :
    Lean.Vir.Browser.DomM Unit

/--
Generated binding for reviewed VIR protocol `react.root.render-selector`.

VIR-owned convenience protocol that finds a selector, creates a root, and renders the exact node value.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-react-protocol-v1`: receiver none; selector js-resource/borrowed/call; node js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "react.root.renderIntoSelector"]
opaque renderIntoSelectorJs
    (selector : @& Lean.Vir.Js String)
    (node : @& Lean.Vir.Js Lean.Vir.React.Node) :
    Lean.Vir.Browser.DomM (Lean.Vir.Js Bool)

/--
Generated binding for reviewed VIR protocol `react.root.render-component-selector`.

VIR-owned selector convenience protocol that mounts the explicitly identified Lean-component adapter.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-react-protocol-v1`: receiver none; selector js-resource/borrowed/call; componentType js-resource/borrowed/call; component callback/owned/until-release; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "react.root.renderComponentIntoSelector"]
opaque renderComponentIntoSelectorThunkJs
    (selector : @& Lean.Vir.Js String)
    (componentType : @& Lean.Vir.Js String)
    (component : Unit → Lean.Vir.React.ReactM (Lean.Vir.Js Lean.Vir.React.Node)) :
    Lean.Vir.Browser.DomM (Lean.Vir.Js Bool)

/--
Generated binding for reviewed VIR protocol `react.root.unmount-selector`.

VIR-owned convenience protocol that unmounts and releases the root associated with a selector.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-react-protocol-v1`: receiver none; selector js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "react.root.unmountSelector"]
opaque unmountSelectorJs
    (selector : @& Lean.Vir.Js String) :
    Lean.Vir.Browser.DomM (Lean.Vir.Js Bool)

end React.Root

namespace React.StateSetter

/--
Generated binding for reviewed VIR protocol `react.state.set`.

Enqueues one concrete JavaScript-owned state value through a React setter.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-react-protocol-v1`: receiver none; setter js-resource/borrowed/call; value js-resource/borrowed/call; result immediate/value.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "react.state.set"]
opaque set
    {α : Type}
    (setter : @& Lean.Vir.Js (Lean.Vir.React.StateSetter (Lean.Vir.Js α)))
    (value : @& Lean.Vir.Js α) :
    Lean.Vir.RuntimeM Unit

/--
Generated binding for reviewed VIR protocol `react.state.modify`.

Passes the Lean updater as React's functional state action; React may invoke it according to normal updater semantics.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-react-protocol-v1`: receiver none; setter js-resource/borrowed/call; update callback/owned/until-release; result immediate/value.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "react.state.modify"]
opaque modify
    {α : Type}
    (setter : @& Lean.Vir.Js (Lean.Vir.React.StateSetter (Lean.Vir.Js α)))
    (update : Lean.Vir.Js α → Lean.Vir.RuntimeM (Lean.Vir.Js α)) :
    Lean.Vir.RuntimeM Unit

end React.StateSetter

namespace React.StateTuple

/--
Generated binding for reviewed VIR protocol `react.state-tuple.value`.

Projects index zero from the exact JavaScript array returned by React.useState.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-react-protocol-v1`: receiver none; result js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "react.stateTuple.value"]
opaque value
    {α : Type}
    (result : @& Lean.Vir.Js (Lean.Vir.React.StateTuple (Lean.Vir.Js α))) :
    Lean.Vir.RuntimeM (Lean.Vir.Js α)

/--
Generated binding for reviewed VIR protocol `react.state-tuple.setter`.

Projects the exact native setter function from index one of React.useState's result array.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-react-protocol-v1`: receiver none; result js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "react.stateTuple.setter"]
opaque setter
    {α : Type}
    (result : @& Lean.Vir.Js (Lean.Vir.React.StateTuple (Lean.Vir.Js α))) :
    Lean.Vir.RuntimeM (Lean.Vir.Js (Lean.Vir.React.StateSetter (Lean.Vir.Js α)))

end React.StateTuple

end Lean.Vir
