/-
Copyright (c) 2026 Lean FRO LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Author: Emilio J. Gallego Arias
-/

-- Generated by scripts/bindings/generate-lean-bindings.mjs. Do not edit.

import Vir.React.Types

namespace Lean.Vir

namespace React.Callback

/--
Generated binding for reviewed VIR protocol `react.callback.of-unary`.

Explicitly converts a transferred Lean unary callback into an ordinary JavaScript function.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-react-protocol-v1`: receiver none; callback callback/owned/until-release; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js_explicit_conversion "js.value.react.callback"]
opaque ofUnary
    {α : Type}
    (callback : Lean.Vir.Js α → Lean.Vir.Browser.DomM Unit) :
    Lean.Vir.RuntimeM (Lean.Vir.Js (Lean.Vir.React.Callback α))

end React.Callback

namespace React.Component

/--
Generated binding for reviewed VIR protocol `react.component.of-lean`.

Explicitly converts a transferred Lean render callback into one reusable JavaScript React function component; that returned function is the React component identity.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-react-protocol-v1`: receiver none; render callback/owned/until-release; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js_explicit_conversion "js.value.react.component"]
opaque ofLeanJs
    {props : Type}
    (render : Lean.Vir.JSL props → Lean.Vir.React.ReactM (Lean.Vir.Js Lean.Vir.React.Node)) :
    Lean.Vir.RuntimeM (Lean.Vir.Js (Lean.Vir.React.Component props))

end React.Component

namespace React.EffectCallback

/--
Generated binding for reviewed VIR protocol `react.effect-callback.of-lean`.

Explicitly converts separate transferred Lean setup and cleanup callbacks into the ordinary JavaScript setup function shape accepted by React.useEffect.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-react-protocol-v1`: receiver none; effect lean-owned/owned/until-release; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js_explicit_conversion "js.value.react.effectCallback"]
opaque ofLeanJs
    {α : Type}
    (effect : Lean.Vir.React.LeanEffect α) :
    Lean.Vir.RuntimeM (Lean.Vir.Js Lean.Vir.React.EffectCallback)

end React.EffectCallback

namespace React.ElementType

/--
Generated binding for reviewed VIR protocol `react.element-type.tag`.

Uses the exact DOM tag string as a React ElementType value.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-react-protocol-v1`: receiver none; tag js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "react.elementType.tag"]
opaque tagJs
    (tag : @& Lean.Vir.Js String) :
    Lean.Vir.React.ReactM (Lean.Vir.Js Lean.Vir.React.ElementType)

end React.ElementType

namespace React.Hooks

/--
Generated binding for reviewed VIR protocol `react.hooks.use-reducer`.

Passes the caller's native reducer and initial value unchanged to React.useReducer and returns React's exact result array.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-react-protocol-v1`: receiver none; reducer js-resource/borrowed/call; initial js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "react.useReducer"]
opaque useReducer
    {state : Type}
    {action : Type}
    (reducer : @& Lean.Vir.Js (Lean.Vir.React.Reducer state action))
    (initial : @& Lean.Vir.Js state) :
    Lean.Vir.React.ReactM (Lean.Vir.Js (Lean.Vir.React.ReducerTuple state action))

/--
Generated binding for reviewed VIR protocol `react.hooks.use-state`.

Passes the initial value unchanged to React.useState and returns React's exact result array.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-react-protocol-v1`: receiver none; initial js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "react.useState"]
opaque useState
    {α : Type}
    (initial : @& Lean.Vir.Js α) :
    Lean.Vir.React.ReactM (Lean.Vir.Js (Lean.Vir.React.StateTuple (Lean.Vir.Js α)))

/--
Generated binding for reviewed VIR protocol `react.hooks.use-ref`.

Creates a typed React ref object initialized with a JavaScript-owned value.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-react-protocol-v1`: receiver none; initial js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "react.useRef"]
opaque useRef
    {α : Type}
    (initial : @& Lean.Vir.Js α) :
    Lean.Vir.React.ReactM (Lean.Vir.Js (Lean.Vir.React.Ref (Lean.Vir.Js α)))

/--
Generated binding for reviewed VIR protocol `react.hooks.use-effect`.

Passes the caller's native setup function unchanged to React.useEffect without a dependency argument.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-react-protocol-v1`: receiver none; setup js-resource/borrowed/call; result immediate/value.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "react.useEffect"]
opaque useEffectWithoutDeps
    (setup : @& Lean.Vir.Js Lean.Vir.React.EffectCallback) :
    Lean.Vir.React.ReactM Unit

/--
Generated binding for reviewed VIR protocol `react.hooks.use-memo`.

Passes the caller's native calculation function and dependency array unchanged to React.useMemo.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-react-protocol-v1`: receiver none; calculate js-resource/borrowed/call; deps js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "react.useMemo"]
opaque useMemo
    {α : Type}
    (calculate : @& Lean.Vir.Js (Lean.Vir.React.MemoCalculation α))
    (deps : @& Lean.Vir.Js Lean.Vir.React.DependencyList) :
    Lean.Vir.React.ReactM (Lean.Vir.Js α)

/--
Generated binding for reviewed VIR protocol `react.hooks.use-callback`.

Passes the caller's native JavaScript function and dependency array unchanged to React.useCallback and returns React's selected function.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-react-protocol-v1`: receiver none; callback js-resource/borrowed/call; deps js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "react.useCallback"]
opaque useCallback
    {α : Type}
    (callback : @& Lean.Vir.Js (Lean.Vir.React.Callback α))
    (deps : @& Lean.Vir.Js Lean.Vir.React.DependencyList) :
    Lean.Vir.React.ReactM (Lean.Vir.Js (Lean.Vir.React.Callback α))

/--
Generated binding for reviewed VIR protocol `react.hooks.use-context`.

Passes a native React context object unchanged to React.useContext and returns its current JavaScript-owned value.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-react-protocol-v1`: receiver none; context js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "react.useContext"]
opaque useContext
    {α : Type}
    (context : @& Lean.Vir.Js (Lean.Vir.React.Context α)) :
    Lean.Vir.React.ReactM (Lean.Vir.Js α)

/--
Generated binding for reviewed VIR protocol `react.hooks.use-effect-with-deps`.

Passes the caller's native setup function and dependency array unchanged to React.useEffect.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-react-protocol-v1`: receiver none; setup js-resource/borrowed/call; deps js-resource/borrowed/call; result immediate/value.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "react.useEffectWithDeps"]
opaque useEffectWithDeps
    (setup : @& Lean.Vir.Js Lean.Vir.React.EffectCallback)
    (deps : @& Lean.Vir.Js Lean.Vir.React.DependencyList) :
    Lean.Vir.React.ReactM Unit

end React.Hooks

namespace React.MemoCalculation

/--
Generated binding for reviewed VIR protocol `react.memo-calculation.of-lean`.

Explicitly converts a transferred Lean calculation into an ordinary zero-argument JavaScript function.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-react-protocol-v1`: receiver none; calculate callback/owned/until-release; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js_explicit_conversion "js.value.react.memoCalculation"]
opaque ofLean
    {α : Type}
    (calculate : Lean.Vir.React.ReactM (Lean.Vir.Js α)) :
    Lean.Vir.RuntimeM (Lean.Vir.Js (Lean.Vir.React.MemoCalculation α))

end React.MemoCalculation

namespace React.Node

/--
Generated binding for reviewed VIR protocol `react.node.text`.

Uses the exact JavaScript string as a React text node.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-react-protocol-v1`: receiver none; value js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "react.node.text"]
opaque textJs
    (value : @& Lean.Vir.Js String) :
    Lean.Vir.React.ReactM (Lean.Vir.Js Lean.Vir.React.Node)

/--
Generated binding for reviewed VIR protocol `react.node.create-element`.

Calls React.createElement with the exact ElementType, props object, and child array values.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-react-protocol-v1`: receiver none; elementType js-resource/borrowed/call; props js-resource/borrowed/call; children js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "react.node.createElement"]
opaque createElement
    (elementType : @& Lean.Vir.Js Lean.Vir.React.ElementType)
    (props : @& Lean.Vir.Js Lean.Vir.React.Props)
    (children : @& Lean.Vir.Js.Array (Lean.Vir.Js Lean.Vir.React.Node)) :
    Lean.Vir.React.ReactM (Lean.Vir.Js Lean.Vir.React.Node)

/--
Generated binding for reviewed VIR protocol `react.node.component`.

Calls React.createElement with the exact JavaScript function component and JSL-backed Lean props.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-react-protocol-v1`: receiver none; component js-resource/borrowed/call; props js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "react.node.component"]
opaque componentJs
    {props : Type}
    (component : @& Lean.Vir.Js (Lean.Vir.React.Component props))
    (props : @& Lean.Vir.JSL props) :
    Lean.Vir.React.ReactM (Lean.Vir.Js Lean.Vir.React.Node)

/--
Generated binding for reviewed VIR protocol `react.node.keyed-component`.

Calls React.createElement with the exact JavaScript function component, JSL-backed Lean props, and key.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-react-protocol-v1`: receiver none; component js-resource/borrowed/call; props js-resource/borrowed/call; key js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "react.node.keyedComponent"]
opaque keyedComponentJs
    {props : Type}
    (component : @& Lean.Vir.Js (Lean.Vir.React.Component props))
    (props : @& Lean.Vir.JSL props)
    (key : @& Lean.Vir.Js String) :
    Lean.Vir.React.ReactM (Lean.Vir.Js Lean.Vir.React.Node)

/--
Generated binding for reviewed VIR protocol `react.node.fragment`.

Calls React.createElement with React.Fragment, the exact props object, and child array values.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-react-protocol-v1`: receiver none; props js-resource/borrowed/call; children js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "react.node.fragment"]
opaque fragmentWithKeyJs
    (props : @& Lean.Vir.Js Lean.Vir.React.Props)
    (children : @& Lean.Vir.Js.Array (Lean.Vir.Js Lean.Vir.React.Node)) :
    Lean.Vir.React.ReactM (Lean.Vir.Js Lean.Vir.React.Node)

end React.Node

namespace React.Reducer

/--
Generated binding for reviewed VIR protocol `react.reducer.of-lean`.

Explicitly converts a transferred Lean reducer callback into an ordinary JavaScript function; React remains responsible for invocation and replay semantics.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-react-protocol-v1`: receiver none; reducer callback/owned/until-release; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js_explicit_conversion "js.value.react.reducer"]
opaque ofLean
    {state : Type}
    {action : Type}
    (reducer : Lean.Vir.Js state → Lean.Vir.Js action → Lean.Vir.RuntimeM (Lean.Vir.Js state)) :
    Lean.Vir.RuntimeM (Lean.Vir.Js (Lean.Vir.React.Reducer state action))

end React.Reducer

namespace React.Ref

/--
Generated binding for reviewed VIR protocol `react.ref.get`.

Reads the current value from React's exact mutable ref object.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-react-protocol-v1`: receiver none; ref js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "react.ref.get"]
opaque get
    {α : Type}
    (ref : @& Lean.Vir.Js (Lean.Vir.React.Ref (Lean.Vir.Js α))) :
    Lean.Vir.RuntimeM (Lean.Vir.Js α)

/--
Generated binding for reviewed VIR protocol `react.ref.set`.

Writes the exact JavaScript value to React's mutable ref object without scheduling a render.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-react-protocol-v1`: receiver none; ref js-resource/borrowed/call; value js-resource/borrowed/call; result immediate/value.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "react.ref.set"]
opaque set
    {α : Type}
    (ref : @& Lean.Vir.Js (Lean.Vir.React.Ref (Lean.Vir.Js α)))
    (value : @& Lean.Vir.Js α) :
    Lean.Vir.RuntimeM Unit

end React.Ref

namespace React.Root

/--
Generated reviewed method specialization of TypeScript `Root.render`.

Specialization policy: Root rendering is a DOM effect; the exact ReactNode JavaScript value is forwarded without conversion.

Upstream declaration: https://unpkg.com/@types/react-dom@19.2.4/client.d.ts#L62

ABI profile `vir-react-protocol-v1`: root js-resource/borrowed/call; children js-resource/borrowed/call; result immediate/value.

This declaration is generated; edit the TypeScript source or binding configuration.
-/
@[vir_js "react.root.renderNode"]
opaque renderNode
    (root : @& Lean.Vir.Js Lean.Vir.React.Root)
    (children : @& Lean.Vir.Js Lean.Vir.React.Node) :
    Lean.Vir.Browser.DomM Unit

/--
Generated reviewed method specialization of TypeScript `Root.unmount`.

Specialization policy: Unmount is terminal for the Lean root argument: it removes VIR's private active-root record and calls React's root.unmount without revoking JavaScript aliases.

Upstream declaration: https://unpkg.com/@types/react-dom@19.2.4/client.d.ts#L63

ABI profile `vir-react-protocol-v1`: root js-resource/consumed/call; result immediate/value.

This declaration is generated; edit the TypeScript source or binding configuration.
-/
@[vir_js "react.root.unmount"]
opaque unmount
    (root : Lean.Vir.Js Lean.Vir.React.Root) :
    Lean.Vir.Browser.DomM Unit

/--
Generated reviewed function specialization of TypeScript `createRoot`.

createRoot lets you create a root to display React components inside a browser DOM node.

Specialization policy: VIR restricts the TypeScript Container union to Element and uses default RootOptions; within that supported lane it passes the exact container to createRoot and returns the exact Root.

Upstream declaration: https://unpkg.com/@types/react-dom@19.2.4/client.d.ts#L86

ABI profile `vir-react-protocol-v1`: receiver none; container js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the TypeScript source or binding configuration.
-/
@[vir_js "react.root.create"]
opaque create
    (container : @& Lean.Vir.Js Lean.Vir.Browser.Element) :
    Lean.Vir.Browser.DomM (Lean.Vir.Js Lean.Vir.React.Root)

end React.Root

namespace React.StateSetter

/--
Generated binding for reviewed VIR protocol `react.state.modify`.

Passes the Lean updater as React's functional state action; React may invoke it according to normal updater semantics.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-react-protocol-v1`: receiver none; setter js-resource/borrowed/call; update callback/owned/until-release; result immediate/value.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "react.state.modify"]
opaque modify
    {α : Type}
    (setter : @& Lean.Vir.Js (Lean.Vir.React.StateSetter (Lean.Vir.Js α)))
    (update : Lean.Vir.Js α → Lean.Vir.RuntimeM (Lean.Vir.Js α)) :
    Lean.Vir.RuntimeM Unit

end React.StateSetter

end Lean.Vir
