#!/usr/bin/env bash
#
# Copyright (c) 2026 Lean FRO LLC. All rights reserved.
# Released under Apache 2.0 license as described in the file LICENSE.
# Author: Emilio J. Gallego Arias

set -euo pipefail

cd "$(dirname "$0")/.."
script_start=$SECONDS

src="${LEAN4_SRC:-third_party/lean4-src}"
out="build/upstream-probe"

if [ ! -f "$src/src/library/ir_interpreter.cpp" ]; then
  echo "error: Lean source not found at $src; run npm run fetch:lean first" >&2
  exit 1
fi

local_wasi_sdk="$PWD/.tools/wasi-sdk"

if [ -z "${WASI_SDK_PATH:-}" ] && [ -x "$local_wasi_sdk/bin/clang++" ]; then
  export WASI_SDK_PATH="$local_wasi_sdk"
fi

if [ -n "${WASI_SDK_PATH:-}" ] && [ -x "$WASI_SDK_PATH/bin/clang++" ]; then
  export PATH="$WASI_SDK_PATH/bin:$PATH"
  cxx="${CXX:-$WASI_SDK_PATH/bin/clang++}"
elif [ -n "${CXX:-}" ]; then
  cxx="$CXX"
else
  echo "error: clang++ not found. Run npm run install:wasi or set WASI_SDK_PATH." >&2
  exit 1
fi

lean_prefix="${LEAN_PREFIX:-$(lean --print-prefix)}"
target="${WASI_TARGET:-wasm32-wasip1}"
wasm_opt_level="${VIR_WASM_OPT_LEVEL:--O3}"
wasm_initial_memory="${VIR_WASM_INITIAL_MEMORY:-4194304}"
wasm_stack_size="${VIR_WASM_STACK_SIZE:-1048576}"
upstream="$src/src/library/ir_interpreter.cpp"
overlay_include="$out/include"
obj_dir="$out/obj"
wasm="$out/ir_interpreter.allow-undefined.wasm"
strict_wasm="$out/ir_interpreter.strict.wasm"
demo_wasm="web/public/vir-upstream.wasm"
strict_log="$out/strict-link.log"
import_section="$out/import-section.txt"
env_imports="$out/env-imports.txt"
wasi_imports="$out/wasi-imports.txt"
unresolved="$out/unresolved-symbols.txt"
allowed_undefined="$out/allowed-js-imports.txt"
report="$out/boundary.md"
mapfile -t browser_packages < <(
  node -e 'const cfg = require("./fixtures/browser-packages.json"); for (const pkg of cfg.packages ?? []) console.log(pkg.file)'
)

mkdir -p "$out"
mkdir -p "$obj_dir"
mkdir -p "$overlay_include/lean"
mkdir -p web/public

cat > "$allowed_undefined" <<'EOF'
vir_js_call
vir_js_call_result_size
vir_closure_push
vir_resource_get
vir_resource_push
vir_resource_release
vir_resource_root
vir_resource_take
EOF

package_start=$SECONDS
npm run --silent generate:package
for package in "${browser_packages[@]}"; do
  generated_package="build/generated/$package"
  demo_package="web/public/$package"
  if ! cmp -s "$generated_package" "$demo_package"; then
    cp "$generated_package" "$demo_package"
  fi
done
package_seconds=$((SECONDS - package_start))

src_commit="unknown"
if git -C "$src" rev-parse HEAD >/dev/null 2>&1; then
  src_commit="$(git -C "$src" rev-parse HEAD)"
fi

config_h="$overlay_include/lean/config.h"
config_tmp="$config_h.tmp"
cat > "$config_tmp" <<'EOF'
/*
Generated by scripts/build-upstream-probe.sh.

The installed Lean host headers enable LEAN_MIMALLOC, but the pinned Lean
source checkout does not vendor mimalloc sources for a WASI rebuild. For the
probe we compile the real Lean runtime sources through their non-mimalloc
allocator path.
*/
#pragma once
#include <lean/version.h>

#define LEAN_IS_STAGE0 0
EOF
if ! cmp -s "$config_tmp" "$config_h"; then
  mv "$config_tmp" "$config_h"
else
  rm "$config_tmp"
fi

runtime_sources=(
  "$src/src/runtime/alloc.cpp"
  "$src/src/runtime/apply.cpp"
  "$src/src/runtime/exception.cpp"
  "$src/src/runtime/hash.cpp"
  "$src/src/runtime/mpn.cpp"
  "$src/src/runtime/mpz.cpp"
  "$src/src/runtime/object.cpp"
  "$src/src/runtime/object_ref.cpp"
  "$src/src/runtime/utf8.cpp"
)

support_sources=(
  "$src/src/util/name.cpp"
)

shim_sources=(
  "wasm/upstream_shim/lean_object_constructors.cpp"
  "wasm/upstream_shim/interface_codec.cpp"
  "wasm/upstream_shim/native_symbols.cpp"
  "wasm/upstream_shim/platform_stubs.cpp"
  "wasm/upstream_shim/shim.cpp"
  "wasm/upstream_shim/package_decl_provider.cpp"
)

shim_deps=(
  "wasm/upstream_shim/decl_provider.h"
  "wasm/upstream_shim/interface_codec.h"
  "wasm/upstream_shim/native_symbols_registry.inc"
)

common_flags=(
  "--target=$target"
  -std=c++20
  -DNDEBUG
  "$wasm_opt_level"
  -DLEAN_DEFAULT_INTERPRETER_PREFER_NATIVE=false
  "-I$overlay_include"
  "-I$src/src/include"
  "-I$lean_prefix/include"
  "-I$src/src"
  -Iwasm/upstream_shim
  -ffunction-sections
  -fdata-sections
)

compile_stamp="$obj_dir/compile-flags.stamp"
compile_stamp_tmp="$compile_stamp.tmp"
{
  printf 'compiler=%s\n' "$cxx"
  printf 'lean_prefix=%s\n' "$lean_prefix"
  printf 'lean_source_commit=%s\n' "$src_commit"
  printf 'wasi_target=%s\n' "$target"
  printf 'opt_level=%s\n' "$wasm_opt_level"
  printf 'flag=%s\n' "${common_flags[@]}"
} > "$compile_stamp_tmp"
if ! cmp -s "$compile_stamp_tmp" "$compile_stamp"; then
  mv "$compile_stamp_tmp" "$compile_stamp"
else
  rm "$compile_stamp_tmp"
fi

object_for_source() {
  local source="$1"
  local stem="${source//\//_}"
  stem="${stem//:/_}"
  printf '%s/%s.o\n' "$obj_dir" "$stem"
}

compile_one() {
  local source="$1"
  local object="$2"
  shift 2
  local needs_compile=0
  if [ ! -f "$object" ] || [ "$source" -nt "$object" ] || [ "$config_h" -nt "$object" ] || [ "$compile_stamp" -nt "$object" ]; then
    needs_compile=1
  else
    for dep in "$@"; do
      if [ "$dep" -nt "$object" ]; then
        needs_compile=1
        break
      fi
    done
  fi
  if [ "$needs_compile" = "1" ]; then
    mkdir -p "$(dirname "$object")"
    echo "compile $source"
    compiled_count=$((compiled_count + 1))
    "$cxx" "${common_flags[@]}" -c "$source" -o "$object"
  fi
}

compiled_count=0
compile_start=$SECONDS
upstream_obj="$obj_dir/ir_interpreter.o"
stable_objects=("$upstream_obj")
compile_one "$upstream" "$upstream_obj"

for source in "${runtime_sources[@]}" "${support_sources[@]}" "${shim_sources[@]}"; do
  object="$(object_for_source "$source")"
  if [[ "$source" == wasm/upstream_shim/* ]]; then
    compile_one "$source" "$object" "${shim_deps[@]}"
  else
    compile_one "$source" "$object"
  fi
  stable_objects+=("$object")
done
compile_seconds=$((SECONDS - compile_start))
printf '%s\n' "${stable_objects[@]}" > "$out/objects.txt"

link_objects=(
  "${stable_objects[@]}"
)

link_flags=(
  -Wl,--no-entry
  -Wl,--gc-sections
  -Wl,--export-memory
  "-Wl,--initial-memory=$wasm_initial_memory"
  "-Wl,-z,stack-size=$wasm_stack_size"
)

exports=(
  -Wl,--export=lean_eval_const
  -Wl,--export=lean_run_init
  -Wl,--export=lean_run_mod_init_core
  -Wl,--export=vir_upstream_target_pointer_bytes
  -Wl,--export=vir_call
  -Wl,--export=vir_call_result_size
  -Wl,--export=vir_call_error
  -Wl,--export=vir_call_error_size
  -Wl,--export=vir_closure_call
  -Wl,--export=vir_closure_call_result_size
  -Wl,--export=vir_closure_call_error
  -Wl,--export=vir_closure_call_error_size
  -Wl,--export=vir_closure_release
  -Wl,--export=vir_alloc_bytes
  -Wl,--export=vir_free_bytes
  -Wl,--export=vir_load_ir_package
  -Wl,--export=vir_last_package_error
  -Wl,--export=vir_last_package_error_size
  -Wl,--export=vir_package_interface_manifest
  -Wl,--export=vir_package_interface_manifest_size
  -Wl,--export=vir_package_decl_count
)

link_stamp="$obj_dir/link-flags.stamp"
link_stamp_tmp="$link_stamp.tmp"
{
  printf 'wasi_target=%s\n' "$target"
  printf 'initial_memory=%s\n' "$wasm_initial_memory"
  printf 'stack_size=%s\n' "$wasm_stack_size"
  printf 'link_flag=%s\n' "${link_flags[@]}"
  printf 'export=%s\n' "${exports[@]}"
  printf 'allowed_undefined=%s\n' "$(cat "$allowed_undefined")"
} > "$link_stamp_tmp"
if ! cmp -s "$link_stamp_tmp" "$link_stamp"; then
  mv "$link_stamp_tmp" "$link_stamp"
else
  rm "$link_stamp_tmp"
fi

needs_link=0
if [ ! -f "$wasm" ] || [ ! -f "$strict_wasm" ] || [ "$link_stamp" -nt "$strict_wasm" ]; then
  needs_link=1
else
  for object in "${link_objects[@]}"; do
    if [ "$object" -nt "$strict_wasm" ]; then
      needs_link=1
      break
    fi
  done
fi

strict_status=0
link_seconds=0
if [ "$needs_link" = "1" ]; then
  link_start=$SECONDS
  echo "link $wasm"
  "$cxx" "--target=$target" "${link_objects[@]}" \
    "${link_flags[@]}" \
    -Wl,--allow-undefined \
    "${exports[@]}" \
    -o "$wasm"

  echo "link $strict_wasm"
  "$cxx" "--target=$target" "${link_objects[@]}" \
    "${link_flags[@]}" \
    "-Wl,--allow-undefined-file=$allowed_undefined" \
    -Wl,--error-limit=0 \
    "${exports[@]}" \
    -o "$strict_wasm" > "$strict_log" 2>&1 || strict_status=$?
  link_seconds=$((SECONDS - link_start))
else
  strict_status=0
fi

copied_demo_wasm=0
if [ "$strict_status" = "0" ] && { [ ! -f "$demo_wasm" ] || [ "$strict_wasm" -nt "$demo_wasm" ]; }; then
  cp "$strict_wasm" "$demo_wasm"
  copied_demo_wasm=1
fi

if command -v wasm-objdump >/dev/null 2>&1; then
  wasm_objdump=wasm-objdump
elif [ -x node_modules/.bin/wasm-objdump ]; then
  wasm_objdump=node_modules/.bin/wasm-objdump
else
  wasm_objdump=
fi

imports_collected=0
if [ -n "$wasm_objdump" ]; then
  imports_collected=1
  "$wasm_objdump" -x "$wasm" | sed -n '/^Import/,/^Function/p' > "$import_section"
  sed -n 's/^ - func.* <- env\.//p' "$import_section" | sort -u > "$env_imports"
  sed -n 's/^ - func.* <- wasi_snapshot_preview1\.//p' "$import_section" | sort -u > "$wasi_imports"
else
  : > "$import_section"
  : > "$env_imports"
  : > "$wasi_imports"
fi

rg -o "undefined symbol: .+" "$strict_log" \
  | sed 's/^undefined symbol: //' \
  | sort -u > "$unresolved" || true

object_bytes=0
for object in "${link_objects[@]}"; do
  object_bytes=$((object_bytes + $(wc -c < "$object" | tr -d ' ')))
done
object_count="${#link_objects[@]}"
wasm_bytes="$(wc -c < "$wasm" | tr -d ' ')"
unresolved_count="$(wc -l < "$unresolved" | tr -d ' ')"
env_import_count="$(wc -l < "$env_imports" | tr -d ' ')"
wasi_import_count="$(wc -l < "$wasi_imports" | tr -d ' ')"
runtime_source_count="${#runtime_sources[@]}"
support_source_count="${#support_sources[@]}"
shim_source_count="${#shim_sources[@]}"
report_total_seconds=$((SECONDS - script_start))
report_start=$SECONDS

{
  echo "# Upstream IR Interpreter WASI Boundary"
  echo
  echo "This report is generated by \`scripts/build-upstream-probe.sh\`."
  echo
  echo "## Inputs"
  echo
  echo "- Lean source: \`$src\`"
  echo "- Lean source commit: \`$src_commit\`"
  echo "- Lean include prefix: \`$lean_prefix\`"
  echo "- Upstream file: \`$upstream\`"
  echo "- WASI target: \`$target\`"
  echo "- WASM optimization level: \`$wasm_opt_level\`"
  echo "- Compiler: \`$cxx\`"
  echo "- Initial wasm memory: $wasm_initial_memory bytes"
  echo "- Wasm stack size: $wasm_stack_size bytes"
  echo "- Generated config overlay: \`$overlay_include/lean/config.h\`"
  echo "- Object cache: \`$obj_dir\`"
  echo "- Real Lean runtime sources linked: $runtime_source_count"
  echo "- Lean support sources linked: $support_source_count"
  echo "- Local WASI shim sources linked: $shim_source_count"
  echo "- Generated browser IR packages:"
  for package in "${browser_packages[@]}"; do
    echo "  - \`build/generated/$package\`"
  done
  echo "- Browser demo IR packages:"
  for package in "${browser_packages[@]}"; do
    echo "  - \`web/public/$package\`"
  done
  echo
  echo "## Timing"
  echo
  echo "- Browser package generation: ${package_seconds}s"
  echo "- Object compile phase: ${compile_seconds}s"
  echo "- Objects compiled in this run: $compiled_count"
  echo "- Link phase: ${link_seconds}s"
  echo "- Total before report write: ${report_total_seconds}s"
  echo
  echo "## Outputs"
  echo
  echo "- Linked objects: $object_count (${object_bytes} bytes total)"
  echo "- Link reused cached wasm: $([ "$needs_link" = "0" ] && echo "yes" || echo "no")"
  echo "- Allow-undefined wasm with runtime: \`$wasm\` (${wasm_bytes} bytes)"
  if [ "$strict_status" = "0" ]; then
    echo "- Browser demo wasm: \`$demo_wasm\`"
  fi
  echo "- Strict link log: \`$strict_log\`"
  echo "- Strict link status: \`$strict_status\`"
  echo
  echo "## Linked Real Runtime Sources"
  echo
  for path in "${runtime_sources[@]}"; do
    printf -- '- `%s`\n' "$path"
  done
  echo
  echo "## Linked Lean Support Sources"
  echo
  for path in "${support_sources[@]}"; do
    printf -- '- `%s`\n' "$path"
  done
  echo
  echo "## Linked Local Shim Sources"
  echo
  for path in "${shim_sources[@]}"; do
    printf -- '- `%s`\n' "$path"
  done
  echo
  echo "## Runtime Config Overlay"
  echo
  echo "The WASI probe compiles the real Lean runtime source files with a generated"
  echo "\`lean/config.h\` that leaves \`LEAN_MIMALLOC\` disabled. The pinned Lean"
  echo "source checkout provides the runtime source but not a vendored mimalloc source"
  echo "tree suitable for this local WASI rebuild."
  echo
  echo "## Boundary Summary"
  echo
  echo "- Strict unresolved symbols: $unresolved_count"
  if [ "$imports_collected" = "1" ]; then
    echo "- Imported \`env\` symbols in allow-undefined wasm: $env_import_count"
    echo "- Imported WASI symbols in allow-undefined wasm: $wasi_import_count"
  else
    echo "- Allow-undefined import scan: not collected; \`wasm-objdump\` was not available"
  fi
  echo
  echo "## Strict Unresolved Symbols"
  echo
  if [ "$unresolved_count" = "0" ]; then
    echo "None."
  else
    while IFS= read -r sym; do
      printf -- '- `%s`\n' "$sym"
    done < "$unresolved"
  fi
  echo
  echo "## Allow-Undefined \`env\` Imports"
  echo
  if [ "$imports_collected" != "1" ]; then
    echo "Not collected; \`wasm-objdump\` was not available."
  elif [ "$env_import_count" = "0" ]; then
    echo "None."
  else
    while IFS= read -r sym; do
      printf -- '- `%s`\n' "$sym"
    done < "$env_imports"
  fi
  echo
  echo "## Allow-Undefined WASI Imports"
  echo
  if [ "$imports_collected" != "1" ]; then
    echo "Not collected; \`wasm-objdump\` was not available."
  elif [ "$wasi_import_count" = "0" ]; then
    echo "None."
  else
    while IFS= read -r sym; do
      printf -- '- `%s`\n' "$sym"
    done < "$wasi_imports"
  fi
  echo
  echo "## Demo Policy"
  echo
  echo "- Keep \`src/library/ir_interpreter.cpp\` unmodified."
  echo "- Provide real Lean IR declaration objects through \`lean_ir_find_env_decl\`."
  echo "- Stub only runtime/library pieces that the current demo paths do not execute."
  echo "- Keep general native symbol lookup unsupported; register only demo externs explicitly."
  echo
  echo "## Current Shim Scope"
  echo
  echo "\`wasm/upstream_shim/shim.cpp\` supplies the package call surface,"
  echo "closure bridge, and declaration lookup hooks. \`interface_codec.cpp\`"
  echo "supplies the JavaScript interface wire codec."
  echo "\`wasm/upstream_shim/native_symbols.cpp\` supplies the explicit native"
  echo "extern wrappers plus generated registry include and restricted \`dlsym\` lookup;"
  echo "\`platform_stubs.cpp\`"
  echo "contains the remaining host/platform stubs. \`package_decl_provider.cpp\`"
  echo "loads \`$generated_package\`, a single-file declaration package emitted from"
  echo "typed \`Lean.IR.Decl\` values by \`tools/GeneratePackage.lean\`. The browser"
  echo "demos run through the real upstream interpreter."
} > "$report"
report_seconds=$((SECONDS - report_start))

echo "wrote $report"
if [ "$copied_demo_wasm" = "1" ]; then
  echo "wrote $demo_wasm"
fi
echo "strict unresolved symbols: $unresolved_count"
echo "upstream probe timing: packages=${package_seconds}s compile=${compile_seconds}s link=${link_seconds}s report=${report_seconds}s total=$((SECONDS - script_start))s compiled_objects=$compiled_count link_reused=$([ "$needs_link" = "0" ] && echo "yes" || echo "no")"
if [ "$strict_status" != "0" ]; then
  exit "$strict_status"
fi
