#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."

src="${LEAN4_SRC:-third_party/lean4-src}"
out="build/upstream-probe"

if [ ! -f "$src/src/library/ir_interpreter.cpp" ]; then
  echo "error: Lean source not found at $src; run npm run fetch:lean first" >&2
  exit 1
fi

local_wasi_sdk="$PWD/.tools/wasi-sdk"

if [ -z "${WASI_SDK_PATH:-}" ] && [ -x "$local_wasi_sdk/bin/clang++" ]; then
  export WASI_SDK_PATH="$local_wasi_sdk"
fi

if [ -n "${WASI_SDK_PATH:-}" ] && [ -x "$WASI_SDK_PATH/bin/clang++" ]; then
  export PATH="$WASI_SDK_PATH/bin:$PATH"
  cxx="${CXX:-$WASI_SDK_PATH/bin/clang++}"
elif [ -n "${CXX:-}" ]; then
  cxx="$CXX"
else
  echo "error: clang++ not found. Run npm run install:wasi or set WASI_SDK_PATH." >&2
  exit 1
fi

lean_prefix="${LEAN_PREFIX:-$(lean --print-prefix)}"
target="${WASI_TARGET:-wasm32-wasip1}"
upstream="$src/src/library/ir_interpreter.cpp"
overlay_include="$out/include"
obj="$out/ir_interpreter.o"
wasm="$out/ir_interpreter.allow-undefined.wasm"
strict_wasm="$out/ir_interpreter.strict.wasm"
demo_wasm="web/public/vir-upstream.wasm"
strict_log="$out/strict-link.log"
import_section="$out/import-section.txt"
env_imports="$out/env-imports.txt"
wasi_imports="$out/wasi-imports.txt"
unresolved="$out/unresolved-symbols.txt"
report="$out/boundary.md"

mkdir -p "$out"
mkdir -p "$overlay_include/lean"
mkdir -p web/public

cat > "$overlay_include/lean/config.h" <<'EOF'
/*
Generated by scripts/build-upstream-probe.sh.

The installed Lean host headers enable LEAN_MIMALLOC, but the pinned Lean
source checkout does not vendor mimalloc sources for a WASI rebuild. For the
probe we compile the real Lean runtime sources through their non-mimalloc
allocator path.
*/
#pragma once
#include <lean/version.h>

#define LEAN_IS_STAGE0 0
EOF

runtime_sources=(
  "$src/src/runtime/alloc.cpp"
  "$src/src/runtime/apply.cpp"
  "$src/src/runtime/exception.cpp"
  "$src/src/runtime/hash.cpp"
  "$src/src/runtime/mpn.cpp"
  "$src/src/runtime/mpz.cpp"
  "$src/src/runtime/object.cpp"
  "$src/src/runtime/object_ref.cpp"
  "$src/src/runtime/utf8.cpp"
)

support_sources=(
  "$src/src/util/name.cpp"
)

shim_sources=(
  "wasm/upstream_shim/shim.cpp"
  "wasm/upstream_shim/static_decl_provider.cpp"
)

link_sources=(
  "$upstream"
  "${runtime_sources[@]}"
  "${support_sources[@]}"
  "${shim_sources[@]}"
)

common_flags=(
  "--target=$target"
  -std=c++20
  -DNDEBUG
  -DLEAN_DEFAULT_INTERPRETER_PREFER_NATIVE=false
  "-I$overlay_include"
  "-I$src/src/include"
  "-I$lean_prefix/include"
  "-I$src/src"
  -ffunction-sections
  -fdata-sections
)

exports=(
  -Wl,--export=lean_eval_const
  -Wl,--export=lean_eval_main
  -Wl,--export=lean_run_init
  -Wl,--export=lean_run_mod_init_core
  -Wl,--export=vir_upstream_shim_fixture_count
  -Wl,--export=vir_upstream_target_pointer_bytes
  -Wl,--export=vir_upstream_fib
)

"$cxx" "${common_flags[@]}" -c "$upstream" -o "$obj"

"$cxx" "${common_flags[@]}" "${link_sources[@]}" \
  -Wl,--no-entry \
  -Wl,--gc-sections \
  -Wl,--allow-undefined \
  "${exports[@]}" \
  -o "$wasm"

strict_status=0
"$cxx" "${common_flags[@]}" "${link_sources[@]}" \
  -Wl,--no-entry \
  -Wl,--gc-sections \
  -Wl,--error-limit=0 \
  "${exports[@]}" \
  -o "$strict_wasm" > "$strict_log" 2>&1 || strict_status=$?

if [ "$strict_status" = "0" ]; then
  cp "$strict_wasm" "$demo_wasm"
fi

if command -v wasm-objdump >/dev/null 2>&1; then
  wasm_objdump=wasm-objdump
elif [ -x node_modules/.bin/wasm-objdump ]; then
  wasm_objdump=node_modules/.bin/wasm-objdump
else
  wasm_objdump=
fi

imports_collected=0
if [ -n "$wasm_objdump" ]; then
  imports_collected=1
  "$wasm_objdump" -x "$wasm" | sed -n '/^Import/,/^Function/p' > "$import_section"
  sed -n 's/^ - func.* <- env\.//p' "$import_section" | sort -u > "$env_imports"
  sed -n 's/^ - func.* <- wasi_snapshot_preview1\.//p' "$import_section" | sort -u > "$wasi_imports"
else
  : > "$import_section"
  : > "$env_imports"
  : > "$wasi_imports"
fi

rg -o "undefined symbol: .+" "$strict_log" \
  | sed 's/^undefined symbol: //' \
  | sort -u > "$unresolved" || true

src_commit="unknown"
if git -C "$src" rev-parse HEAD >/dev/null 2>&1; then
  src_commit="$(git -C "$src" rev-parse HEAD)"
fi

object_bytes="$(wc -c < "$obj" | tr -d ' ')"
wasm_bytes="$(wc -c < "$wasm" | tr -d ' ')"
unresolved_count="$(wc -l < "$unresolved" | tr -d ' ')"
env_import_count="$(wc -l < "$env_imports" | tr -d ' ')"
wasi_import_count="$(wc -l < "$wasi_imports" | tr -d ' ')"
runtime_source_count="${#runtime_sources[@]}"
support_source_count="${#support_sources[@]}"
shim_source_count="${#shim_sources[@]}"

{
  echo "# Upstream IR Interpreter WASI Boundary"
  echo
  echo "This report is generated by \`scripts/build-upstream-probe.sh\`."
  echo
  echo "## Inputs"
  echo
  echo "- Lean source: \`$src\`"
  echo "- Lean source commit: \`$src_commit\`"
  echo "- Lean include prefix: \`$lean_prefix\`"
  echo "- Upstream file: \`$upstream\`"
  echo "- WASI target: \`$target\`"
  echo "- Compiler: \`$cxx\`"
  echo "- Generated config overlay: \`$overlay_include/lean/config.h\`"
  echo "- Real Lean runtime sources linked: $runtime_source_count"
  echo "- Lean support sources linked: $support_source_count"
  echo "- Local WASI shim sources linked: $shim_source_count"
  echo
  echo "## Outputs"
  echo
  echo "- Object: \`$obj\` (${object_bytes} bytes)"
  echo "- Allow-undefined wasm with runtime: \`$wasm\` (${wasm_bytes} bytes)"
  if [ "$strict_status" = "0" ]; then
    echo "- Browser demo wasm: \`$demo_wasm\`"
  fi
  echo "- Strict link log: \`$strict_log\`"
  echo "- Strict link status: \`$strict_status\`"
  echo
  echo "## Linked Real Runtime Sources"
  echo
  for path in "${runtime_sources[@]}"; do
    printf -- '- `%s`\n' "$path"
  done
  echo
  echo "## Linked Lean Support Sources"
  echo
  for path in "${support_sources[@]}"; do
    printf -- '- `%s`\n' "$path"
  done
  echo
  echo "## Linked Local Shim Sources"
  echo
  for path in "${shim_sources[@]}"; do
    printf -- '- `%s`\n' "$path"
  done
  echo
  echo "## Runtime Config Overlay"
  echo
  echo "The WASI probe compiles the real Lean runtime source files with a generated"
  echo "\`lean/config.h\` that leaves \`LEAN_MIMALLOC\` disabled. The pinned Lean"
  echo "source checkout provides the runtime source but not a vendored mimalloc source"
  echo "tree suitable for this local WASI rebuild."
  echo
  echo "## Boundary Summary"
  echo
  echo "- Strict unresolved symbols: $unresolved_count"
  if [ "$imports_collected" = "1" ]; then
    echo "- Imported \`env\` symbols in allow-undefined wasm: $env_import_count"
    echo "- Imported WASI symbols in allow-undefined wasm: $wasi_import_count"
  else
    echo "- Allow-undefined import scan: not collected; \`wasm-objdump\` was not available"
  fi
  echo
  echo "## Strict Unresolved Symbols"
  echo
  if [ "$unresolved_count" = "0" ]; then
    echo "None."
  else
    while IFS= read -r sym; do
      printf -- '- `%s`\n' "$sym"
    done < "$unresolved"
  fi
  echo
  echo "## Allow-Undefined \`env\` Imports"
  echo
  if [ "$imports_collected" != "1" ]; then
    echo "Not collected; \`wasm-objdump\` was not available."
  elif [ "$env_import_count" = "0" ]; then
    echo "None."
  else
    while IFS= read -r sym; do
      printf -- '- `%s`\n' "$sym"
    done < "$env_imports"
  fi
  echo
  echo "## Allow-Undefined WASI Imports"
  echo
  if [ "$imports_collected" != "1" ]; then
    echo "Not collected; \`wasm-objdump\` was not available."
  elif [ "$wasi_import_count" = "0" ]; then
    echo "None."
  else
    while IFS= read -r sym; do
      printf -- '- `%s`\n' "$sym"
    done < "$wasi_imports"
  fi
  echo
  echo "## Demo Policy"
  echo
  echo "- Keep \`src/library/ir_interpreter.cpp\` unmodified."
  echo "- Provide real Lean IR declaration objects through \`lean_ir_find_env_decl\`."
  echo "- Stub only runtime/library pieces that the fib path does not execute."
  echo "- Leave native symbol lookup unsupported until a real use case needs it."
  echo
  echo "## Current Shim Scope"
  echo
  echo "\`wasm/upstream_shim/shim.cpp\` supplies the minimal host/environment"
  echo "boundary for the strict WASI link. \`static_decl_provider.cpp\` supplies"
  echo "the statically loaded demo declaration closure for \`fib\`, \`fib._boxed\`,"
  echo "\`Nat.add\`, \`Nat.sub\`, and \`Nat.decEq\`."
  echo "The arithmetic declarations are executable real IR function bodies over a"
  echo "static Peano-shaped Nat representation, so \`vir_upstream_fib\` now runs"
  echo "the fixture through the real upstream interpreter."
} > "$report"

echo "wrote $report"
if [ "$strict_status" = "0" ]; then
  echo "wrote $demo_wasm"
fi
echo "strict unresolved symbols: $unresolved_count"
