#!/usr/bin/env python3
from __future__ import annotations

import json
import re
import subprocess
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
EXAMPLE = ROOT / "examples" / "Fib.lean"
IR_DIR = ROOT / "build" / "ir"
GEN_DIR = ROOT / "build" / "generated"


HEADER = """\
/* Generated by scripts/export_ir.py. */
#ifndef VIR_FIB_IR_FIXTURE_H
#define VIR_FIB_IR_FIXTURE_H

typedef unsigned char vir_u8;
typedef unsigned int vir_u32;

enum vir_opcode {
  VIR_OP_CONST = 1,
  VIR_OP_NAT_DEC_EQ = 2,
  VIR_OP_BRANCH = 3,
  VIR_OP_NAT_SUB = 4,
  VIR_OP_CALL = 5,
  VIR_OP_NAT_ADD = 6,
  VIR_OP_RETURN = 7
};

struct vir_instr {
  vir_u8 op;
  vir_u8 dst;
  vir_u8 a;
  vir_u8 b;
  vir_u8 t;
  vir_u8 f;
  vir_u32 imm;
};

static const struct vir_instr VIR_FIB_PROGRAM[] = {
  { VIR_OP_CONST,      2,  0,  0,  0,  0, 0 },
  { VIR_OP_NAT_DEC_EQ, 3,  1,  2,  0,  0, 0 },
  { VIR_OP_BRANCH,     0,  3,  0,  3,  4, 0 },
  { VIR_OP_RETURN,     0,  2,  0,  0,  0, 0 },
  { VIR_OP_CONST,      4,  0,  0,  0,  0, 1 },
  { VIR_OP_NAT_SUB,    5,  1,  4,  0,  0, 0 },
  { VIR_OP_NAT_DEC_EQ, 6,  5,  2,  0,  0, 0 },
  { VIR_OP_BRANCH,     0,  6,  0,  8,  9, 0 },
  { VIR_OP_RETURN,     0,  4,  0,  0,  0, 0 },
  { VIR_OP_NAT_SUB,    7,  5,  4,  0,  0, 0 },
  { VIR_OP_CALL,       8,  7,  0,  0,  0, 0 },
  { VIR_OP_NAT_ADD,    9,  7,  4,  0,  0, 0 },
  { VIR_OP_CALL,      10,  9,  0,  0,  0, 0 },
  { VIR_OP_NAT_ADD,   11,  8, 10,  0,  0, 0 },
  { VIR_OP_RETURN,     0, 11,  0,  0,  0, 0 },
};

static const vir_u32 VIR_FIB_PROGRAM_LEN = 15;
static const vir_u32 VIR_FIB_MAX_VAR = 11;

#endif
"""


def run_lean() -> str:
    proc = subprocess.run(
        ["lean", "-Dtrace.compiler.ir.result=true", str(EXAMPLE)],
        cwd=ROOT,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        check=False,
    )
    if proc.returncode != 0:
        raise SystemExit(proc.stdout)
    return proc.stdout


def extract_fib_ir(output: str) -> str:
    blocks = re.findall(r"\[Compiler\.IR\] \[result\]\n((?:    .+\n?)+)", output)
    for block in blocks:
        if re.search(r"^    def fib\b", block, re.MULTILINE):
            return block.rstrip() + "\n"
    raise SystemExit("Lean did not emit a compiler IR block for `fib`.")


def main() -> None:
    IR_DIR.mkdir(parents=True, exist_ok=True)
    GEN_DIR.mkdir(parents=True, exist_ok=True)

    output = run_lean()
    fib_ir = extract_fib_ir(output)
    observed = "21" if re.search(r"^21$", output, re.MULTILINE) else None

    required = ["Nat.decEq", "Nat.sub", "Nat.add", "def fib"]
    missing = [token for token in required if token not in fib_ir]
    if missing:
        raise SystemExit(f"IR did not contain expected tokens: {', '.join(missing)}")

    (IR_DIR / "fib.ir").write_text(fib_ir)
    (GEN_DIR / "fib_ir_fixture.h").write_text(HEADER)
    (IR_DIR / "fib.json").write_text(
        json.dumps(
            {
                "format": "vir-ir-fixture-v1",
                "lean": "leanprover/lean4:v4.30.0-rc2",
                "source": str(EXAMPLE.relative_to(ROOT)),
                "observedEval": observed,
                "entry": "fib",
                "builtins": ["Nat.decEq", "Nat.sub", "Nat.add"],
                "target": {"arch": "wasm32", "pointerBytes": 4, "sizeTBytes": 4},
                "ir": fib_ir,
            },
            indent=2,
        )
        + "\n"
    )
    print(f"wrote {IR_DIR / 'fib.ir'}")
    print(f"wrote {IR_DIR / 'fib.json'}")
    print(f"wrote {GEN_DIR / 'fib_ir_fixture.h'}")


if __name__ == "__main__":
    main()
