/-
Generated by `node scripts/check-ir-codec-tags.mjs --write`.
Source of truth: `scripts/ir-codec-tags.mjs`.
-/

namespace Vir.GeneratePackage

namespace PackageIRTags

def nameAnonymous : Nat := 0
def nameString : Nat := 1
def nameNumeral : Nat := 2

def irTypeFloat : Nat := 0
def irTypeUInt8 : Nat := 1
def irTypeUInt16 : Nat := 2
def irTypeUInt32 : Nat := 3
def irTypeUInt64 : Nat := 4
def irTypeUSize : Nat := 5
def irTypeErased : Nat := 6
def irTypeObject : Nat := 7
def irTypeTObject : Nat := 8
def irTypeFloat32 : Nat := 9
def irTypeTagged : Nat := 12
def irTypeVoid : Nat := 13
-- Tag 10 is reserved: Lean.IR.IRType.struct is not supported by the package codec.
-- Tag 11 is reserved: Lean.IR.IRType.union is not supported by the package codec.

def argVar : Nat := 0
def argErased : Nat := 1

def litNum : Nat := 0
def litString : Nat := 1

def exprCtor : Nat := 0
def exprReset : Nat := 1
def exprReuse : Nat := 2
def exprProj : Nat := 3
def exprUProj : Nat := 4
def exprSProj : Nat := 5
def exprFap : Nat := 6
def exprPap : Nat := 7
def exprAp : Nat := 8
def exprBox : Nat := 9
def exprUnbox : Nat := 10
def exprLit : Nat := 11
def exprIsShared : Nat := 12

def altCtor : Nat := 0
def altDefault : Nat := 1

def bodyVDecl : Nat := 0
def bodyJDecl : Nat := 1
def bodySet : Nat := 2
def bodySetTag : Nat := 3
def bodyUSet : Nat := 4
def bodySSet : Nat := 5
def bodyInc : Nat := 6
def bodyDec : Nat := 7
def bodyDel : Nat := 8
def bodyCase : Nat := 9
def bodyRet : Nat := 10
def bodyJmp : Nat := 11
def bodyUnreachable : Nat := 12

def declFun : Nat := 0
def declExtern : Nat := 1

end PackageIRTags

end Vir.GeneratePackage
