/-
Copyright (c) 2026 Lean FRO LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Author: Emilio J. Gallego Arias
-/

import Vir.GeneratePackage.Manifest

open Lean

namespace Vir.GeneratePackage

open Lean.IR

def reportFor (_targets : Array Target) (closure : Closure) (manifest : InterfaceManifest) : String :=
  let roots :=
    manifest.metadata.targets.foldl (fun acc target => acc ++ target.resolvedRoots) #[]
  let loadedLines :=
    closure.decls.map fun loaded =>
      s!"- `{loaded.decl.name}` from `{loaded.source}`"
  let externLines :=
    closure.externs.map fun ext =>
      s!"- `{ext.name}` -> `{ext.symbol}`"
  let initGlobalLines :=
    if closure.initGlobals.isEmpty then #["None."] else closure.initGlobals.map fun entry =>
      s!"- `{entry.name}` <- `{entry.initName}`"
  let missingDeclLines :=
    if closure.missingDecls.isEmpty then #["None."] else closure.missingDecls.map fun n => s!"- `{n}`"
  let missingExternLines :=
    if closure.missingExterns.isEmpty then #["None."] else closure.missingExterns.map fun n => s!"- `{n}`"
  let unsupportedInitGlobalLines :=
    if closure.unsupportedInitGlobals.isEmpty then #["None."] else closure.unsupportedInitGlobals.map fun n => s!"- `{n}`"
  let interfaceExportLines :=
    if manifest.exports.isEmpty then #["None."] else manifest.exports.map fun entry =>
      let args := entry.args.map (fun arg => s!"{arg.name} : {arg.type.label}")
      let effect := if entry.effect.isEffectful then s!" {entry.effect.display}" else ""
      let startup := if entry.startup then " [startup]" else ""
      s!"- `{entry.entry}` as `{entry.jsName}`{startup} : ({", ".intercalate args.toList}) ->{effect} {entry.result.label}"
  let hostImportLines :=
    if manifest.hostImports.isEmpty then #["None."] else manifest.hostImports.map fun entry =>
      let args := entry.args.map (fun arg => s!"{arg.name} : {arg.type.label}")
      let effect := if entry.effect.isEffectful then s!"{entry.effect.display} " else ""
      let erased :=
        if entry.erasedPrefixArgs == 0 then ""
        else s!" erasedPrefixArgs={entry.erasedPrefixArgs}"
      s!"- slot {entry.slot}: `{entry.name}` -> `{entry.target}` via `{entry.symbol}` boundary={entry.boundary.label} arity={entry.arity}{erased} : ({", ".intercalate args.toList}) -> {effect}{entry.result.label}"
  let packageDiagnosticLines :=
    if manifest.diagnostics.isEmpty then #["None."] else manifest.diagnostics.map fun diagnostic =>
      s!"- `{diagnostic.name}` from `{diagnostic.source}`: {diagnostic.reason}"
  "# Generated IR Package Report\n\n"
  ++ "Generated by `tools/GeneratePackage.lean` from typed `Lean.IR.Decl` values.\n\n"
  ++ s!"Package format: {manifest.metadata.packageFormatVersion}\n\n"
  ++ s!"Manifest version: {manifest.metadata.manifestVersion}\n\n"
  ++ s!"Lean toolchain: {manifest.metadata.leanToolchain}\n\n"
  ++ s!"Lean version: {manifest.metadata.leanVersion}\n\n"
  ++ s!"Lean git hash: {manifest.metadata.leanGithash}\n\n"
  ++ s!"Generated at: {manifest.metadata.generatedAt}\n\n"
  ++ s!"Loaded declarations: {closure.decls.size}\n\n"
  ++ s!"Native extern declarations: {closure.externs.size}\n\n"
  ++ s!"Initializer globals: {closure.initGlobals.size}\n\n"
  ++ s!"JavaScript host imports: {manifest.hostImports.size}\n\n"
  ++ s!"Interface exports: {manifest.exports.size}\n\n"
  ++ "## Roots\n\n"
  ++ "\n".intercalate (roots.map (fun n => s!"- `{n}`")).toList ++ "\n\n"
  ++ "## Loaded IR Declarations\n\n"
  ++ "\n".intercalate loadedLines.toList ++ "\n\n"
  ++ "## Native Extern Declarations\n\n"
  ++ "\n".intercalate externLines.toList ++ "\n\n"
  ++ "## Initializer Globals\n\n"
  ++ "\n".intercalate initGlobalLines.toList ++ "\n\n"
  ++ "## JavaScript Host Imports\n\n"
  ++ "\n".intercalate hostImportLines.toList ++ "\n\n"
  ++ "## Missing IR Declarations\n\n"
  ++ "\n".intercalate missingDeclLines.toList ++ "\n\n"
  ++ "## Missing Native Extern Registrations\n\n"
  ++ "\n".intercalate missingExternLines.toList ++ "\n\n"
  ++ "## Unsupported Init Globals\n\n"
  ++ "\n".intercalate unsupportedInitGlobalLines.toList ++ "\n\n"
  ++ "## Interface Exports\n\n"
  ++ "\n".intercalate interfaceExportLines.toList ++ "\n\n"
  ++ "## Package Diagnostics\n\n"
  ++ "\n".intercalate packageDiagnosticLines.toList ++ "\n"

end Vir.GeneratePackage
