/-
Copyright (c) 2026 Lean FRO LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Author: Emilio J. Gallego Arias
-/

import Lean.Compiler.LCNF.EmitC
import Lean.Compiler.Main
import Lean.Elab.Frontend
import Vir.GeneratePackage.Json
import Vir.GeneratePackage.NativeExterns

open Lean

namespace Vir.GenerateNativeWrappers

open Vir.GeneratePackage

def wrapperExterns (externs : Array NativeExtern) : Array NativeExtern :=
  externs.filter (·.generateBoxedWrapper)

def wrapperDecls (externs : Array NativeExtern) : Array Name :=
  wrapperExterns externs |>.map (·.name)

def readExtraNames (path : System.FilePath) : IO (Array Name) := do
  let mut names := #[]
  for line in (← IO.FS.readFile path).splitOn "\n" do
    let line := line.trimAscii.toString
    if line.isEmpty || line.startsWith "#" then
      continue
    let name ← IO.ofExcept (parseDottedName line)
    if names.contains name then
      throw <| IO.userError s!"duplicate extra native extern `{name}`"
    names := names.push name
  if names.isEmpty then
    throw <| IO.userError s!"extra native extern file `{path}` is empty"
  return names

def nativeExternCatalogJson (externs : Array NativeExtern) : String :=
  jsonObject #[
    ("format", jsonString "lean-vir-native-extern-catalog"),
    ("version", jsonNat 1),
    ("externs", jsonArray (externs.map fun ext => jsonObject #[
      ("name", jsonName ext.name),
      ("symbol", jsonString ext.symbol),
      ("generateBoxedWrapper", jsonBool ext.generateBoxedWrapper),
      ("params", jsonArray (ext.params.map fun param => jsonObject #[
        ("index", jsonNat param.x.idx),
        ("borrow", jsonBool param.borrow),
        ("type", jsonString (nativeIRTypeLabel param.ty))
      ])),
      ("resultType", jsonString (nativeIRTypeLabel ext.resultType)),
      ("deps", jsonArray (ext.deps.map jsonName))
    ]))
  ]

def generatedRegistry (externs : Array NativeExtern) : CoreM String := do
  let env ← getEnv
  let wrapperExterns := wrapperExterns externs
  let macroLine :=
    if wrapperExterns.isEmpty then
      "#define VIR_COMPILER_NATIVE_SYMBOLS(X)"
    else
      "#define VIR_COMPILER_NATIVE_SYMBOLS(X) \\"
  let mut lines : Array String := #[
    "/*",
    "Generated by vir_native_wrappers from Vir.GeneratePackage.nativeExternSpecs.",
    "*/",
    "",
    macroLine
  ]
  let mut index := 0
  for ext in wrapperExterns do
    index := index + 1
    let stem := getSymbolStem env ext.name
    let boxedSymbol := mkMangledBoxedName stem
    let suffix := if index == wrapperExterns.size then "" else " \\"
    lines := lines.push s!"    X(\"{ext.name}\", \"{ext.symbol}\", {boxedSymbol}){suffix}"
  return "\n".intercalate lines.toList ++ "\n"

unsafe def loadEnvironment : IO Environment := do
  enableInitializersExecution
  initSearchPath (← getBuildDir)
  let opts := Elab.async.set ({} : Options) false
  match ← Elab.runFrontend "import Lean\n" opts "VirNativeWrappers.lean" `VirNativeWrappers with
  | some env => return env
  | none => throw <| IO.userError "failed to load the Lean environment for native wrapper generation"

def resolveNativeExternsIO
    (env : Environment) (extraNames : Array Name := #[]) : IO (Array NativeExtern) := do
  match resolveNativeExternsWithExtras env extraNames with
  | .ok externs => pure externs
  | .error error => throw <| IO.userError error

unsafe def generateCatalog : IO String := do
  let env ← loadEnvironment
  return nativeExternCatalogJson (← resolveNativeExternsIO env) ++ "\n"

unsafe def generate (extraNames : Array Name := #[]) : IO (String × String) := do
  let env ← loadEnvironment
  let externs ← resolveNativeExternsIO env extraNames
  let opts := maxHeartbeats.set ({} : Options) 0
  let action : CoreM (String × String) := do
    let wrapperDecls := wrapperDecls externs
    Compiler.compile wrapperDecls
    let boxedDecls := wrapperDecls.map Compiler.LCNF.mkBoxedName
    -- The emitted boxed bodies depend on the now-local extern declarations.
    -- Include both sets so `emitCForDecls` can order every collected local declaration.
    let source ← Compiler.LCNF.emitCForDecls `VirNativeWrappers (wrapperDecls ++ boxedDecls)
    return (source, ← generatedRegistry externs)
  let (outputs, state) ←
    action.toIO { fileName := "VirNativeWrappers.lean", fileMap := default, options := opts } { env }
  for message in state.messages.unreported do
    IO.eprintln (← message.toString)
  if state.messages.hasErrors then
    throw <| IO.userError "native wrapper compilation failed"
  return outputs

def writeFileIfChanged (path : System.FilePath) (contents : String) : IO Unit := do
  if ← path.pathExists then
    if (← IO.FS.readFile path) == contents then
      return
  IO.FS.writeFile path contents

end Vir.GenerateNativeWrappers

unsafe def main (args : List String) : IO UInt32 := do
  match args with
  | ["--catalog"] =>
      IO.print (← Vir.GenerateNativeWrappers.generateCatalog)
      return 0
  | [sourceOutput, registryOutput] =>
      let (source, registry) ← Vir.GenerateNativeWrappers.generate
      Vir.GenerateNativeWrappers.writeFileIfChanged sourceOutput source
      Vir.GenerateNativeWrappers.writeFileIfChanged registryOutput registry
      return 0
  | ["--extras", extrasPath, sourceOutput, registryOutput] =>
      let names ← Vir.GenerateNativeWrappers.readExtraNames extrasPath
      let (source, registry) ← Vir.GenerateNativeWrappers.generate names
      Vir.GenerateNativeWrappers.writeFileIfChanged sourceOutput source
      Vir.GenerateNativeWrappers.writeFileIfChanged registryOutput registry
      return 0
  | _ =>
      IO.eprintln <|
        "usage: vir_native_wrappers --catalog | <output.cpp> <registry.inc> | " ++
        "--extras <names.txt> <output.cpp> <registry.inc>"
      return 2
