/-
Copyright (c) 2026 Lean FRO LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Author: Emilio J. Gallego Arias
-/

import Lean.Compiler.LCNF.EmitC
import Lean.Compiler.Main
import Lean.Elab.Frontend
import Vir.GeneratePackage.NativeExterns

open Lean

namespace Vir.GenerateNativeWrappers

open Vir.GeneratePackage

def wrapperExterns : Array NativeExtern :=
  nativeExterns.filter (·.generateBoxedWrapper)

def wrapperDecls : Array Name :=
  wrapperExterns.map (·.name)

def generatedRegistry : CoreM String := do
  let env ← getEnv
  let macroLine :=
    if wrapperExterns.isEmpty then
      "#define VIR_COMPILER_NATIVE_SYMBOLS(X)"
    else
      "#define VIR_COMPILER_NATIVE_SYMBOLS(X) \\"
  let mut lines : Array String := #[
    "/*",
    "Generated by vir_native_wrappers from Vir.GeneratePackage.nativeExterns.",
    "*/",
    "",
    macroLine
  ]
  let mut index := 0
  for ext in wrapperExterns do
    index := index + 1
    let stem := getSymbolStem env ext.name
    let boxedSymbol := mkMangledBoxedName stem
    let suffix := if index == wrapperExterns.size then "" else " \\"
    lines := lines.push s!"    X(\"{ext.name}\", \"{ext.symbol}\", {boxedSymbol}){suffix}"
  return "\n".intercalate lines.toList ++ "\n"

unsafe def loadEnvironment : IO Environment := do
  enableInitializersExecution
  initSearchPath (← getBuildDir)
  let opts := Elab.async.set ({} : Options) false
  match ← Elab.runFrontend "import Lean\n" opts "VirNativeWrappers.lean" `VirNativeWrappers with
  | some env => return env
  | none => throw <| IO.userError "failed to load the Lean environment for native wrapper generation"

unsafe def generate : IO (String × String) := do
  let env ← loadEnvironment
  let opts := maxHeartbeats.set ({} : Options) 0
  let action : CoreM (String × String) := do
    Compiler.compile wrapperDecls
    let boxedDecls := wrapperDecls.map Compiler.LCNF.mkBoxedName
    -- The emitted boxed bodies depend on the now-local extern declarations.
    -- Include both sets so `emitCForDecls` can order every collected local declaration.
    let source ← Compiler.LCNF.emitCForDecls `VirNativeWrappers (wrapperDecls ++ boxedDecls)
    return (source, ← generatedRegistry)
  let (outputs, state) ←
    action.toIO { fileName := "VirNativeWrappers.lean", fileMap := default, options := opts } { env }
  for message in state.messages.unreported do
    IO.eprintln (← message.toString)
  if state.messages.hasErrors then
    throw <| IO.userError "native wrapper compilation failed"
  return outputs

def writeFileIfChanged (path : System.FilePath) (contents : String) : IO Unit := do
  if ← path.pathExists then
    if (← IO.FS.readFile path) == contents then
      return
  IO.FS.writeFile path contents

end Vir.GenerateNativeWrappers

unsafe def main (args : List String) : IO UInt32 := do
  match args with
  | [sourceOutput, registryOutput] =>
      let (source, registry) ← Vir.GenerateNativeWrappers.generate
      Vir.GenerateNativeWrappers.writeFileIfChanged sourceOutput source
      Vir.GenerateNativeWrappers.writeFileIfChanged registryOutput registry
      return 0
  | _ =>
      IO.eprintln "usage: vir_native_wrappers <output.cpp> <registry.inc>"
      return 2
