/-
Copyright (c) 2026 Lean FRO LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Author: Emilio J. Gallego Arias
-/

import Lean.Compiler.LCNF.EmitC
import Lean.Compiler.Main
import Lean.Elab.Frontend
import Vir.ClientNativeExternManifest
import Vir.GeneratePackage.Json
import Vir.GeneratePackage.NativeExterns

open Lean

namespace Vir.GenerateNativeWrappers

open Vir.GeneratePackage

def wrapperExterns (externs : Array NativeExtern) : Array NativeExtern :=
  externs.filter (·.generateBoxedWrapper)

def wrapperDecls (externs : Array NativeExtern) : Array Name :=
  wrapperExterns externs |>.map (·.name)

def readExtraNames (path : System.FilePath) : IO (Array Name) := do
  let mut names := #[]
  for line in (← IO.FS.readFile path).splitOn "\n" do
    let line := line.trimAscii.toString
    if line.isEmpty || line.startsWith "#" then
      continue
    let name ← IO.ofExcept (parseDottedName line)
    if names.contains name then
      throw <| IO.userError s!"duplicate extra native extern `{name}`"
    names := names.push name
  if names.isEmpty then
    throw <| IO.userError s!"extra native extern file `{path}` is empty"
  return names

def nativeExternCatalogJson (externs : Array NativeExtern) : String :=
  jsonObject #[
    ("format", jsonString "lean-vir-native-extern-catalog"),
    ("version", jsonNat 1),
    ("externs", jsonArray (externs.map fun ext => jsonObject #[
      ("name", jsonName ext.name),
      ("symbol", jsonString ext.symbol),
      ("generateBoxedWrapper", jsonBool ext.generateBoxedWrapper),
      ("params", jsonArray (ext.params.map fun param => jsonObject #[
        ("index", jsonNat param.x.idx),
        ("borrow", jsonBool param.borrow),
        ("type", jsonString (nativeIRTypeLabel param.ty))
      ])),
      ("resultType", jsonString (nativeIRTypeLabel ext.resultType)),
      ("deps", jsonArray (ext.deps.map jsonName))
    ]))
  ]

def generatedRegistry (externs : Array NativeExtern) : CoreM String := do
  let env ← getEnv
  let wrapperExterns := wrapperExterns externs
  let macroLine :=
    if wrapperExterns.isEmpty then
      "#define VIR_COMPILER_NATIVE_SYMBOLS(X)"
    else
      "#define VIR_COMPILER_NATIVE_SYMBOLS(X) \\"
  let mut lines : Array String := #[
    "/*",
    "Generated by vir_native_wrappers from the selected native extern catalog.",
    "*/",
    "",
    macroLine
  ]
  let mut index := 0
  for ext in wrapperExterns do
    index := index + 1
    let stem := getSymbolStem env ext.name
    let boxedSymbol := mkMangledBoxedName stem
    let suffix := if index == wrapperExterns.size then "" else " \\"
    lines := lines.push s!"    X(\"{ext.name}\", \"{ext.symbol}\", {boxedSymbol}){suffix}"
  return "\n".intercalate lines.toList ++ "\n"

def sameBoxedAbi (lhs rhs : NativeExtern) : Bool :=
  lhs.params.size == rhs.params.size && lhs.resultType == rhs.resultType &&
    (lhs.params.zip rhs.params |>.all fun (lhs, rhs) =>
      lhs.borrow == rhs.borrow && lhs.ty == rhs.ty
    )

def validateSharedLookupStems
    (externs : Array NativeExtern) (clientNames : Array Name) : Except String Unit := do
  for ext in externs do
    for prior in externs do
      if (clientNames.contains prior.name || clientNames.contains ext.name) &&
          prior.name.toString < ext.name.toString && prior.symbol == ext.symbol &&
          !sameBoxedAbi prior ext then
        throw <| s!"native externs `{prior.name}` and `{ext.name}` share lookup stem " ++
          s!"`{ext.symbol}` with incompatible boxed ABIs"

unsafe def loadEnvironment (modules : Array Name := #[]) : IO Environment := do
  enableInitializersExecution
  initSearchPath (← getBuildDir)
  let opts := Elab.async.set ({} : Options) false
  let imports := modules.map fun moduleName => s!"import {moduleName}"
  let contents := "import Lean\n" ++ "\n".intercalate imports.toList ++ "\n"
  match ← Elab.runFrontend contents opts "VirNativeWrappers.lean" `VirNativeWrappers with
  | some env => return env
  | none => throw <| IO.userError "failed to load the Lean environment for native wrapper generation"

def resolveNativeExternsIO
    (env : Environment) (extraNames : Array Name := #[]) : IO (Array NativeExtern) := do
  match resolveNativeExternsWithExtras env extraNames with
  | .ok externs =>
      match validateSharedLookupStems externs extraNames with
      | .ok _ => pure externs
      | .error error => throw <| IO.userError error
  | .error error => throw <| IO.userError error

unsafe def generateCatalog : IO String := do
  let env ← loadEnvironment
  return nativeExternCatalogJson (← resolveNativeExternsIO env) ++ "\n"

unsafe def generateInEnvironment
    (env : Environment) (extraNames : Array Name := #[]) : IO (String × String × Array NativeExtern) := do
  let externs ← resolveNativeExternsIO env extraNames
  let opts := maxHeartbeats.set ({} : Options) 0
  let action : CoreM (String × String) := do
    let wrapperDecls := wrapperDecls externs
    Compiler.compile wrapperDecls
    let boxedDecls := wrapperDecls.map Compiler.LCNF.mkBoxedName
    -- The emitted boxed bodies depend on the now-local extern declarations.
    -- Include both sets so `emitCForDecls` can order every collected local declaration.
    let source ← Compiler.LCNF.emitCForDecls `VirNativeWrappers (wrapperDecls ++ boxedDecls)
    return (source, ← generatedRegistry externs)
  let (outputs, state) ←
    action.toIO { fileName := "VirNativeWrappers.lean", fileMap := default, options := opts } { env }
  for message in state.messages.unreported do
    IO.eprintln (← message.toString)
  if state.messages.hasErrors then
    throw <| IO.userError "native wrapper compilation failed"
  return (outputs.1, outputs.2, externs)

unsafe def generate (extraNames : Array Name := #[]) : IO (String × String) := do
  let (source, registry, _) ← generateInEnvironment (← loadEnvironment) extraNames
  return (source, registry)

def generatedProviderSources (manifest : Vir.ClientNativeExternManifest) : String :=
  "\n".intercalate (manifest.providerSources.map (fun path => path.toString)).toList ++ "\n"

def generatedProviderSymbols
    (manifest : Vir.ClientNativeExternManifest)
    (externs : Array NativeExtern) : Except String String := do
  let clientExterns ← manifest.externs.mapM fun name =>
    match externs.find? (·.name == name) with
    | some ext => pure ext
    | none => throw s!"resolved client-native extern `{name}` is missing from the selected catalog"
  return "\n".intercalate
    (clientExterns.map fun ext => s!"{ext.name}\t{ext.symbol}").toList ++ "\n"

unsafe def generateForManifest
    (manifest : Vir.ClientNativeExternManifest) : IO (String × String × String × String) := do
  let (source, registry, externs) ←
    generateInEnvironment (← loadEnvironment manifest.modules) manifest.externs
  let symbols ← IO.ofExcept <| generatedProviderSymbols manifest externs
  return (
    source,
    registry,
    generatedProviderSources manifest,
    symbols
  )

def writeFileIfChanged (path : System.FilePath) (contents : String) : IO Unit := do
  if ← path.pathExists then
    if (← IO.FS.readFile path) == contents then
      return
  IO.FS.writeFile path contents

end Vir.GenerateNativeWrappers

unsafe def main (args : List String) : IO UInt32 := do
  match args with
  | ["--catalog"] =>
      IO.print (← Vir.GenerateNativeWrappers.generateCatalog)
      return 0
  | [sourceOutput, registryOutput] =>
      let (source, registry) ← Vir.GenerateNativeWrappers.generate
      Vir.GenerateNativeWrappers.writeFileIfChanged sourceOutput source
      Vir.GenerateNativeWrappers.writeFileIfChanged registryOutput registry
      return 0
  | ["--extras", extrasPath, sourceOutput, registryOutput] =>
      let names ← Vir.GenerateNativeWrappers.readExtraNames extrasPath
      let (source, registry) ← Vir.GenerateNativeWrappers.generate names
      Vir.GenerateNativeWrappers.writeFileIfChanged sourceOutput source
      Vir.GenerateNativeWrappers.writeFileIfChanged registryOutput registry
      return 0
  | ["--manifest", manifestPath, sourceOutput, registryOutput, sourcesOutput, symbolsOutput] =>
      let manifest ← Vir.readClientNativeExternManifest manifestPath
      let (source, registry, sources, symbols) ←
        Vir.GenerateNativeWrappers.generateForManifest manifest
      Vir.GenerateNativeWrappers.writeFileIfChanged sourceOutput source
      Vir.GenerateNativeWrappers.writeFileIfChanged registryOutput registry
      Vir.GenerateNativeWrappers.writeFileIfChanged sourcesOutput sources
      Vir.GenerateNativeWrappers.writeFileIfChanged symbolsOutput symbols
      return 0
  | _ =>
      IO.eprintln <|
        "usage: vir_native_wrappers --catalog | <output.cpp> <registry.inc> | " ++
        "--extras <names.txt> <output.cpp> <registry.inc> | " ++
        "--manifest <manifest.json> <output.cpp> <registry.inc> <sources.txt> <symbols.tsv>"
      return 2
