/-
Copyright (c) 2026 Lean FRO LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Author: Emilio J. Gallego Arias
-/

-- Generated by scripts/bindings/generate-lean-bindings.mjs. Do not edit.

import Vir.Js

namespace Lean.Vir

namespace Common

/--
Generated binding for reviewed VIR protocol `common.echo-string`.

VIR-owned smoke-test protocol that round-trips a JavaScript string resource.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-common-protocol-v1`: receiver none; value js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "common.echoString"]
opaque echoStringJs
    (value : @& Lean.Vir.Js String) :
    Lean.Vir.RuntimeM (Lean.Vir.Js String)

/--
Generated binding for reviewed VIR protocol `common.add-nat`.

VIR-owned smoke-test protocol that adds two JavaScript number resources interpreted as natural numbers.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-common-protocol-v1`: receiver none; lhs js-resource/borrowed/call; rhs js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "common.addNat"]
opaque addNatJs
    (lhs : @& Lean.Vir.Js Nat)
    (rhs : @& Lean.Vir.Js Nat) :
    Lean.Vir.RuntimeM (Lean.Vir.Js Nat)

end Common

end Lean.Vir
