/-
Copyright (c) 2026 Lean FRO LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Author: Emilio J. Gallego Arias
-/

-- Generated by scripts/bindings/generate-lean-bindings.mjs. Do not edit.

module

public import Vir.Browser.Types
public import Vir.Infoview.Client.Types
public import Vir.React.Types

public section

namespace Lean.Vir

namespace Infoview

/--
Generated binding for reviewed VIR protocol `infoview.client-notification-effect`.

Calls the upstream infoview hook with the exact method, callback and dependency array or undefined. Upstream treats undefined as omitted and owns subscription and cleanup; VIR neither queues nor filters notifications.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-infoview-protocol-v1` (bridge-handle retention): receiver none; method js-resource/borrowed/call; callback js-resource/borrowed/call; deps js-resource/borrowed/call; result immediate/value.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "infoview.useClientNotificationEffect"]
opaque useClientNotificationEffect
    {params : Type}
    (method : @& Lean.Vir.Js String)
    (callback : @& Lean.Vir.Js.Function1 (Lean.Vir.Js params) Unit)
    (deps : @& Lean.Vir.Js.UndefinedOr React.DependencyList) :
    Lean.Vir.React.ReactM Unit

end Infoview

namespace Infoview.ClientRequestOptions

/--
Generated binding for reviewed VIR protocol `infoview.request-options.empty`.

Constructs an ordinary empty ClientRequestOptions object, omitting abortSignal rather than substituting null.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-infoview-protocol-v1` (bridge-handle retention): receiver none; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "infoview.clientRequestOptions.empty"]
opaque empty : Lean.Vir.RuntimeM (Lean.Vir.Js Infoview.ClientRequestOptions)

/--
Generated binding for reviewed VIR protocol `infoview.request-options.abort-signal`.

Assigns the exact native AbortSignal to options.abortSignal without wrapping the signal or changing cancellation behavior.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-infoview-protocol-v1` (bridge-handle retention): receiver none; options js-resource/borrowed/call; signal js-resource/borrowed/call; result immediate/value.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "infoview.clientRequestOptions.setAbortSignal"]
opaque setAbortSignal
    (options : @& Lean.Vir.Js Infoview.ClientRequestOptions)
    (signal : @& Lean.Vir.Js Browser.AbortSignal) :
    Lean.Vir.RuntimeM Unit

end Infoview.ClientRequestOptions

namespace Infoview.RpcSession

/--
Generated binding for reviewed VIR protocol `infoview.rpc-session.call`.

Calls the exact position-specific infoview RPC session with the exact method string and request object, omits its optional ClientRequestOptions argument, and returns its native Promise.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-infoview-protocol-v1` (bridge-handle retention): receiver none; session js-resource/borrowed/call; method js-resource/borrowed/call; params js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "infoview.rpcSession.call"]
opaque call
    {params : Type}
    {result : Type}
    (session : @& Lean.Vir.Js Infoview.RpcSession)
    (method : @& Lean.Vir.Js String)
    (params : @& Lean.Vir.Js params) :
    Lean.Vir.RuntimeM (Lean.Vir.Js.Promise result)

/--
Generated binding for reviewed VIR protocol `infoview.rpc-session.call-options`.

Passes the exact ClientRequestOptions and AbortSignal to the position-specific session; params use Js.Any to fit the interpreter arity limit without changing their value. Cancellation and Promise settlement follow the official RPC client and server.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-infoview-protocol-v1` (bridge-handle retention): receiver none; session js-resource/borrowed/call; method js-resource/borrowed/call; params js-resource/borrowed/call; options js-resource/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js "infoview.rpcSession.callWithOptions"]
opaque callWithOptions
    {result : Type}
    (session : @& Lean.Vir.Js Infoview.RpcSession)
    (method : @& Lean.Vir.Js String)
    (params : @& Lean.Vir.Js.Any)
    (options : @& Lean.Vir.Js Infoview.ClientRequestOptions) :
    Lean.Vir.RuntimeM (Lean.Vir.Js.Promise result)

end Infoview.RpcSession

end Lean.Vir
